//! A/B-test router generator (Solidity / EVM).
//!
//! Part of the `evolution` module. The on-chain bucketing mirrors the pure-Rust
//! [`super::assign_variant`] exactly, so off-chain analytics agree with the
//! contract.

use super::{AbTestConfig, VariantAssignment, cumulative_thresholds, validate_ab_variants};
use crate::tokenization::jurisdiction_compliance_tag;
use crate::{ChainResult, ContractGenerator, GeneratedContract};

impl ContractGenerator {
    /// Emits the Solidity source for a weight-bucketed A/B-test router.
    pub(crate) fn generate_solidity_ab_test(
        &self,
        config: &AbTestConfig,
    ) -> ChainResult<GeneratedContract> {
        validate_ab_variants(&config.variants)?;
        let compliance_tag = jurisdiction_compliance_tag(config.jurisdiction);
        let thresholds = cumulative_thresholds(&config.variants);
        let variant_count = config.variants.len();
        let is_sticky = config.assignment == VariantAssignment::Sticky;
        let has_implementations = config
            .variants
            .iter()
            .any(|variant| variant.implementation.is_some());

        let mut source = String::from("// SPDX-License-Identifier: MIT\n");
        source.push_str("pragma solidity ^0.8.20;\n\n");
        source.push_str("import \"@openzeppelin/contracts/access/Ownable2Step.sol\";\n\n");

        // -- NatSpec header ----------------------------------------------------
        source.push_str(&format!("/// @title {}\n", config.name));
        source.push_str(&format!(
            "/// @notice On-chain A/B test '{}' across {} variants ({} assignment).\n",
            config.experiment_key,
            variant_count,
            config.assignment.label()
        ));
        source.push_str(&format!(
            "/// @dev Compliance framework: {compliance_tag}. Generated by Legalis-Chain.\n"
        ));
        source.push_str("/// @dev Variant weights (basis points):\n");
        for variant in &config.variants {
            source.push_str(&format!(
                "/// @dev   - {}: {}\n",
                variant.label, variant.weight_basis_points
            ));
        }
        source.push_str("/// @dev Security Considerations:\n");
        source.push_str(
            "/// @dev  - Bucketing is keccak(EXPERIMENT_KEY, user) % 10000: deterministic and\n",
        );
        source.push_str(
            "/// @dev    namespaced, so two experiments never collide on the same address.\n",
        );
        source.push_str("/// @dev Gas Notes:\n");
        source.push_str(
            "/// @dev  - assignVariant is an unrolled comparison chain (no storage reads).\n\n",
        );

        // -- Contract declaration & constants ----------------------------------
        source.push_str(&format!("contract {} is Ownable2Step {{\n", config.name));
        source.push_str(&format!(
            "    bytes32 public constant EXPERIMENT_KEY = keccak256(bytes(\"{}\"));\n",
            config.experiment_key
        ));
        source.push_str("    uint256 public constant BPS_DENOMINATOR = 10000;\n");
        source.push_str(&format!(
            "    uint256 public constant VARIANT_COUNT = {variant_count};\n\n"
        ));

        // -- Storage -----------------------------------------------------------
        source.push_str(&format!("    string[{variant_count}] private _labels;\n"));
        if has_implementations {
            source.push_str(&format!(
                "    address[{variant_count}] private _implementations;\n"
            ));
        }
        if is_sticky {
            source.push_str(
                "    /// @dev variant index + 1 (0 means not yet committed).\n    mapping(address => uint256) private _sticky;\n",
            );
        }
        if config.measure_conversions {
            source.push_str(&format!("    uint256[{variant_count}] public exposures;\n"));
            source.push_str(&format!(
                "    uint256[{variant_count}] public conversions;\n"
            ));
        }
        source.push('\n');

        // -- Events ------------------------------------------------------------
        source.push_str("    event Assigned(address indexed user, uint256 variant);\n");
        if config.measure_conversions {
            source.push_str("    event Exposure(address indexed user, uint256 variant);\n");
            source.push_str("    event Converted(address indexed user, uint256 variant);\n");
        }
        source.push('\n');

        // -- Constructor -------------------------------------------------------
        source.push_str("    constructor() Ownable(msg.sender) {\n");
        for (index, variant) in config.variants.iter().enumerate() {
            source.push_str(&format!(
                "        _labels[{}] = \"{}\";\n",
                index, variant.label
            ));
        }
        if has_implementations {
            for (index, variant) in config.variants.iter().enumerate() {
                let address = variant.implementation.as_deref().unwrap_or("address(0)");
                source.push_str(&format!("        _implementations[{index}] = {address};\n"));
            }
        }
        source.push_str("    }\n\n");

        // -- Views: metadata ---------------------------------------------------
        source.push_str("    /// @notice Label of a variant by index.\n");
        source.push_str(
            "    function variantLabel(uint256 index) external view returns (string memory) {\n",
        );
        source.push_str("        require(index < VARIANT_COUNT, \"AB: bad index\");\n");
        source.push_str("        return _labels[index];\n");
        source.push_str("    }\n\n");
        if has_implementations {
            source.push_str("    /// @notice Routing target of a variant by index.\n");
            source.push_str(
                "    function variantImplementation(uint256 index) public view returns (address) {\n",
            );
            source.push_str("        require(index < VARIANT_COUNT, \"AB: bad index\");\n");
            source.push_str("        return _implementations[index];\n");
            source.push_str("    }\n\n");
        }

        // -- Bucket + assignment -----------------------------------------------
        source.push_str("    /// @notice Stable bucket in [0, 10000) for a user.\n");
        source.push_str("    function bucketOf(address user) public view returns (uint256) {\n");
        source.push_str(
            "        return uint256(keccak256(abi.encodePacked(EXPERIMENT_KEY, user))) % BPS_DENOMINATOR;\n",
        );
        source.push_str("    }\n\n");

        source.push_str("    /// @notice Deterministic variant for a bucket value.\n");
        source.push_str(
            "    function variantForBucket(uint256 bucket) public pure returns (uint256) {\n",
        );
        self.push_ab_bucket_chain(&mut source, &thresholds);
        source.push_str("    }\n\n");

        source.push_str("    /// @notice Variant currently assigned to a user.\n");
        source
            .push_str("    function assignVariant(address user) public view returns (uint256) {\n");
        if is_sticky {
            source.push_str("        uint256 committed = _sticky[user];\n");
            source.push_str("        if (committed != 0) {\n");
            source.push_str("            return committed - 1;\n");
            source.push_str("        }\n");
        }
        source.push_str("        return variantForBucket(bucketOf(user));\n");
        source.push_str("    }\n");

        if is_sticky {
            source.push('\n');
            source.push_str(
                "    /// @notice Persist the caller's assignment so later weight changes cannot move them.\n",
            );
            source.push_str("    function commitAssignment() external returns (uint256) {\n");
            source.push_str("        uint256 committed = _sticky[msg.sender];\n");
            source.push_str("        if (committed != 0) {\n");
            source.push_str("            return committed - 1;\n");
            source.push_str("        }\n");
            source.push_str("        uint256 variant = variantForBucket(bucketOf(msg.sender));\n");
            source.push_str("        _sticky[msg.sender] = variant + 1; // effects before event\n");
            source.push_str("        emit Assigned(msg.sender, variant);\n");
            source.push_str("        return variant;\n");
            source.push_str("    }\n");
        }

        if config.measure_conversions {
            self.push_ab_metrics(&mut source);
        }

        // -- Routing helper ----------------------------------------------------
        if has_implementations {
            source.push('\n');
            source.push_str("    /// @notice Routing target for a user's assigned variant.\n");
            source.push_str("    function route(address user) external view returns (address) {\n");
            source.push_str("        return variantImplementation(assignVariant(user));\n");
            source.push_str("    }\n");
        }

        source.push_str("}\n");

        Ok(GeneratedContract {
            name: config.name.clone(),
            source,
            platform: self.platform,
            abi: None,
            deployment_script: None,
        })
    }

    /// Appends the unrolled bucket -> variant comparison chain.
    fn push_ab_bucket_chain(&self, source: &mut String, thresholds: &[u32]) {
        // The final variant owns every remaining bucket, so only the first
        // `len - 1` thresholds need an explicit branch.
        let last_index = thresholds.len().saturating_sub(1);
        for (index, threshold) in thresholds.iter().enumerate().take(last_index) {
            source.push_str(&format!("        if (bucket < {threshold}) {{\n"));
            source.push_str(&format!("            return {index};\n"));
            source.push_str("        }\n");
        }
        source.push_str(&format!("        return {last_index};\n"));
    }

    /// Appends the exposure/conversion accounting functions.
    fn push_ab_metrics(&self, source: &mut String) {
        source.push('\n');
        source.push_str("    /// @notice Record that a user was exposed to their variant.\n");
        source.push_str("    function recordExposure(address user) external onlyOwner {\n");
        source.push_str("        uint256 variant = assignVariant(user);\n");
        source.push_str("        exposures[variant] += 1;\n");
        source.push_str("        emit Exposure(user, variant);\n");
        source.push_str("    }\n\n");
        source.push_str("    /// @notice Record that a user converted under their variant.\n");
        source.push_str("    function recordConversion(address user) external onlyOwner {\n");
        source.push_str("        uint256 variant = assignVariant(user);\n");
        source.push_str("        conversions[variant] += 1;\n");
        source.push_str("        emit Converted(user, variant);\n");
        source.push_str("    }\n");
    }
}
