//! Emergency-pause controller generator (Solidity / EVM).
//!
//! Part of the `evolution` module. Differentiated from the existing circuit
//! breaker generator by three properties: (1) guardians may *pause* but only
//! governance may *unpause*, (2) every pause auto-expires after a maximum
//! duration so a rogue guardian cannot freeze the system forever, and (3)
//! unpausing is subject to a mandatory cool-down.

use super::{EmergencyPauseConfig, scope_constant_name, validate_emergency_pause};
use crate::tokenization::jurisdiction_compliance_tag;
use crate::{ChainResult, ContractGenerator, GeneratedContract};

impl ContractGenerator {
    /// Emits the Solidity source for a tiered emergency-pause controller.
    pub(crate) fn generate_solidity_emergency_pause(
        &self,
        config: &EmergencyPauseConfig,
    ) -> ChainResult<GeneratedContract> {
        validate_emergency_pause(config)?;
        let compliance_tag = jurisdiction_compliance_tag(config.jurisdiction);
        let has_auto_expiry = config.max_pause_seconds > 0;
        let has_cooldown = config.unpause_delay_seconds > 0;
        // Names of the scope constants, defaulting to a single global scope.
        let scope_constants: Vec<(String, String)> = if config.scopes.is_empty() {
            vec![("SCOPE_GLOBAL".to_string(), "GLOBAL".to_string())]
        } else {
            config
                .scopes
                .iter()
                .map(|scope| (scope_constant_name(scope), scope.clone()))
                .collect()
        };

        let mut source = String::from("// SPDX-License-Identifier: MIT\n");
        source.push_str("pragma solidity ^0.8.20;\n\n");

        // -- NatSpec header ----------------------------------------------------
        source.push_str(&format!("/// @title {}\n", config.name));
        source.push_str(&format!(
            "/// @notice Tiered emergency-pause controller over {} scope(s).\n",
            scope_constants.len()
        ));
        source.push_str(&format!(
            "/// @dev Compliance framework: {compliance_tag}. Generated by Legalis-Chain.\n"
        ));
        source.push_str("/// @dev Security Considerations:\n");
        source.push_str(
            "/// @dev  - Guardians can PAUSE quickly; only governance can UNPAUSE (separation of duty).\n",
        );
        if has_auto_expiry {
            source.push_str(&format!(
                "/// @dev  - Every pause auto-expires after {} seconds unless governance extends it,\n",
                config.max_pause_seconds
            ));
            source.push_str(
                "/// @dev    so a compromised guardian cannot freeze the protocol indefinitely.\n",
            );
        } else {
            source.push_str(
                "/// @dev  - Pauses are indefinite (no auto-expiry); governance must unpause.\n",
            );
        }
        if has_cooldown {
            source.push_str(&format!(
                "/// @dev  - Unpausing requires a request plus a {}-second cool-down.\n",
                config.unpause_delay_seconds
            ));
        }
        source.push_str("/// @dev Gas Notes:\n");
        source.push_str(
            "/// @dev  - State is keyed by scope; isPaused is an O(1) view with no loops.\n\n",
        );

        // -- Contract declaration & constants ----------------------------------
        source.push_str(&format!("contract {} {{\n", config.name));
        source.push_str("    address public governance;\n");
        source.push_str(&format!(
            "    uint256 public constant MAX_PAUSE_DURATION = {} seconds;\n",
            config.max_pause_seconds
        ));
        source.push_str(&format!(
            "    uint256 public constant UNPAUSE_DELAY = {} seconds;\n\n",
            config.unpause_delay_seconds
        ));

        source.push_str("    // Declared pause scopes.\n");
        for (constant, raw) in &scope_constants {
            source.push_str(&format!(
                "    bytes32 public constant {constant} = keccak256(bytes(\"{raw}\"));\n"
            ));
        }
        source.push('\n');

        // -- Types & storage ---------------------------------------------------
        source.push_str("    struct PauseInfo {\n");
        source.push_str("        uint256 pausedAt;   // 0 = not paused\n");
        source
            .push_str("        uint256 expiry;     // 0 = indefinite; else auto-lift timestamp\n");
        source.push_str("        uint256 unpauseEta; // 0 = no pending unpause request\n");
        source.push_str("    }\n");
        source.push_str("    mapping(bytes32 => PauseInfo) public pauses;\n");
        source.push_str("    mapping(bytes32 => bool) public knownScope;\n");
        source.push_str("    mapping(address => bool) public isGuardian;\n\n");

        // -- Events ------------------------------------------------------------
        source.push_str(
            "    event Paused(bytes32 indexed scope, address indexed guardian, uint256 expiry);\n",
        );
        source.push_str("    event Unpaused(bytes32 indexed scope);\n");
        if has_auto_expiry {
            source.push_str("    event PauseExtended(bytes32 indexed scope, uint256 expiry);\n");
        }
        if has_cooldown {
            source.push_str("    event UnpauseRequested(bytes32 indexed scope, uint256 eta);\n");
        }
        source.push_str("    event GuardianSet(address indexed guardian, bool enabled);\n");
        source.push_str(
            "    event GovernanceTransferred(address indexed previous, address indexed next);\n\n",
        );

        // -- Modifiers ---------------------------------------------------------
        source.push_str("    modifier onlyGovernance() {\n");
        source.push_str("        require(msg.sender == governance, \"Pause: not governance\");\n");
        source.push_str("        _;\n");
        source.push_str("    }\n\n");
        source.push_str("    modifier onlyGuardian() {\n");
        source.push_str("        require(isGuardian[msg.sender], \"Pause: not guardian\");\n");
        source.push_str("        _;\n");
        source.push_str("    }\n\n");

        // -- Constructor -------------------------------------------------------
        source.push_str(&format!(
            "    constructor() {{\n        governance = {};\n",
            config.governance
        ));
        for guardian in &config.guardians {
            source.push_str(&format!("        isGuardian[{guardian}] = true;\n"));
        }
        for (constant, _) in &scope_constants {
            source.push_str(&format!("        knownScope[{constant}] = true;\n"));
        }
        source.push_str("    }\n\n");

        self.push_pause_admin(&mut source);
        self.push_pause_lifecycle(&mut source, has_auto_expiry, has_cooldown);
        self.push_pause_views(&mut source);

        source.push_str("}\n");

        Ok(GeneratedContract {
            name: config.name.clone(),
            source,
            platform: self.platform,
            abi: None,
            deployment_script: None,
        })
    }

    /// Appends guardian and governance administration functions.
    fn push_pause_admin(&self, source: &mut String) {
        source.push_str("    /// @notice Enable or disable a guardian.\n");
        source.push_str(
            "    function setGuardian(address guardian, bool enabled) external onlyGovernance {\n",
        );
        source.push_str("        isGuardian[guardian] = enabled;\n");
        source.push_str("        emit GuardianSet(guardian, enabled);\n");
        source.push_str("    }\n\n");
        source.push_str("    /// @notice Transfer governance to a new address.\n");
        source
            .push_str("    function transferGovernance(address next) external onlyGovernance {\n");
        source.push_str("        require(next != address(0), \"Pause: zero governance\");\n");
        source.push_str("        emit GovernanceTransferred(governance, next);\n");
        source.push_str("        governance = next;\n");
        source.push_str("    }\n\n");
    }

    /// Appends the pause/extend/unpause lifecycle.
    fn push_pause_lifecycle(&self, source: &mut String, has_auto_expiry: bool, has_cooldown: bool) {
        // pause
        source.push_str("    /// @notice Pause a scope (guardian action).\n");
        source.push_str("    function pause(bytes32 scope) external onlyGuardian {\n");
        source.push_str("        require(knownScope[scope], \"Pause: unknown scope\");\n");
        source.push_str("        PauseInfo storage info = pauses[scope];\n");
        source.push_str("        require(!_effectivelyPaused(info), \"Pause: already paused\");\n");
        source.push_str("        info.pausedAt = block.timestamp;\n");
        if has_auto_expiry {
            source.push_str("        info.expiry = block.timestamp + MAX_PAUSE_DURATION;\n");
        } else {
            source.push_str("        info.expiry = 0;\n");
        }
        source.push_str("        info.unpauseEta = 0;\n");
        source.push_str("        emit Paused(scope, msg.sender, info.expiry);\n");
        source.push_str("    }\n\n");

        // extend (only when auto-expiry exists)
        if has_auto_expiry {
            source.push_str(
                "    /// @notice Governance extends a pause beyond its current auto-expiry.\n",
            );
            source.push_str("    function extendPause(bytes32 scope) external onlyGovernance {\n");
            source.push_str("        PauseInfo storage info = pauses[scope];\n");
            source.push_str("        require(_effectivelyPaused(info), \"Pause: not paused\");\n");
            source.push_str("        info.expiry = block.timestamp + MAX_PAUSE_DURATION;\n");
            source.push_str("        emit PauseExtended(scope, info.expiry);\n");
            source.push_str("    }\n\n");
        }

        // unpause (with or without cool-down)
        if has_cooldown {
            source.push_str(
                "    /// @notice Governance requests an unpause, starting the cool-down.\n",
            );
            source
                .push_str("    function requestUnpause(bytes32 scope) external onlyGovernance {\n");
            source.push_str("        PauseInfo storage info = pauses[scope];\n");
            source.push_str("        require(_effectivelyPaused(info), \"Pause: not paused\");\n");
            source.push_str("        info.unpauseEta = block.timestamp + UNPAUSE_DELAY;\n");
            source.push_str("        emit UnpauseRequested(scope, info.unpauseEta);\n");
            source.push_str("    }\n\n");
            source
                .push_str("    /// @notice Finalise an unpause after the cool-down has elapsed.\n");
            source.push_str("    function unpause(bytes32 scope) external onlyGovernance {\n");
            source.push_str("        PauseInfo storage info = pauses[scope];\n");
            source.push_str(
                "        require(info.unpauseEta != 0 && block.timestamp >= info.unpauseEta, \"Pause: cool-down active\");\n",
            );
            source.push_str("        _clear(info);\n");
            source.push_str("        emit Unpaused(scope);\n");
            source.push_str("    }\n\n");
        } else {
            source.push_str("    /// @notice Governance lifts a pause.\n");
            source.push_str("    function unpause(bytes32 scope) external onlyGovernance {\n");
            source.push_str("        PauseInfo storage info = pauses[scope];\n");
            source.push_str("        require(info.pausedAt != 0, \"Pause: not paused\");\n");
            source.push_str("        _clear(info);\n");
            source.push_str("        emit Unpaused(scope);\n");
            source.push_str("    }\n\n");
        }

        source.push_str("    function _clear(PauseInfo storage info) private {\n");
        source.push_str("        info.pausedAt = 0;\n");
        source.push_str("        info.expiry = 0;\n");
        source.push_str("        info.unpauseEta = 0;\n");
        source.push_str("    }\n\n");
    }

    /// Appends the read-only pause predicates.
    fn push_pause_views(&self, source: &mut String) {
        source.push_str(
            "    function _effectivelyPaused(PauseInfo storage info) private view returns (bool) {\n",
        );
        source.push_str("        if (info.pausedAt == 0) {\n");
        source.push_str("            return false;\n");
        source.push_str("        }\n");
        source.push_str("        if (info.expiry != 0 && block.timestamp >= info.expiry) {\n");
        source.push_str("            return false; // auto-expired\n");
        source.push_str("        }\n");
        source.push_str("        return true;\n");
        source.push_str("    }\n\n");
        source
            .push_str("    /// @notice Whether a scope is currently paused (auto-expiry aware).\n");
        source.push_str("    function isPaused(bytes32 scope) public view returns (bool) {\n");
        source.push_str("        return _effectivelyPaused(pauses[scope]);\n");
        source.push_str("    }\n\n");
        source.push_str(
            "    /// @notice Reverts if the scope is paused; for cross-contract guards.\n",
        );
        source.push_str("    function checkNotPaused(bytes32 scope) external view {\n");
        source.push_str(
            "        require(!_effectivelyPaused(pauses[scope]), \"Pause: scope paused\");\n",
        );
        source.push_str("    }\n");
    }
}
