//! Feature-flag registry generator (Solidity / EVM).
//!
//! Part of the `evolution` module.

use super::{FeatureFlagConfig, FlagAdminModel, flag_constant_name, validate_feature_flags};
use crate::tokenization::jurisdiction_compliance_tag;
use crate::{ChainResult, ContractGenerator, GeneratedContract};

impl ContractGenerator {
    /// Emits the Solidity source for a feature-flag registry.
    pub(crate) fn generate_solidity_feature_flags(
        &self,
        config: &FeatureFlagConfig,
    ) -> ChainResult<GeneratedContract> {
        validate_feature_flags(&config.flags)?;
        let compliance_tag = jurisdiction_compliance_tag(config.jurisdiction);
        let uses_roles = config.admin_model == FlagAdminModel::Roles;
        let admin_guard = if uses_roles {
            "onlyRole(FLAG_ADMIN_ROLE)"
        } else {
            "onlyOwner"
        };

        let mut source = String::from("// SPDX-License-Identifier: MIT\n");
        source.push_str("pragma solidity ^0.8.20;\n\n");
        if uses_roles {
            source.push_str("import \"@openzeppelin/contracts/access/AccessControl.sol\";\n\n");
        } else {
            source.push_str("import \"@openzeppelin/contracts/access/Ownable2Step.sol\";\n\n");
        }

        // -- NatSpec header ----------------------------------------------------
        source.push_str(&format!("/// @title {}\n", config.name));
        source.push_str(&format!(
            "/// @notice On-chain feature-flag registry governing {} flag(s).\n",
            config.flags.len()
        ));
        source.push_str(&format!(
            "/// @dev Compliance framework: {compliance_tag}. Generated by Legalis-Chain.\n"
        ));
        source.push_str("/// @dev Security Considerations:\n");
        source.push_str(&format!(
            "/// @dev  - Flag administration is gated by {}.\n",
            if uses_roles {
                "FLAG_ADMIN_ROLE (transferable to a multisig)"
            } else {
                "Ownable2Step (two-step ownership transfer)"
            }
        ));
        if config.global_kill_switch {
            source.push_str(
                "/// @dev  - A global kill switch force-disables every flag in one transaction.\n",
            );
        }
        source.push_str("/// @dev Gas Notes:\n");
        source.push_str(
            "/// @dev  - Reads are O(1) mapping lookups; flag keys are compile-time constants.\n\n",
        );

        // -- Contract declaration ----------------------------------------------
        if uses_roles {
            source.push_str(&format!("contract {} is AccessControl {{\n", config.name));
            source.push_str(
                "    bytes32 public constant FLAG_ADMIN_ROLE = keccak256(\"FLAG_ADMIN_ROLE\");\n\n",
            );
        } else {
            source.push_str(&format!("contract {} is Ownable2Step {{\n", config.name));
        }

        // -- Declared flag key constants ---------------------------------------
        source.push_str("    // Declared feature-flag keys.\n");
        for flag in &config.flags {
            let constant = flag_constant_name(&flag.key);
            source.push_str(&format!(
                "    /// @notice {}\n    bytes32 public constant {} = keccak256(bytes(\"{}\"));\n",
                flag.description, constant, flag.key
            ));
        }
        source.push('\n');

        // -- Storage -----------------------------------------------------------
        source.push_str("    mapping(bytes32 => bool) private _enabled;\n");
        if config.per_address_overrides {
            source.push_str(
                "    /// @dev 0 = inherit global, 1 = force enabled, 2 = force disabled.\n",
            );
            source.push_str(
                "    mapping(bytes32 => mapping(address => uint8)) private _overrides;\n",
            );
        }
        if config.global_kill_switch {
            source.push_str(
                "    /// @notice When true, isEnabled* returns false for every flag.\n    bool public killSwitch;\n",
            );
        }
        source.push('\n');

        // -- Events ------------------------------------------------------------
        source.push_str("    event FlagChanged(bytes32 indexed key, bool enabled);\n");
        if config.per_address_overrides {
            source.push_str(
                "    event OverrideSet(bytes32 indexed key, address indexed account, uint8 state);\n",
            );
        }
        if config.global_kill_switch {
            source.push_str("    event KillSwitchSet(bool active);\n");
        }
        source.push('\n');

        // -- Constructor -------------------------------------------------------
        if uses_roles {
            source.push_str("    constructor() {\n");
            source.push_str("        _grantRole(DEFAULT_ADMIN_ROLE, msg.sender);\n");
            source.push_str("        _grantRole(FLAG_ADMIN_ROLE, msg.sender);\n");
        } else {
            source.push_str("    constructor() Ownable(msg.sender) {\n");
        }
        for flag in &config.flags {
            if flag.default_enabled {
                let constant = flag_constant_name(&flag.key);
                source.push_str(&format!("        _enabled[{constant}] = true;\n"));
            }
        }
        source.push_str("    }\n\n");

        // -- Admin mutators ----------------------------------------------------
        source.push_str("    /// @notice Enable or disable a flag globally.\n");
        source.push_str(&format!(
            "    function setFlag(bytes32 key, bool enabled) external {admin_guard} {{\n"
        ));
        source.push_str("        _enabled[key] = enabled;\n");
        source.push_str("        emit FlagChanged(key, enabled);\n");
        source.push_str("    }\n\n");

        if config.per_address_overrides {
            source
                .push_str("    /// @notice Set a per-address override (0 inherit, 1 on, 2 off).\n");
            source.push_str(&format!(
                "    function setOverride(bytes32 key, address account, uint8 state) external {admin_guard} {{\n"
            ));
            source.push_str("        require(state <= 2, \"Flags: invalid override\");\n");
            source.push_str("        _overrides[key][account] = state;\n");
            source.push_str("        emit OverrideSet(key, account, state);\n");
            source.push_str("    }\n\n");
        }

        if config.global_kill_switch {
            source.push_str("    /// @notice Toggle the global kill switch.\n");
            source.push_str(&format!(
                "    function setKillSwitch(bool active) external {admin_guard} {{\n"
            ));
            source.push_str("        killSwitch = active;\n");
            source.push_str("        emit KillSwitchSet(active);\n");
            source.push_str("    }\n\n");
        }

        // -- Views -------------------------------------------------------------
        source.push_str("    /// @notice Whether a flag is globally enabled.\n");
        source.push_str("    function isEnabled(bytes32 key) public view returns (bool) {\n");
        if config.global_kill_switch {
            source.push_str("        if (killSwitch) {\n");
            source.push_str("            return false;\n");
            source.push_str("        }\n");
        }
        source.push_str("        return _enabled[key];\n");
        source.push_str("    }\n");

        if config.per_address_overrides {
            source.push('\n');
            source.push_str(
                "    /// @notice Whether a flag is enabled for a specific account (override-aware).\n",
            );
            source.push_str(
                "    function isEnabledFor(bytes32 key, address account) public view returns (bool) {\n",
            );
            if config.global_kill_switch {
                source.push_str("        if (killSwitch) {\n");
                source.push_str("            return false;\n");
                source.push_str("        }\n");
            }
            source.push_str("        uint8 ov = _overrides[key][account];\n");
            source.push_str("        if (ov == 1) {\n");
            source.push_str("            return true;\n");
            source.push_str("        }\n");
            source.push_str("        if (ov == 2) {\n");
            source.push_str("            return false;\n");
            source.push_str("        }\n");
            source.push_str("        return _enabled[key];\n");
            source.push_str("    }\n");
        }

        source.push_str("}\n");

        Ok(GeneratedContract {
            name: config.name.clone(),
            source,
            platform: self.platform,
            abi: None,
            deployment_script: None,
        })
    }
}
