//! Gradual-rollout controller generator (Solidity / EVM).
//!
//! Part of the `evolution` module. The on-chain `currentBps()` view mirrors the
//! pure-Rust [`super::rollout_basis_points_at`] for time-based strategies.

use super::{
    GradualRolloutConfig, RolloutStrategy, rollout_basis_points_at, validate_gradual_rollout,
};
use crate::tokenization::jurisdiction_compliance_tag;
use crate::{ChainResult, ContractGenerator, GeneratedContract};

impl ContractGenerator {
    /// Emits the Solidity source for a gradual-rollout controller.
    pub(crate) fn generate_solidity_gradual_rollout(
        &self,
        config: &GradualRolloutConfig,
    ) -> ChainResult<GeneratedContract> {
        validate_gradual_rollout(config)?;
        let compliance_tag = jurisdiction_compliance_tag(config.jurisdiction);
        let time_based = matches!(
            config.strategy,
            RolloutStrategy::Linear | RolloutStrategy::Canary
        );
        let is_canary = config.strategy == RolloutStrategy::Canary;
        let is_manual = config.strategy == RolloutStrategy::Manual;

        let mut source = String::from("// SPDX-License-Identifier: MIT\n");
        source.push_str("pragma solidity ^0.8.20;\n\n");
        source.push_str("import \"@openzeppelin/contracts/access/Ownable2Step.sol\";\n\n");

        // -- NatSpec header ----------------------------------------------------
        source.push_str(&format!("/// @title {}\n", config.name));
        source.push_str(&format!(
            "/// @notice Gradual rollout controller ({}).\n",
            config.strategy.label()
        ));
        source.push_str(&format!(
            "/// @dev Compliance framework: {compliance_tag}. Generated by Legalis-Chain.\n"
        ));
        if time_based {
            source.push_str("/// @dev Worked schedule (basis points after activation):\n");
            for steps in 0u64..=3 {
                let elapsed = config.step_interval_seconds.saturating_mul(steps);
                let bps = rollout_basis_points_at(
                    config.start_basis_points,
                    config.step_basis_points,
                    config.target_basis_points,
                    config.step_interval_seconds,
                    elapsed,
                );
                source.push_str(&format!("/// @dev   - t = {elapsed}s: {bps} bps\n"));
            }
        }
        source.push_str("/// @dev Security Considerations:\n");
        source.push_str(
            "/// @dev  - currentBps is monotonic and capped at TARGET_BPS; it can never exceed 100%.\n",
        );
        if config.guardian_rollback {
            source.push_str(
                "/// @dev  - A guardian can roll the exposure back to zero instantly in an incident.\n",
            );
        }
        source.push_str("/// @dev Gas Notes:\n");
        source.push_str(
            "/// @dev  - isActiveFor is a single keccak hash plus comparison (no storage writes).\n\n",
        );

        // -- Contract declaration & constants ----------------------------------
        source.push_str(&format!("contract {} is Ownable2Step {{\n", config.name));
        source.push_str("    uint256 public constant BPS_DENOMINATOR = 10000;\n");
        source.push_str(&format!(
            "    uint256 public constant START_BPS = {};\n",
            config.start_basis_points
        ));
        source.push_str(&format!(
            "    uint256 public constant TARGET_BPS = {};\n",
            config.target_basis_points
        ));
        source.push_str(&format!(
            "    uint256 public constant STEP_BPS = {};\n",
            config.step_basis_points
        ));
        source.push_str(&format!(
            "    uint256 public constant STEP_INTERVAL = {} seconds;\n\n",
            config.step_interval_seconds
        ));

        // -- Storage -----------------------------------------------------------
        source.push_str("    /// @notice Activation timestamp (0 = not started).\n");
        source.push_str("    uint256 public startTime;\n");
        source.push_str("    bool public active;\n");
        if is_manual {
            source.push_str("    /// @notice Manually-controlled current share.\n");
            source.push_str("    uint256 public manualBps;\n");
        }
        if is_canary {
            source.push_str("    /// @notice Canary allowlist served regardless of percentage.\n");
            source.push_str("    mapping(address => bool) public allowlist;\n");
        }
        if config.guardian_rollback {
            source.push_str("    /// @notice Guardian permitted to roll the rollout back.\n");
            source.push_str("    address public immutable guardian;\n");
        }
        source.push('\n');

        // -- Events ------------------------------------------------------------
        source.push_str("    event RolloutActivated(uint256 startTime);\n");
        if is_manual {
            source.push_str("    event ManualBpsSet(uint256 bps);\n");
        }
        if is_canary {
            source.push_str("    event AllowlistSet(address indexed account, bool allowed);\n");
        }
        if config.guardian_rollback {
            source.push_str("    event RolledBack();\n");
        }
        source.push('\n');

        // -- Constructor -------------------------------------------------------
        if config.guardian_rollback {
            source.push_str("    constructor(address guardian_) Ownable(msg.sender) {\n");
            source.push_str(
                "        require(guardian_ != address(0), \"Rollout: zero guardian\");\n",
            );
            source.push_str("        guardian = guardian_;\n");
        } else {
            source.push_str("    constructor() Ownable(msg.sender) {\n");
        }
        if is_manual {
            source.push_str("        manualBps = START_BPS;\n");
        }
        source.push_str("    }\n\n");

        if config.guardian_rollback {
            source.push_str("    modifier onlyGuardian() {\n");
            source.push_str(
                "        require(msg.sender == guardian || msg.sender == owner(), \"Rollout: not guardian\");\n",
            );
            source.push_str("        _;\n");
            source.push_str("    }\n\n");
        }

        // -- Activation --------------------------------------------------------
        source.push_str("    /// @notice Begin the rollout schedule.\n");
        source.push_str("    function activate() external onlyOwner {\n");
        source.push_str("        require(startTime == 0, \"Rollout: already active\");\n");
        source.push_str("        startTime = block.timestamp;\n");
        source.push_str("        active = true;\n");
        source.push_str("        emit RolloutActivated(startTime);\n");
        source.push_str("    }\n\n");

        // -- Manual controls ---------------------------------------------------
        if is_manual {
            source.push_str(
                "    /// @notice Advance the manual share by one step (capped at target).\n",
            );
            source.push_str("    function advance() external onlyOwner {\n");
            source.push_str("        uint256 next = manualBps + STEP_BPS;\n");
            source.push_str("        manualBps = next > TARGET_BPS ? TARGET_BPS : next;\n");
            source.push_str("        emit ManualBpsSet(manualBps);\n");
            source.push_str("    }\n\n");
            source.push_str("    /// @notice Set the manual share directly (capped at target).\n");
            source.push_str("    function setBps(uint256 bps) external onlyOwner {\n");
            source.push_str("        require(bps <= TARGET_BPS, \"Rollout: above target\");\n");
            source.push_str("        manualBps = bps;\n");
            source.push_str("        emit ManualBpsSet(manualBps);\n");
            source.push_str("    }\n\n");
        }

        // -- Canary allowlist --------------------------------------------------
        if is_canary {
            source
                .push_str("    /// @notice Add or remove an address from the canary allowlist.\n");
            source.push_str(
                "    function setAllowlist(address account, bool allowed) external onlyOwner {\n",
            );
            source.push_str("        allowlist[account] = allowed;\n");
            source.push_str("        emit AllowlistSet(account, allowed);\n");
            source.push_str("    }\n\n");
        }

        // -- Rollback ----------------------------------------------------------
        if config.guardian_rollback {
            source.push_str("    /// @notice Roll the rollout back to zero exposure.\n");
            source.push_str("    function rollback() external onlyGuardian {\n");
            source.push_str("        active = false;\n");
            source.push_str("        startTime = 0;\n");
            if is_manual {
                source.push_str("        manualBps = START_BPS;\n");
            }
            source.push_str("        emit RolledBack();\n");
            source.push_str("    }\n\n");
        }

        // -- currentBps --------------------------------------------------------
        source.push_str("    /// @notice Current rollout share in basis points.\n");
        source.push_str("    function currentBps() public view returns (uint256) {\n");
        source.push_str("        if (!active) {\n");
        source.push_str("            return 0;\n");
        source.push_str("        }\n");
        if is_manual {
            source.push_str("        return manualBps;\n");
        } else {
            source.push_str("        if (STEP_INTERVAL == 0) {\n");
            source.push_str("            return TARGET_BPS;\n");
            source.push_str("        }\n");
            source.push_str(
                "        uint256 steps = (block.timestamp - startTime) / STEP_INTERVAL;\n",
            );
            source.push_str("        uint256 value = START_BPS + steps * STEP_BPS;\n");
            source.push_str("        return value > TARGET_BPS ? TARGET_BPS : value;\n");
        }
        source.push_str("    }\n\n");

        // -- Bucket + predicate ------------------------------------------------
        source.push_str("    /// @notice Stable bucket in [0, 10000) for a user.\n");
        source.push_str("    function bucketOf(address user) public view returns (uint256) {\n");
        source.push_str(
            "        return uint256(keccak256(abi.encodePacked(address(this), user))) % BPS_DENOMINATOR;\n",
        );
        source.push_str("    }\n\n");
        source.push_str("    /// @notice Whether the rolled-out feature is live for a user.\n");
        source.push_str("    function isActiveFor(address user) public view returns (bool) {\n");
        if is_canary {
            source.push_str("        if (allowlist[user]) {\n");
            source.push_str("            return true;\n");
            source.push_str("        }\n");
        }
        source.push_str("        if (!active) {\n");
        source.push_str("            return false;\n");
        source.push_str("        }\n");
        source.push_str("        return bucketOf(user) < currentBps();\n");
        source.push_str("    }\n");

        source.push_str("}\n");

        Ok(GeneratedContract {
            name: config.name.clone(),
            source,
            platform: self.platform,
            abi: None,
            deployment_script: None,
        })
    }
}
