//! On-chain upgrade-governance generator (Solidity / EVM).
//!
//! Part of the `evolution` module. Distinct from the general-purpose DAO governor
//! generator: every proposal here carries a candidate implementation address and
//! the only execution path is a timelocked proxy upgrade.

use super::{ProxyKind, UpgradeGovernanceConfig, validate_upgrade_governance};
use crate::tokenization::jurisdiction_compliance_tag;
use crate::{ChainResult, ContractGenerator, GeneratedContract};

impl ContractGenerator {
    /// Emits the Solidity source for a token-weighted upgrade governor.
    pub(crate) fn generate_solidity_upgrade_governance(
        &self,
        config: &UpgradeGovernanceConfig,
    ) -> ChainResult<GeneratedContract> {
        validate_upgrade_governance(config)?;
        let compliance_tag = jurisdiction_compliance_tag(config.jurisdiction);
        let is_transparent = config.proxy_kind == ProxyKind::Transparent;

        let mut source = String::from("// SPDX-License-Identifier: MIT\n");
        source.push_str("pragma solidity ^0.8.20;\n\n");
        source.push_str("import \"@openzeppelin/contracts/governance/utils/IVotes.sol\";\n");
        source.push_str("import \"@openzeppelin/contracts/utils/ReentrancyGuard.sol\";\n\n");

        // -- Upgrade interface -------------------------------------------------
        if is_transparent {
            source.push_str("/// @notice Minimal ProxyAdmin interface (transparent proxies).\n");
            source.push_str("interface IProxyAdmin {\n");
            source.push_str(
                "    function upgradeAndCall(address proxy, address implementation, bytes calldata data) external payable;\n",
            );
            source.push_str("}\n\n");
        } else {
            source.push_str("/// @notice Minimal UUPS proxy interface (EIP-1822).\n");
            source.push_str("interface IUUPSProxy {\n");
            source.push_str(
                "    function upgradeToAndCall(address newImplementation, bytes calldata data) external payable;\n",
            );
            source.push_str("}\n\n");
        }

        // -- NatSpec header ----------------------------------------------------
        source.push_str(&format!("/// @title {}\n", config.name));
        source.push_str(&format!(
            "/// @notice Token-weighted governor whose sole power is to upgrade proxy {} ({}).\n",
            config.proxy,
            config.proxy_kind.label()
        ));
        source.push_str(&format!(
            "/// @dev Compliance framework: {compliance_tag}. Generated by Legalis-Chain.\n"
        ));
        source.push_str("/// @dev Security Considerations:\n");
        source.push_str(
            "/// @dev  - Voting weight is read from an immutable IVotes snapshot at voteStart,\n",
        );
        source.push_str(
            "/// @dev    so flash-loaned or post-proposal tokens cannot sway an upgrade.\n",
        );
        source.push_str(
            "/// @dev  - A passed proposal must clear quorum AND a timelock before execution,\n",
        );
        source.push_str("/// @dev    giving users a window to exit before code changes.\n");
        source.push_str(
            "/// @dev  - executeUpgrade follows CEI (executed=true before the external call) and\n",
        );
        source.push_str("/// @dev    is nonReentrant.\n");
        source.push_str("/// @dev Gas Notes:\n");
        source.push_str(
            "/// @dev  - Vote tallies are O(1) per voter; no iteration over the holder set.\n",
        );
        source.push_str(
            "/// @dev  - Proposal state is derived from block/timestamp comparisons, not stored.\n\n",
        );

        // -- Contract declaration & constants ----------------------------------
        source.push_str(&format!("contract {} is ReentrancyGuard {{\n", config.name));
        source.push_str(&format!(
            "    IVotes public immutable governanceToken = IVotes({});\n",
            config.governance_token
        ));
        source.push_str(&format!(
            "    /// @notice Proxy this governor is authorised to upgrade.\n    address public constant TARGET_PROXY = {};\n",
            config.proxy
        ));
        source.push_str(&format!(
            "    /// @notice Blocks between proposal creation and voting start.\n    uint256 public constant VOTING_DELAY = {};\n",
            config.voting_delay_blocks
        ));
        source.push_str(&format!(
            "    /// @notice Voting window length, in blocks.\n    uint256 public constant VOTING_PERIOD = {};\n",
            config.voting_period_blocks
        ));
        source.push_str(&format!(
            "    /// @notice Snapshot votes required to create a proposal.\n    uint256 public constant PROPOSAL_THRESHOLD = {};\n",
            config.proposal_threshold
        ));
        source.push_str(&format!(
            "    /// @notice Quorum as a fraction of snapshot supply (basis points).\n    uint256 public constant QUORUM_BPS = {};\n",
            config.quorum_basis_points
        ));
        source.push_str(&format!(
            "    /// @notice Delay between queueing and executing an upgrade, in seconds.\n    uint256 public constant TIMELOCK_DELAY = {};\n",
            config.timelock_delay_seconds
        ));
        source.push_str("    uint256 public constant BPS_DENOMINATOR = 10000;\n\n");

        if is_transparent {
            source.push_str(
                "    /// @notice ProxyAdmin that owns the transparent proxy (set at deployment).\n",
            );
            source.push_str("    IProxyAdmin public immutable proxyAdmin;\n\n");
        }

        // -- Types & storage ---------------------------------------------------
        source.push_str(
            "    enum ProposalState { Pending, Active, Defeated, Succeeded, Queued, Executed, Canceled }\n\n",
        );
        source.push_str("    struct UpgradeProposal {\n");
        source.push_str("        address proposer;\n");
        source.push_str("        address newImplementation;\n");
        source.push_str("        bytes initCalldata;\n");
        source.push_str("        uint256 voteStart;     // block number\n");
        source.push_str("        uint256 voteEnd;       // block number\n");
        source.push_str(
            "        uint256 snapshotBlock; // block for getPastVotes/getPastTotalSupply\n",
        );
        source.push_str("        uint256 forVotes;\n");
        source.push_str("        uint256 againstVotes;\n");
        source.push_str("        uint256 abstainVotes;\n");
        source.push_str("        uint256 eta;           // timestamp execution becomes possible\n");
        source.push_str("        bool executed;\n");
        source.push_str("        bool canceled;\n");
        source.push_str("    }\n\n");
        source.push_str("    uint256 public proposalCount;\n");
        source.push_str("    mapping(uint256 => UpgradeProposal) public proposals;\n");
        source.push_str("    mapping(uint256 => mapping(address => bool)) public hasVoted;\n\n");

        // -- Events ------------------------------------------------------------
        source.push_str(
            "    event UpgradeProposed(uint256 indexed id, address indexed proposer, address newImplementation);\n",
        );
        source.push_str(
            "    event VoteCast(uint256 indexed id, address indexed voter, uint8 support, uint256 weight);\n",
        );
        source.push_str("    event ProposalQueued(uint256 indexed id, uint256 eta);\n");
        source.push_str(
            "    event UpgradeExecuted(uint256 indexed id, address newImplementation);\n",
        );
        source.push_str("    event ProposalCanceled(uint256 indexed id);\n\n");

        // -- Constructor -------------------------------------------------------
        if is_transparent {
            source.push_str("    constructor(address proxyAdmin_) {\n");
            source.push_str("        require(proxyAdmin_ != address(0), \"Gov: zero admin\");\n");
            source.push_str("        proxyAdmin = IProxyAdmin(proxyAdmin_);\n");
            source.push_str("    }\n\n");
        }

        self.push_upgrade_lifecycle(&mut source);
        self.push_upgrade_execution(&mut source, is_transparent);

        source.push_str("}\n");

        Ok(GeneratedContract {
            name: config.name.clone(),
            source,
            platform: self.platform,
            abi: None,
            deployment_script: None,
        })
    }

    /// Appends proposal creation, voting, quorum and state-machine logic.
    fn push_upgrade_lifecycle(&self, source: &mut String) {
        // proposeUpgrade
        source.push_str("    /// @notice Create a proposal to upgrade TARGET_PROXY.\n");
        source.push_str(
            "    function proposeUpgrade(address newImplementation, bytes calldata initCalldata) external returns (uint256) {\n",
        );
        source.push_str(
            "        require(newImplementation != address(0), \"Gov: zero implementation\");\n",
        );
        source.push_str(
            "        require(governanceToken.getPastVotes(msg.sender, block.number - 1) >= PROPOSAL_THRESHOLD, \"Gov: below threshold\");\n",
        );
        source.push_str("        proposalCount += 1;\n");
        source.push_str("        uint256 id = proposalCount;\n");
        source.push_str("        UpgradeProposal storage p = proposals[id];\n");
        source.push_str("        p.proposer = msg.sender;\n");
        source.push_str("        p.newImplementation = newImplementation;\n");
        source.push_str("        p.initCalldata = initCalldata;\n");
        source.push_str("        p.voteStart = block.number + VOTING_DELAY;\n");
        source.push_str("        p.voteEnd = p.voteStart + VOTING_PERIOD;\n");
        source.push_str("        p.snapshotBlock = p.voteStart;\n");
        source.push_str("        emit UpgradeProposed(id, msg.sender, newImplementation);\n");
        source.push_str("        return id;\n");
        source.push_str("    }\n\n");

        // castVote
        source.push_str("    /// @notice Cast a vote (0=against, 1=for, 2=abstain).\n");
        source.push_str("    function castVote(uint256 id, uint8 support) external {\n");
        source.push_str(
            "        require(state(id) == ProposalState.Active, \"Gov: voting closed\");\n",
        );
        source.push_str("        require(support <= 2, \"Gov: invalid support\");\n");
        source.push_str("        require(!hasVoted[id][msg.sender], \"Gov: already voted\");\n");
        source.push_str("        UpgradeProposal storage p = proposals[id];\n");
        source.push_str(
            "        uint256 weight = governanceToken.getPastVotes(msg.sender, p.snapshotBlock);\n",
        );
        source.push_str("        require(weight > 0, \"Gov: no voting weight\");\n");
        source.push_str("        hasVoted[id][msg.sender] = true;\n");
        source.push_str("        if (support == 1) {\n");
        source.push_str("            p.forVotes += weight;\n");
        source.push_str("        } else if (support == 0) {\n");
        source.push_str("            p.againstVotes += weight;\n");
        source.push_str("        } else {\n");
        source.push_str("            p.abstainVotes += weight;\n");
        source.push_str("        }\n");
        source.push_str("        emit VoteCast(id, msg.sender, support, weight);\n");
        source.push_str("    }\n\n");

        // quorum view
        source.push_str("    /// @notice Quorum (in votes) required for a proposal to pass.\n");
        source.push_str("    function quorum(uint256 id) public view returns (uint256) {\n");
        source.push_str(
            "        uint256 supply = governanceToken.getPastTotalSupply(proposals[id].snapshotBlock);\n",
        );
        source.push_str("        return (supply * QUORUM_BPS) / BPS_DENOMINATOR;\n");
        source.push_str("    }\n\n");

        // state machine
        source.push_str("    /// @notice Current lifecycle state of a proposal.\n");
        source.push_str("    function state(uint256 id) public view returns (ProposalState) {\n");
        source.push_str("        UpgradeProposal storage p = proposals[id];\n");
        source.push_str("        require(p.voteStart != 0, \"Gov: unknown proposal\");\n");
        source.push_str("        if (p.canceled) {\n");
        source.push_str("            return ProposalState.Canceled;\n");
        source.push_str("        }\n");
        source.push_str("        if (p.executed) {\n");
        source.push_str("            return ProposalState.Executed;\n");
        source.push_str("        }\n");
        source.push_str("        if (block.number < p.voteStart) {\n");
        source.push_str("            return ProposalState.Pending;\n");
        source.push_str("        }\n");
        source.push_str("        if (block.number <= p.voteEnd) {\n");
        source.push_str("            return ProposalState.Active;\n");
        source.push_str("        }\n");
        source.push_str(
            "        if (p.forVotes <= p.againstVotes || (p.forVotes + p.abstainVotes) < quorum(id)) {\n",
        );
        source.push_str("            return ProposalState.Defeated;\n");
        source.push_str("        }\n");
        source.push_str("        if (p.eta == 0) {\n");
        source.push_str("            return ProposalState.Succeeded;\n");
        source.push_str("        }\n");
        source.push_str("        return ProposalState.Queued;\n");
        source.push_str("    }\n\n");

        // cancel (proposer only, before execution)
        source.push_str("    /// @notice Proposer may cancel before execution.\n");
        source.push_str("    function cancel(uint256 id) external {\n");
        source.push_str("        UpgradeProposal storage p = proposals[id];\n");
        source.push_str("        require(msg.sender == p.proposer, \"Gov: not proposer\");\n");
        source.push_str("        require(!p.executed, \"Gov: already executed\");\n");
        source.push_str("        p.canceled = true;\n");
        source.push_str("        emit ProposalCanceled(id);\n");
        source.push_str("    }\n\n");
    }

    /// Appends the timelock queue and the proxy-upgrade execution path.
    fn push_upgrade_execution(&self, source: &mut String, is_transparent: bool) {
        source.push_str("    /// @notice Queue a passed proposal behind the timelock.\n");
        source.push_str("    function queue(uint256 id) external {\n");
        source.push_str(
            "        require(state(id) == ProposalState.Succeeded, \"Gov: not succeeded\");\n",
        );
        source.push_str("        UpgradeProposal storage p = proposals[id];\n");
        source.push_str("        p.eta = block.timestamp + TIMELOCK_DELAY;\n");
        source.push_str("        emit ProposalQueued(id, p.eta);\n");
        source.push_str("    }\n\n");

        source.push_str("    /// @notice Execute the upgrade once the timelock has elapsed.\n");
        source.push_str("    function executeUpgrade(uint256 id) external nonReentrant {\n");
        source
            .push_str("        require(state(id) == ProposalState.Queued, \"Gov: not queued\");\n");
        source.push_str("        UpgradeProposal storage p = proposals[id];\n");
        source.push_str("        require(block.timestamp >= p.eta, \"Gov: timelock active\");\n");
        source.push_str("        p.executed = true; // CEI: effects before interaction\n");
        source.push_str("        emit UpgradeExecuted(id, p.newImplementation);\n");
        if is_transparent {
            source.push_str(
                "        proxyAdmin.upgradeAndCall(TARGET_PROXY, p.newImplementation, p.initCalldata);\n",
            );
        } else {
            source.push_str(
                "        IUUPSProxy(TARGET_PROXY).upgradeToAndCall(p.newImplementation, p.initCalldata);\n",
            );
        }
        source.push_str("    }\n");
    }
}
