# coding: utf-8

"""
    Legalis API

    REST API for the Legalis-RS legal framework. Provides CRUD operations for statutes, verification, and simulation endpoints.

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "legalis-api-client"
VERSION = "0.2.0"
PYTHON_REQUIRES = ">= 3.9"
REQUIRES = [
    "urllib3 >= 2.1.0, < 3.0.0",
    "python-dateutil >= 2.8.2",
    "pydantic >= 2",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="Legalis API",
    author="Legalis-RS Project",
    author_email="team@openapitools.org",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "Legalis API"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    license="MIT OR Apache-2.0",
    long_description_content_type='text/markdown',
    long_description="""\
    REST API for the Legalis-RS legal framework. Provides CRUD operations for statutes, verification, and simulation endpoints.
    """,  # noqa: E501
    package_data={"legalis_client": ["py.typed"]},
)