//! Automatic-optimization (feedback controller) generator (Solidity / EVM).
//!
//! Part of the `autonomous` module. The on-chain `_adjust` routine mirrors the
//! pure-Rust [`super::adjust_parameter`] step controller exactly, so off-chain
//! tooling can predict every parameter move the contract will make.
//!
//! Distinct from the crate's *compile-time* gas-optimization hints: this contract
//! makes the optimization decision itself, at runtime, bounded by `[min, max]` and
//! a per-step ceiling — the metric is supplied by a trusted reporter while the
//! *adjustment* is fully autonomous.

use super::{AutoOptimizerConfig, ControlSense, validate_auto_optimizer};
use crate::tokenization::jurisdiction_compliance_tag;
use crate::{ChainResult, ContractGenerator, GeneratedContract};

impl ContractGenerator {
    /// Emits the Solidity source for an automatic-optimization controller.
    pub(crate) fn generate_solidity_auto_optimizer(
        &self,
        config: &AutoOptimizerConfig,
    ) -> ChainResult<GeneratedContract> {
        validate_auto_optimizer(config)?;
        let compliance_tag = jurisdiction_compliance_tag(config.jurisdiction);

        let mut source = String::from("// SPDX-License-Identifier: MIT\n");
        source.push_str("pragma solidity ^0.8.20;\n\n");
        source.push_str("import \"@openzeppelin/contracts/access/Ownable2Step.sol\";\n\n");

        // -- NatSpec header ----------------------------------------------------
        source.push_str(&format!("/// @title {}\n", config.name));
        source.push_str(&format!(
            "/// @notice Autonomous feedback controller tuning '{}' toward a '{}' set-point.\n",
            config.parameter_label, config.metric_label
        ));
        source.push_str(&format!(
            "/// @dev Compliance framework: {compliance_tag}. Generated by Legalis-Chain.\n"
        ));
        source.push_str(&format!(
            "/// @dev Control sense: {}.\n",
            config.sense.label()
        ));
        source.push_str("/// @dev Security Considerations:\n");
        source.push_str(
            "/// @dev  - The parameter is bounded by [MIN_VALUE, MAX_VALUE] and moves by at most\n",
        );
        source.push_str(
            "/// @dev    STEP per COOLDOWN, so a bad metric cannot swing it arbitrarily.\n",
        );
        source.push_str(
            "/// @dev  - The driving metric must come from a trusted reporter/oracle (setReporter).\n",
        );
        source.push_str("/// @dev Gas Notes:\n");
        source.push_str(
            "/// @dev  - _adjust is pure and branch-only; observe writes at most two slots.\n\n",
        );

        // -- Contract declaration & constants ----------------------------------
        source.push_str(&format!("contract {} is Ownable2Step {{\n", config.name));
        source.push_str(&format!(
            "    uint256 public constant MIN_VALUE = {};\n",
            config.min_value
        ));
        source.push_str(&format!(
            "    uint256 public constant MAX_VALUE = {};\n",
            config.max_value
        ));
        source.push_str(&format!(
            "    uint256 public constant TARGET = {};\n",
            config.target_value
        ));
        source.push_str(&format!(
            "    uint256 public constant STEP = {};\n",
            config.step_value
        ));
        source.push_str(&format!(
            "    uint256 public constant COOLDOWN = {} seconds;\n\n",
            config.cooldown_seconds
        ));

        // -- Storage -----------------------------------------------------------
        source.push_str("    uint256 public value;\n");
        source.push_str("    uint256 public lastAdjusted;\n");
        source.push_str("    address public reporter;\n\n");

        // -- Events ------------------------------------------------------------
        source.push_str(
            "    event Adjusted(uint256 observed, uint256 oldValue, uint256 newValue);\n",
        );
        source.push_str("    event ReporterSet(address indexed reporter);\n\n");

        // -- Modifier ----------------------------------------------------------
        source.push_str("    modifier onlyReporter() {\n");
        source.push_str(
            "        require(msg.sender == reporter || msg.sender == owner(), \"Opt: not reporter\");\n",
        );
        source.push_str("        _;\n");
        source.push_str("    }\n\n");

        // -- Constructor -------------------------------------------------------
        source.push_str("    constructor() Ownable(msg.sender) {\n");
        source.push_str(&format!("        value = {};\n", config.initial_value));
        source.push_str("        lastAdjusted = block.timestamp;\n");
        source.push_str("    }\n\n");

        // -- Admin -------------------------------------------------------------
        source.push_str("    /// @notice Set the trusted reporter that may submit metrics.\n");
        source.push_str("    function setReporter(address newReporter) external onlyOwner {\n");
        source.push_str("        reporter = newReporter;\n");
        source.push_str("        emit ReporterSet(newReporter);\n");
        source.push_str("    }\n\n");

        // -- Observe / adjust --------------------------------------------------
        source.push_str(
            "    /// @notice Submit the latest metric; the controller steps the parameter autonomously.\n",
        );
        source.push_str(
            "    function observe(uint256 metric) external onlyReporter returns (uint256) {\n",
        );
        source.push_str(
            "        require(block.timestamp >= lastAdjusted + COOLDOWN, \"Opt: cooldown active\");\n",
        );
        source.push_str("        uint256 prev = value;\n");
        source.push_str("        uint256 next = _adjust(prev, metric);\n");
        source.push_str("        if (next != prev) {\n");
        source.push_str("            value = next; // CEI: effect before event\n");
        source.push_str("            lastAdjusted = block.timestamp;\n");
        source.push_str("            emit Adjusted(metric, prev, next);\n");
        source.push_str("        }\n");
        source.push_str("        return next;\n");
        source.push_str("    }\n\n");

        source.push_str(
            "    /// @notice Preview the next value for a metric without mutating state.\n",
        );
        source.push_str(
            "    function previewAdjust(uint256 metric) external view returns (uint256) {\n",
        );
        source.push_str("        return _adjust(value, metric);\n");
        source.push_str("    }\n\n");

        self.push_optimizer_adjust(&mut source, config.sense);

        source.push_str("}\n");

        Ok(GeneratedContract {
            name: config.name.clone(),
            source,
            platform: self.platform,
            abi: None,
            deployment_script: None,
        })
    }

    /// Appends the pure `_adjust` controller step, specialised by control sense.
    fn push_optimizer_adjust(&self, source: &mut String, sense: ControlSense) {
        // The raise/lower branches swap with the control sense; both saturate the
        // decrement at zero and clamp the result into [MIN_VALUE, MAX_VALUE].
        let (on_above, on_below) = match sense {
            ControlSense::Direct => (
                "            next = current + STEP;\n",
                "            next = current >= STEP ? current - STEP : 0;\n",
            ),
            ControlSense::Inverse => (
                "            next = current >= STEP ? current - STEP : 0;\n",
                "            next = current + STEP;\n",
            ),
        };
        source.push_str(
            "    /// @dev Pure controller step mirrored off-chain by adjust_parameter.\n",
        );
        source.push_str(
            "    function _adjust(uint256 current, uint256 observed) internal pure returns (uint256) {\n",
        );
        source.push_str("        uint256 next = current;\n");
        source.push_str("        if (observed > TARGET) {\n");
        source.push_str(on_above);
        source.push_str("        } else if (observed < TARGET) {\n");
        source.push_str(on_below);
        source.push_str("        }\n");
        source.push_str("        if (next < MIN_VALUE) {\n");
        source.push_str("            next = MIN_VALUE;\n");
        source.push_str("        }\n");
        source.push_str("        if (next > MAX_VALUE) {\n");
        source.push_str("            next = MAX_VALUE;\n");
        source.push_str("        }\n");
        source.push_str("        return next;\n");
        source.push_str("    }\n");
    }
}
