//! Cost-optimization generator (Solidity / EVM).
//!
//! Part of the `autonomous` module. The on-chain `estimateSavings` mirrors the
//! pure-Rust [`super::batch_savings`] and the optional `_shouldDefer` guard mirrors
//! [`super::should_defer`].
//!
//! Distinct from the crate's *compile-time* gas-optimization comments/hints: this
//! contract reduces cost at runtime by amortising the base transaction cost across
//! a batch, harvesting storage refunds, and deferring non-urgent work while gas is
//! expensive.

use super::{CostOptimizerConfig, validate_cost_optimizer};
use crate::tokenization::jurisdiction_compliance_tag;
use crate::{ChainResult, ContractGenerator, GeneratedContract};

impl ContractGenerator {
    /// Emits the Solidity source for a cost-optimization batch executor.
    pub(crate) fn generate_solidity_cost_optimizer(
        &self,
        config: &CostOptimizerConfig,
    ) -> ChainResult<GeneratedContract> {
        validate_cost_optimizer(config)?;
        let compliance_tag = jurisdiction_compliance_tag(config.jurisdiction);
        let has_guard = config.basefee_ceiling_wei > 0;
        let has_refunds = config.enable_refunds;

        let mut source = String::from("// SPDX-License-Identifier: MIT\n");
        source.push_str("pragma solidity ^0.8.20;\n\n");
        source.push_str("import \"@openzeppelin/contracts/access/Ownable2Step.sol\";\n");
        source.push_str("import \"@openzeppelin/contracts/utils/ReentrancyGuard.sol\";\n\n");

        // -- NatSpec header ----------------------------------------------------
        source.push_str(&format!("/// @title {}\n", config.name));
        source.push_str(
            "/// @notice Cost-optimizing batch executor (amortised base gas + storage refunds).\n",
        );
        source.push_str(&format!(
            "/// @dev Compliance framework: {compliance_tag}. Generated by Legalis-Chain.\n"
        ));
        source.push_str("/// @dev Security Considerations:\n");
        source.push_str(
            "/// @dev  - executeBatch is owner-only and nonReentrant; each subcall is checked.\n",
        );
        if has_guard {
            source.push_str(
                "/// @dev  - Non-urgent batches revert when block.basefee exceeds BASEFEE_CEILING.\n",
            );
        }
        if has_refunds {
            source.push_str(
                "/// @dev  - clearSlots harvests storage gas refunds by zeroing spent scratch slots.\n",
            );
        }
        source.push_str("/// @dev Gas Notes:\n");
        source.push_str(&format!(
            "/// @dev  - Batching up to {} calls amortises BASE_TX_GAS across the batch.\n\n",
            config.max_batch_size
        ));

        // -- Contract declaration & constants ----------------------------------
        source.push_str(&format!(
            "contract {} is Ownable2Step, ReentrancyGuard {{\n",
            config.name
        ));
        source.push_str(&format!(
            "    uint256 public constant MAX_BATCH_SIZE = {};\n",
            config.max_batch_size
        ));
        source.push_str(&format!(
            "    uint256 public constant BASE_TX_GAS = {};\n",
            config.base_tx_gas
        ));
        if has_guard {
            source.push_str(&format!(
                "    uint256 public constant BASEFEE_CEILING = {} wei;\n",
                config.basefee_ceiling_wei
            ));
        }
        source.push('\n');

        // -- Types & storage ---------------------------------------------------
        source.push_str("    struct Call {\n");
        source.push_str("        address target;\n");
        source.push_str("        uint256 value;\n");
        source.push_str("        bytes data;\n");
        source.push_str("    }\n");
        if has_refunds {
            source.push_str("    mapping(bytes32 => uint256) public scratch;\n");
        }
        source.push('\n');

        // -- Events ------------------------------------------------------------
        source.push_str("    event BatchExecuted(uint256 count, uint256 estimatedGasSaved);\n");
        if has_guard {
            source.push_str("    event Deferred(uint256 basefee);\n");
        }
        if has_refunds {
            source.push_str("    event SlotCleared(bytes32 indexed slot);\n");
        }
        source.push('\n');

        // -- Constructor -------------------------------------------------------
        source.push_str("    constructor() Ownable(msg.sender) {}\n\n");

        self.push_cost_execute(&mut source, has_guard);
        self.push_cost_helpers(&mut source, has_guard, has_refunds);

        source.push_str("}\n");

        Ok(GeneratedContract {
            name: config.name.clone(),
            source,
            platform: self.platform,
            abi: None,
            deployment_script: None,
        })
    }

    /// Appends the batched execution entry point.
    fn push_cost_execute(&self, source: &mut String, has_guard: bool) {
        source.push_str(
            "    /// @notice Execute many calls in one transaction, amortising base gas.\n",
        );
        if has_guard {
            source.push_str("    function executeBatch(Call[] calldata calls, bool urgent)\n");
        } else {
            source.push_str("    function executeBatch(Call[] calldata calls)\n");
        }
        source.push_str("        external\n");
        source.push_str("        payable\n");
        source.push_str("        onlyOwner\n");
        source.push_str("        nonReentrant\n");
        source.push_str("        returns (bytes[] memory results)\n");
        source.push_str("    {\n");
        source.push_str(
            "        require(calls.length > 0 && calls.length <= MAX_BATCH_SIZE, \"Cost: bad batch size\");\n",
        );
        if has_guard {
            source.push_str("        if (!urgent && _shouldDefer()) {\n");
            source.push_str("            emit Deferred(block.basefee);\n");
            source.push_str("            revert(\"Cost: deferred, basefee too high\");\n");
            source.push_str("        }\n");
        }
        source.push_str("        results = new bytes[](calls.length);\n");
        source.push_str("        for (uint256 i = 0; i < calls.length; i++) {\n");
        source.push_str(
            "            (bool ok, bytes memory ret) = calls[i].target.call{value: calls[i].value}(calls[i].data);\n",
        );
        source.push_str("            require(ok, \"Cost: subcall reverted\");\n");
        source.push_str("            results[i] = ret;\n");
        source.push_str("        }\n");
        source
            .push_str("        emit BatchExecuted(calls.length, estimateSavings(calls.length));\n");
        source.push_str("    }\n\n");
    }

    /// Appends the savings estimate, base-fee guard and refund harvester.
    fn push_cost_helpers(&self, source: &mut String, has_guard: bool, has_refunds: bool) {
        source.push_str(
            "    /// @notice Gas saved by batching `numCalls` vs sending them separately.\n",
        );
        source.push_str("    /// @dev Mirrored off-chain by batch_savings.\n");
        source.push_str(
            "    function estimateSavings(uint256 numCalls) public pure returns (uint256) {\n",
        );
        source.push_str("        if (numCalls == 0) {\n");
        source.push_str("            return 0;\n");
        source.push_str("        }\n");
        source.push_str("        return (numCalls - 1) * BASE_TX_GAS;\n");
        source.push_str("    }\n");

        if has_guard {
            source.push('\n');
            source.push_str(
                "    /// @notice Whether a non-urgent batch should currently be deferred.\n",
            );
            source.push_str("    function shouldDefer() external view returns (bool) {\n");
            source.push_str("        return _shouldDefer();\n");
            source.push_str("    }\n\n");
            source.push_str("    /// @dev Mirrored off-chain by should_defer.\n");
            source.push_str("    function _shouldDefer() internal view returns (bool) {\n");
            source.push_str(
                "        return BASEFEE_CEILING != 0 && block.basefee > BASEFEE_CEILING;\n",
            );
            source.push_str("    }\n");
        }

        if has_refunds {
            source.push('\n');
            source.push_str("    /// @notice Set a scratch slot (counts toward later refunds).\n");
            source.push_str(
                "    function setScratch(bytes32 slot, uint256 value) external onlyOwner {\n",
            );
            source.push_str("        scratch[slot] = value;\n");
            source.push_str("    }\n\n");
            source.push_str(
                "    /// @notice Harvest storage refunds by zeroing spent scratch slots.\n",
            );
            source.push_str(
                "    function clearSlots(bytes32[] calldata slots) external onlyOwner {\n",
            );
            source.push_str("        uint256 len = slots.length;\n");
            source.push_str("        for (uint256 i = 0; i < len; i++) {\n");
            source.push_str("            if (scratch[slots[i]] != 0) {\n");
            source
                .push_str("                delete scratch[slots[i]]; // harvests SSTORE refund\n");
            source.push_str("                emit SlotCleared(slots[i]);\n");
            source.push_str("            }\n");
            source.push_str("        }\n");
            source.push_str("    }\n");
        }
    }
}
