//! Performance-monitoring generator (Solidity / EVM).
//!
//! Part of the `autonomous` module. The on-chain `_ema` routine mirrors the
//! pure-Rust [`super::ema_update`] and `healthScore` mirrors [`super::health_score`],
//! so off-chain dashboards agree with the contract's own aggregates.
//!
//! Distinct from the crate's domain-specific compliance/environmental monitors
//! (which watch *legal* state): this contract self-instruments its *operational*
//! gas via a `measured` modifier that records `gasleft()` deltas autonomously.

use super::{PerformanceMonitorConfig, operation_constant_name, validate_performance_monitor};
use crate::tokenization::jurisdiction_compliance_tag;
use crate::{ChainResult, ContractGenerator, GeneratedContract};

impl ContractGenerator {
    /// Emits the Solidity source for a performance monitor.
    pub(crate) fn generate_solidity_performance_monitor(
        &self,
        config: &PerformanceMonitorConfig,
    ) -> ChainResult<GeneratedContract> {
        validate_performance_monitor(config)?;
        let compliance_tag = jurisdiction_compliance_tag(config.jurisdiction);
        let operation_constants: Vec<(String, &String)> = config
            .operations
            .iter()
            .map(|op| (operation_constant_name(op), op))
            .collect();

        let mut source = String::from("// SPDX-License-Identifier: MIT\n");
        source.push_str("pragma solidity ^0.8.20;\n\n");
        source.push_str("import \"@openzeppelin/contracts/access/Ownable2Step.sol\";\n\n");

        // -- NatSpec header ----------------------------------------------------
        source.push_str(&format!("/// @title {}\n", config.name));
        source.push_str(&format!(
            "/// @notice On-chain performance monitor over {} operation(s).\n",
            config.operations.len()
        ));
        source.push_str(&format!(
            "/// @dev Compliance framework: {compliance_tag}. Generated by Legalis-Chain.\n"
        ));
        source.push_str("/// @dev Security Considerations:\n");
        source.push_str(
            "/// @dev  - The `measured` modifier self-instruments gas (gasleft deltas), so on-chain\n",
        );
        source.push_str(
            "/// @dev    metrics need no trusted feed; external samples via record() are reporter-gated.\n",
        );
        source.push_str("/// @dev Gas Notes:\n");
        source.push_str(&format!(
            "/// @dev  - EMA smoothing alpha = {} bps; record touches one Metric slot group.\n\n",
            config.ema_alpha_bps
        ));

        // -- Contract declaration & constants ----------------------------------
        source.push_str(&format!("contract {} is Ownable2Step {{\n", config.name));
        source.push_str("    uint256 public constant BPS_DENOMINATOR = 10000;\n");
        source.push_str(&format!(
            "    uint256 public constant EMA_ALPHA_BPS = {};\n",
            config.ema_alpha_bps
        ));
        if config.health_score {
            source.push_str(&format!(
                "    uint256 public constant GAS_BUDGET = {};\n",
                config.gas_budget_per_op
            ));
        }
        source.push('\n');
        source.push_str("    // Monitored operations.\n");
        for (constant, raw) in &operation_constants {
            source.push_str(&format!(
                "    bytes32 public constant {constant} = keccak256(bytes(\"{raw}\"));\n"
            ));
        }
        source.push('\n');

        // -- Types & storage ---------------------------------------------------
        source.push_str("    struct Metric {\n");
        source.push_str("        uint256 count;\n");
        source.push_str("        uint256 totalGas;\n");
        source.push_str("        uint256 emaGas;\n");
        source.push_str("        uint256 minGas;\n");
        source.push_str("        uint256 maxGas;\n");
        source.push_str("        bool known;\n");
        source.push_str("    }\n");
        source.push_str("    mapping(bytes32 => Metric) public metrics;\n");
        source.push_str("    address public reporter;\n\n");

        // -- Events ------------------------------------------------------------
        if config.emit_events {
            source.push_str(
                "    event Recorded(bytes32 indexed op, uint256 gasUsed, uint256 emaGas);\n",
            );
        }
        source.push_str("    event ReporterSet(address indexed reporter);\n\n");

        // -- Constructor -------------------------------------------------------
        source.push_str("    constructor() Ownable(msg.sender) {\n");
        for (constant, _) in &operation_constants {
            source.push_str(&format!("        metrics[{constant}].known = true;\n"));
        }
        source.push_str("    }\n\n");

        // -- Admin -------------------------------------------------------------
        source.push_str(
            "    /// @notice Set the trusted reporter for externally-measured samples.\n",
        );
        source.push_str("    function setReporter(address newReporter) external onlyOwner {\n");
        source.push_str("        reporter = newReporter;\n");
        source.push_str("        emit ReporterSet(newReporter);\n");
        source.push_str("    }\n\n");

        self.push_monitor_record(&mut source, config.emit_events);
        self.push_monitor_views(&mut source, config.health_score);

        source.push_str("}\n");

        Ok(GeneratedContract {
            name: config.name.clone(),
            source,
            platform: self.platform,
            abi: None,
            deployment_script: None,
        })
    }

    /// Appends the self-instrumenting modifier, the record entry points and `_ema`.
    fn push_monitor_record(&self, source: &mut String, emit_events: bool) {
        source.push_str("    modifier onlyReporter() {\n");
        source.push_str(
            "        require(msg.sender == reporter || msg.sender == owner(), \"Mon: not reporter\");\n",
        );
        source.push_str("        _;\n");
        source.push_str("    }\n\n");

        source.push_str("    /// @notice Self-instrument an operation's gas autonomously.\n");
        source.push_str("    modifier measured(bytes32 op) {\n");
        source.push_str("        uint256 gasStart = gasleft();\n");
        source.push_str("        _;\n");
        source.push_str("        _record(op, gasStart - gasleft());\n");
        source.push_str("    }\n\n");

        source.push_str(
            "    /// @notice Submit an externally-measured gas sample for an operation.\n",
        );
        source
            .push_str("    function record(bytes32 op, uint256 gasUsed) external onlyReporter {\n");
        source.push_str("        _record(op, gasUsed);\n");
        source.push_str("    }\n\n");

        source.push_str("    function _record(bytes32 op, uint256 gasUsed) internal {\n");
        source.push_str("        Metric storage m = metrics[op];\n");
        source.push_str("        require(m.known, \"Mon: unknown op\");\n");
        source.push_str("        m.count += 1;\n");
        source.push_str("        m.totalGas += gasUsed;\n");
        source.push_str("        if (m.count == 1) {\n");
        source.push_str("            m.emaGas = gasUsed;\n");
        source.push_str("            m.minGas = gasUsed;\n");
        source.push_str("            m.maxGas = gasUsed;\n");
        source.push_str("        } else {\n");
        source.push_str("            m.emaGas = _ema(m.emaGas, gasUsed);\n");
        source.push_str("            if (gasUsed < m.minGas) {\n");
        source.push_str("                m.minGas = gasUsed;\n");
        source.push_str("            }\n");
        source.push_str("            if (gasUsed > m.maxGas) {\n");
        source.push_str("                m.maxGas = gasUsed;\n");
        source.push_str("            }\n");
        source.push_str("        }\n");
        if emit_events {
            source.push_str("        emit Recorded(op, gasUsed, m.emaGas);\n");
        }
        source.push_str("    }\n\n");

        source.push_str("    /// @dev Pure EMA step mirrored off-chain by ema_update.\n");
        source.push_str(
            "    function _ema(uint256 prev, uint256 sample) internal pure returns (uint256) {\n",
        );
        source.push_str(
            "        return (EMA_ALPHA_BPS * sample + (BPS_DENOMINATOR - EMA_ALPHA_BPS) * prev) / BPS_DENOMINATOR;\n",
        );
        source.push_str("    }\n\n");
    }

    /// Appends the read-only metric views (and optional health score).
    fn push_monitor_views(&self, source: &mut String, health_score: bool) {
        source.push_str(
            "    /// @notice Arithmetic mean gas for an operation (0 if never sampled).\n",
        );
        source.push_str("    function averageGas(bytes32 op) external view returns (uint256) {\n");
        source.push_str("        Metric memory m = metrics[op];\n");
        source.push_str("        if (m.count == 0) {\n");
        source.push_str("            return 0;\n");
        source.push_str("        }\n");
        source.push_str("        return m.totalGas / m.count;\n");
        source.push_str("    }\n");
        if health_score {
            source.push('\n');
            source.push_str(
                "    /// @notice 0..10000 health score from the EMA gas vs GAS_BUDGET.\n",
            );
            source.push_str("    /// @dev Mirrored off-chain by health_score.\n");
            source.push_str(
                "    function healthScore(bytes32 op) external view returns (uint256) {\n",
            );
            source.push_str("        uint256 ema = metrics[op].emaGas;\n");
            source.push_str("        if (ema == 0 || GAS_BUDGET >= ema) {\n");
            source.push_str("            return BPS_DENOMINATOR;\n");
            source.push_str("        }\n");
            source.push_str("        return GAS_BUDGET * BPS_DENOMINATOR / ema;\n");
            source.push_str("    }\n");
        }
    }
}
