//! Resource-management (rate-limit + budget) generator (Solidity / EVM).
//!
//! Part of the `autonomous` module. The on-chain refill math mirrors the pure-Rust
//! [`super::token_bucket_available`], the budget window mirrors [`super::epoch_index`],
//! and the affordability check mirrors [`super::can_consume`] — so off-chain tooling
//! can predict exactly when a caller will be throttled.

use super::{ResourceManagerConfig, validate_resource_manager};
use crate::tokenization::jurisdiction_compliance_tag;
use crate::{ChainResult, ContractGenerator, GeneratedContract};

impl ContractGenerator {
    /// Emits the Solidity source for a token-bucket resource manager.
    pub(crate) fn generate_solidity_resource_manager(
        &self,
        config: &ResourceManagerConfig,
    ) -> ChainResult<GeneratedContract> {
        validate_resource_manager(config)?;
        let compliance_tag = jurisdiction_compliance_tag(config.jurisdiction);
        let has_budget = config.epoch_budget > 0 && config.epoch_seconds > 0;
        let per_caller = config.per_caller;
        let bucket_ref = if per_caller {
            "_buckets[caller]"
        } else {
            "_global"
        };

        let mut source = String::from("// SPDX-License-Identifier: MIT\n");
        source.push_str("pragma solidity ^0.8.20;\n\n");
        source.push_str("import \"@openzeppelin/contracts/access/Ownable2Step.sol\";\n\n");

        // -- NatSpec header ----------------------------------------------------
        source.push_str(&format!("/// @title {}\n", config.name));
        source.push_str(&format!(
            "/// @notice {} token-bucket rate limiter{}.\n",
            if per_caller { "Per-caller" } else { "Global" },
            if has_budget {
                " with a per-epoch consumption budget"
            } else {
                ""
            }
        ));
        source.push_str(&format!(
            "/// @dev Compliance framework: {compliance_tag}. Generated by Legalis-Chain.\n"
        ));
        source.push_str("/// @dev Security Considerations:\n");
        source.push_str(
            "/// @dev  - Buckets refill lazily at REFILL_PER_SECOND and are capped at CAPACITY,\n",
        );
        source.push_str(
            "/// @dev    so bursts are bounded and steady-state throughput is deterministic.\n",
        );
        if has_budget {
            source.push_str(
                "/// @dev  - A global per-epoch budget caps aggregate consumption independent of buckets.\n",
            );
        }
        source.push_str("/// @dev Gas Notes:\n");
        source
            .push_str("/// @dev  - available() is O(1); consume() writes at most three slots.\n\n");

        // -- Contract declaration & constants ----------------------------------
        source.push_str(&format!("contract {} is Ownable2Step {{\n", config.name));
        source.push_str(&format!(
            "    uint256 public constant CAPACITY = {};\n",
            config.bucket_capacity
        ));
        source.push_str(&format!(
            "    uint256 public constant REFILL_PER_SECOND = {};\n",
            config.refill_per_second
        ));
        source.push_str(&format!(
            "    uint256 public constant COST_PER_OP = {};\n",
            config.cost_per_op
        ));
        source.push_str(&format!(
            "    uint256 public constant EPOCH_SECONDS = {};\n",
            config.epoch_seconds
        ));
        if has_budget {
            source.push_str(&format!(
                "    uint256 public constant EPOCH_BUDGET = {};\n",
                config.epoch_budget
            ));
        }
        source.push('\n');
        source.push_str("    uint256 public immutable startTime;\n\n");

        // -- Types & storage ---------------------------------------------------
        source.push_str("    struct Bucket {\n");
        source.push_str("        uint256 tokens;\n");
        source.push_str("        uint256 lastRefill;\n");
        source.push_str("        bool init;\n");
        source.push_str("    }\n");
        if per_caller {
            source.push_str("    mapping(address => Bucket) private _buckets;\n");
        } else {
            source.push_str("    Bucket private _global;\n");
        }
        if has_budget {
            source.push_str("    mapping(uint256 => uint256) public epochSpent;\n");
        }
        source.push('\n');

        // -- Events ------------------------------------------------------------
        source.push_str(
            "    event Consumed(address indexed caller, uint256 cost, uint256 remaining);\n\n",
        );

        // -- Constructor -------------------------------------------------------
        source.push_str("    constructor() Ownable(msg.sender) {\n");
        source.push_str("        startTime = block.timestamp;\n");
        source.push_str("    }\n\n");

        // -- Epoch view --------------------------------------------------------
        source.push_str(
            "    /// @notice Zero-based index of the epoch containing the current block.\n",
        );
        source.push_str("    function currentEpoch() public view returns (uint256) {\n");
        source.push_str("        if (EPOCH_SECONDS == 0) {\n");
        source.push_str("            return 0;\n");
        source.push_str("        }\n");
        source.push_str("        return (block.timestamp - startTime) / EPOCH_SECONDS;\n");
        source.push_str("    }\n\n");

        self.push_resource_available(&mut source, per_caller, bucket_ref);
        self.push_resource_consume(&mut source, per_caller, bucket_ref, has_budget);

        source.push_str("}\n");

        Ok(GeneratedContract {
            name: config.name.clone(),
            source,
            platform: self.platform,
            abi: None,
            deployment_script: None,
        })
    }

    /// Appends the lazy-refill `available` view.
    fn push_resource_available(&self, source: &mut String, per_caller: bool, bucket_ref: &str) {
        if per_caller {
            source.push_str("    /// @notice Tokens available to `caller` right now.\n");
            source.push_str(
                "    function available(address caller) public view returns (uint256) {\n",
            );
        } else {
            source.push_str("    /// @notice Tokens available in the shared bucket right now.\n");
            source.push_str("    function available() public view returns (uint256) {\n");
        }
        source.push_str(&format!("        Bucket storage b = {bucket_ref};\n"));
        source.push_str("        if (!b.init) {\n");
        source.push_str("            return CAPACITY;\n");
        source.push_str("        }\n");
        source.push_str("        uint256 elapsed = block.timestamp - b.lastRefill;\n");
        source.push_str("        uint256 avail = b.tokens + elapsed * REFILL_PER_SECOND;\n");
        source.push_str("        return avail > CAPACITY ? CAPACITY : avail;\n");
        source.push_str("    }\n\n");
    }

    /// Appends the `consume`/`_consume` rate-limited spend path.
    fn push_resource_consume(
        &self,
        source: &mut String,
        per_caller: bool,
        bucket_ref: &str,
        has_budget: bool,
    ) {
        let avail_call = if per_caller {
            "available(caller)"
        } else {
            "available()"
        };
        source.push_str(
            "    /// @notice Consume COST_PER_OP tokens for the caller; reverts when rate limited.\n",
        );
        source.push_str("    function consume() external returns (uint256) {\n");
        source.push_str("        return _consume(msg.sender);\n");
        source.push_str("    }\n\n");
        source.push_str("    function _consume(address caller) internal returns (uint256) {\n");
        if has_budget {
            source.push_str("        uint256 epoch = currentEpoch();\n");
            source.push_str(
                "        require(epochSpent[epoch] + COST_PER_OP <= EPOCH_BUDGET, \"RL: epoch budget exhausted\");\n",
            );
        }
        source.push_str(&format!("        uint256 avail = {avail_call};\n"));
        source.push_str("        require(avail >= COST_PER_OP, \"RL: rate limited\");\n");
        source.push_str(&format!("        Bucket storage b = {bucket_ref};\n"));
        source.push_str("        b.tokens = avail - COST_PER_OP; // effects before event\n");
        source.push_str("        b.lastRefill = block.timestamp;\n");
        source.push_str("        b.init = true;\n");
        if has_budget {
            source.push_str("        epochSpent[epoch] += COST_PER_OP;\n");
        }
        source.push_str("        emit Consumed(caller, COST_PER_OP, b.tokens);\n");
        source.push_str("        return b.tokens;\n");
        source.push_str("    }\n");
    }
}
