//! Self-healing controller generator (Solidity / EVM).
//!
//! Part of the `autonomous` module. The on-chain `_transition` routine mirrors
//! the pure-Rust [`super::next_health_state`] state machine exactly, so off-chain
//! keepers can predict every heal/auto-resume the contract will perform.
//!
//! Differentiated from the guardian-triggered [`crate::EmergencyPauseConfig`] by
//! being fully autonomous: a breach is detected, the last-known-good checkpoint is
//! restored, and the subsystem auto-resumes after the metric recovers and a
//! cool-down elapses — with no privileged operator in the recovery path.

use super::{SelfHealingConfig, invariant_constant_name, validate_self_healing};
use crate::tokenization::jurisdiction_compliance_tag;
use crate::{ChainResult, ContractGenerator, GeneratedContract};

impl ContractGenerator {
    /// Emits the Solidity source for a self-healing controller.
    pub(crate) fn generate_solidity_self_healing(
        &self,
        config: &SelfHealingConfig,
    ) -> ChainResult<GeneratedContract> {
        validate_self_healing(config)?;
        let compliance_tag = jurisdiction_compliance_tag(config.jurisdiction);
        let has_reward = config.keeper_reward_wei > 0;
        let has_checkpoint = config.checkpoint_enabled;
        let invariant_constants: Vec<(String, &String, u128, u128)> = config
            .invariants
            .iter()
            .map(|invariant| {
                (
                    invariant_constant_name(&invariant.key),
                    &invariant.key,
                    invariant.min_value,
                    invariant.max_value,
                )
            })
            .collect();

        let base = if has_reward {
            "Ownable2Step, ReentrancyGuard"
        } else {
            "Ownable2Step"
        };

        let mut source = String::from("// SPDX-License-Identifier: MIT\n");
        source.push_str("pragma solidity ^0.8.20;\n\n");
        source.push_str("import \"@openzeppelin/contracts/access/Ownable2Step.sol\";\n");
        if has_reward {
            source.push_str("import \"@openzeppelin/contracts/utils/ReentrancyGuard.sol\";\n");
        }
        source.push('\n');

        self.push_self_healing_header(&mut source, config, compliance_tag, has_checkpoint);
        source.push_str(&format!("contract {} is {base} {{\n", config.name));
        self.push_self_healing_state(&mut source, config, &invariant_constants, has_checkpoint);
        self.push_self_healing_constructor(&mut source, &invariant_constants);
        if has_checkpoint {
            self.push_self_healing_checkpoint(&mut source);
        }
        self.push_self_healing_report(&mut source, has_checkpoint, has_reward);
        source.push_str("}\n");

        Ok(GeneratedContract {
            name: config.name.clone(),
            source,
            platform: self.platform,
            abi: None,
            deployment_script: None,
        })
    }

    /// Appends the NatSpec header documenting the autonomous recovery loop.
    fn push_self_healing_header(
        &self,
        source: &mut String,
        config: &SelfHealingConfig,
        compliance_tag: &str,
        has_checkpoint: bool,
    ) {
        source.push_str(&format!("/// @title {}\n", config.name));
        source.push_str(&format!(
            "/// @notice Self-healing controller over {} health invariant(s).\n",
            config.invariants.len()
        ));
        source.push_str(&format!(
            "/// @dev Compliance framework: {compliance_tag}. Generated by Legalis-Chain.\n"
        ));
        source.push_str("/// @dev Autonomous recovery loop (no operator in the hot path):\n");
        source.push_str(
            "/// @dev   Healthy --(out of band)--> Degraded --(in band)--> Recovering --(cool-down)--> Healthy\n",
        );
        source.push_str("/// @dev Security Considerations:\n");
        source.push_str(
            "/// @dev  - reportHealth is permissionless: anyone (a keeper) can drive recovery,\n",
        );
        source.push_str("/// @dev    so liveness does not depend on a privileged unpauser.\n");
        if has_checkpoint {
            source.push_str(
                "/// @dev  - On a breach the last-known-good checkpoint is restored atomically,\n",
            );
            source.push_str("/// @dev    bounding the blast radius of a bad parameter update.\n");
        }
        source.push_str(&format!(
            "/// @dev  - Auto-resume requires the metric to stay in band for {} seconds.\n",
            config.recover_after_seconds
        ));
        source.push_str("/// @dev Gas Notes:\n");
        source.push_str(
            "/// @dev  - State is keyed by invariant; the FSM transition is branch-only (no loops).\n\n",
        );
    }

    /// Appends constants, structs, storage and events.
    fn push_self_healing_state(
        &self,
        source: &mut String,
        config: &SelfHealingConfig,
        invariants: &[(String, &String, u128, u128)],
        has_checkpoint: bool,
    ) {
        source.push_str("    uint8 public constant HEALTHY = 0;\n");
        source.push_str("    uint8 public constant DEGRADED = 1;\n");
        source.push_str("    uint8 public constant RECOVERING = 2;\n");
        source.push_str(&format!(
            "    uint256 public constant RECOVER_AFTER = {} seconds;\n",
            config.recover_after_seconds
        ));
        if config.keeper_reward_wei > 0 {
            source.push_str(&format!(
                "    uint256 public constant KEEPER_REWARD = {} wei;\n",
                config.keeper_reward_wei
            ));
        }
        source.push('\n');
        source.push_str("    // Declared health invariants.\n");
        for (constant, raw, _, _) in invariants {
            source.push_str(&format!(
                "    bytes32 public constant {constant} = keccak256(bytes(\"{raw}\"));\n"
            ));
        }
        source.push('\n');

        source.push_str("    struct Band {\n");
        source.push_str("        uint256 min;\n");
        source.push_str("        uint256 max;\n");
        source.push_str("        bool known;\n");
        source.push_str("    }\n");
        source.push_str("    struct Health {\n");
        source.push_str("        uint8 state;\n");
        source.push_str("        uint256 stateSince;\n");
        source.push_str("        uint256 lastValue;\n");
        source.push_str("    }\n");
        source.push_str("    mapping(bytes32 => Band) public band;\n");
        source.push_str("    mapping(bytes32 => Health) public health;\n");
        if has_checkpoint {
            source.push_str("    mapping(bytes32 => uint256) public param;\n");
            source.push_str("    mapping(bytes32 => uint256) private _checkpoint;\n");
            source.push_str("    mapping(bytes32 => bool) private _paramKnown;\n");
            source.push_str("    bytes32[] private _paramKeys;\n");
        }
        source.push('\n');

        source.push_str(
            "    event HealthReported(bytes32 indexed key, uint256 value, uint8 state);\n",
        );
        source.push_str("    event Breached(bytes32 indexed key, uint256 value);\n");
        source.push_str("    event Recovered(bytes32 indexed key);\n");
        if has_checkpoint {
            source.push_str("    event CheckpointCommitted();\n");
            source.push_str("    event CheckpointRestored();\n");
        }
        if config.keeper_reward_wei > 0 {
            source.push_str("    event KeeperRewarded(address indexed keeper, uint256 amount);\n");
        }
        source.push('\n');
    }

    /// Appends the constructor that registers each invariant's band.
    fn push_self_healing_constructor(
        &self,
        source: &mut String,
        invariants: &[(String, &String, u128, u128)],
    ) {
        source.push_str("    constructor() Ownable(msg.sender) {\n");
        for (constant, _, min, max) in invariants {
            source.push_str(&format!(
                "        band[{constant}] = Band({min}, {max}, true);\n"
            ));
            source.push_str(&format!(
                "        health[{constant}] = Health(HEALTHY, block.timestamp, 0);\n"
            ));
        }
        source.push_str("    }\n\n");
    }

    /// Appends the checkpoint commit/restore machinery.
    fn push_self_healing_checkpoint(&self, source: &mut String) {
        source.push_str("    /// @notice Set a tunable parameter (tracked for checkpointing).\n");
        source.push_str("    function setParam(bytes32 key, uint256 value) external onlyOwner {\n");
        source.push_str("        if (!_paramKnown[key]) {\n");
        source.push_str("            _paramKnown[key] = true;\n");
        source.push_str("            _paramKeys.push(key);\n");
        source.push_str("        }\n");
        source.push_str("        param[key] = value;\n");
        source.push_str("    }\n\n");
        source.push_str(
            "    /// @notice Snapshot the current parameters as the last-known-good state.\n",
        );
        source.push_str("    function commitCheckpoint() external onlyOwner {\n");
        source.push_str("        uint256 len = _paramKeys.length;\n");
        source.push_str("        for (uint256 i = 0; i < len; i++) {\n");
        source.push_str("            _checkpoint[_paramKeys[i]] = param[_paramKeys[i]];\n");
        source.push_str("        }\n");
        source.push_str("        emit CheckpointCommitted();\n");
        source.push_str("    }\n\n");
        source.push_str("    /// @notice Restore parameters from the last checkpoint (auto-invoked on breach).\n");
        source.push_str("    function _restoreCheckpoint() private {\n");
        source.push_str("        uint256 len = _paramKeys.length;\n");
        source.push_str("        for (uint256 i = 0; i < len; i++) {\n");
        source.push_str("            param[_paramKeys[i]] = _checkpoint[_paramKeys[i]];\n");
        source.push_str("        }\n");
        source.push_str("        emit CheckpointRestored();\n");
        source.push_str("    }\n\n");
    }

    /// Appends the report/transition/guard logic.
    fn push_self_healing_report(
        &self,
        source: &mut String,
        has_checkpoint: bool,
        has_reward: bool,
    ) {
        let report_attrs = if has_reward { " nonReentrant" } else { "" };
        source.push_str(
            "    /// @notice Report a health metric; the FSM heals and auto-resumes autonomously.\n",
        );
        source.push_str(&format!(
            "    function reportHealth(bytes32 key, uint256 value) external{report_attrs} {{\n"
        ));
        source.push_str("        Band memory b = band[key];\n");
        source.push_str("        require(b.known, \"Heal: unknown invariant\");\n");
        source.push_str("        Health storage h = health[key];\n");
        source.push_str("        bool inBand = (value >= b.min && value <= b.max);\n");
        source.push_str("        uint8 prev = h.state;\n");
        source.push_str(
            "        uint8 next = _transition(prev, inBand, block.timestamp - h.stateSince);\n",
        );
        source.push_str("        h.lastValue = value;\n");
        source.push_str("        if (next != prev) {\n");
        source.push_str("            h.state = next; // CEI: effects before any interaction\n");
        source.push_str("            h.stateSince = block.timestamp;\n");
        source.push_str("            if (next == DEGRADED) {\n");
        source.push_str("                emit Breached(key, value);\n");
        if has_checkpoint {
            source.push_str("                _restoreCheckpoint();\n");
        }
        source.push_str("            } else if (next == HEALTHY) {\n");
        source.push_str("                emit Recovered(key);\n");
        source.push_str("            }\n");
        if has_reward {
            source.push_str("            if (address(this).balance >= KEEPER_REWARD) {\n");
            source.push_str(
                "                (bool ok, ) = payable(msg.sender).call{value: KEEPER_REWARD}(\"\");\n",
            );
            source.push_str("                require(ok, \"Heal: reward transfer failed\");\n");
            source.push_str("                emit KeeperRewarded(msg.sender, KEEPER_REWARD);\n");
            source.push_str("            }\n");
        }
        source.push_str("        }\n");
        source.push_str("        emit HealthReported(key, value, next);\n");
        source.push_str("    }\n\n");

        // -- the transition state machine (parity with next_health_state) ------
        source.push_str(
            "    /// @dev Pure FSM transition mirrored off-chain by next_health_state.\n",
        );
        source.push_str(
            "    function _transition(uint8 state, bool inBand, uint256 elapsed) internal pure returns (uint8) {\n",
        );
        source.push_str("        if (state == HEALTHY) {\n");
        source.push_str("            return inBand ? HEALTHY : DEGRADED;\n");
        source.push_str("        }\n");
        source.push_str("        if (state == DEGRADED) {\n");
        source.push_str("            return inBand ? RECOVERING : DEGRADED;\n");
        source.push_str("        }\n");
        source.push_str("        if (!inBand) {\n");
        source.push_str("            return DEGRADED;\n");
        source.push_str("        }\n");
        source.push_str("        return elapsed >= RECOVER_AFTER ? HEALTHY : RECOVERING;\n");
        source.push_str("    }\n\n");

        // -- views & guard -----------------------------------------------------
        source
            .push_str("    /// @notice Whether an invariant is currently Healthy (operational).\n");
        source.push_str("    function isOperational(bytes32 key) public view returns (bool) {\n");
        source.push_str("        return health[key].state == HEALTHY;\n");
        source.push_str("    }\n\n");
        source.push_str("    /// @notice Reverts unless the invariant is Healthy; for guarded business logic.\n");
        source.push_str("    modifier whenHealthy(bytes32 key) {\n");
        source.push_str(
            "        require(health[key].state == HEALTHY, \"Heal: subsystem not healthy\");\n",
        );
        source.push_str("        _;\n");
        source.push_str("    }\n");
        if has_reward {
            source.push('\n');
            source.push_str("    /// @notice Fund the keeper-reward pool.\n");
            source.push_str("    receive() external payable {}\n");
        }
    }
}
