/* tslint:disable */
/* eslint-disable */
/**
 * Legalis API
 * REST API for the Legalis-RS legal framework. Provides CRUD operations for statutes, verification, and simulation endpoints.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface CreateStatute201Response {
    'data'?: Statute;
}
export interface CreateStatuteRequest {
    'statute': Statute;
}
export interface ErrorResponse {
    /**
     * Error message
     */
    'error': string;
}
export interface HealthCheck200Response {
    'service'?: string;
    'status'?: string;
    'version'?: string;
}
export interface SaveSimulationRequest {
    /**
     * Optional description
     */
    'description'?: string | null;
    /**
     * Name for the saved simulation
     */
    'name': string;
    'simulation_result': SimulationResponse;
}
export interface SavedSimulation {
    'created_at': string;
    /**
     * Username of creator
     */
    'created_by': string;
    /**
     * Optional description
     */
    'description'?: string | null;
    /**
     * Number of deterministic outcomes
     */
    'deterministic_outcomes'?: number;
    'deterministic_rate': number;
    /**
     * Number of discretionary outcomes
     */
    'discretionary_outcomes'?: number;
    'discretionary_rate': number;
    /**
     * Unique saved simulation identifier
     */
    'id': string;
    /**
     * User-provided name for the simulation
     */
    'name': string;
    /**
     * Population size
     */
    'population_size': number;
    /**
     * Statute IDs used in simulation
     */
    'statute_ids'?: Array<string>;
    /**
     * Number of void outcomes
     */
    'void_outcomes'?: number;
    'void_rate': number;
}
export interface SimulationRequest {
    /**
     * Additional parameters for entity generation
     */
    'entity_params': { [key: string]: string; };
    /**
     * Number of entities to generate for simulation
     */
    'population_size': number;
    /**
     * IDs of statutes to simulate (empty = all statutes)
     */
    'statute_ids': Array<string>;
}
export interface SimulationResponse {
    /**
     * Completion timestamp (RFC3339)
     */
    'completed_at': string;
    /**
     * Number of deterministic outcomes
     */
    'deterministic_outcomes': number;
    /**
     * Percentage of deterministic outcomes
     */
    'deterministic_rate': number;
    /**
     * Number of discretionary outcomes
     */
    'discretionary_outcomes': number;
    /**
     * Percentage of discretionary outcomes
     */
    'discretionary_rate': number;
    /**
     * Unique simulation identifier
     */
    'simulation_id': string;
    /**
     * Total number of entities simulated
     */
    'total_entities': number;
    /**
     * Number of void/inapplicable outcomes
     */
    'void_outcomes': number;
    /**
     * Percentage of void outcomes
     */
    'void_rate': number;
}
export interface Statute {
    /**
     * Amendment history
     */
    'amendments'?: Array<object>;
    /**
     * Description of discretionary logic
     */
    'discretion_logic'?: string | null;
    'effect': StatuteEffect;
    /**
     * Unique identifier
     */
    'id': string;
    /**
     * Jurisdiction identifier
     */
    'jurisdiction'?: string | null;
    /**
     * List of preconditions (If clauses)
     */
    'preconditions': Array<object>;
    /**
     * Hierarchical relationships to other statutes
     */
    'relations'?: Array<object>;
    /**
     * Temporal validity constraints
     */
    'temporal_validity'?: object;
    /**
     * Title of the statute
     */
    'title': string;
    /**
     * Version number
     */
    'version': number;
}
/**
 * Legal effect (Then clause)
 */
export interface StatuteEffect {
    'description': string;
    'effect_type': StatuteEffectEffectTypeEnum;
    'parameters'?: { [key: string]: string; };
}

export const StatuteEffectEffectTypeEnum = {
    Grant: 'Grant',
    Revoke: 'Revoke',
    Obligation: 'Obligation',
    Prohibition: 'Prohibition',
    MonetaryTransfer: 'MonetaryTransfer',
    StatusChange: 'StatusChange'
} as const;

export type StatuteEffectEffectTypeEnum = typeof StatuteEffectEffectTypeEnum[keyof typeof StatuteEffectEffectTypeEnum];

export interface StatuteListResponse {
    'data': StatuteListResponseData;
}
export interface StatuteListResponseData {
    'statutes'?: Array<StatuteSummary>;
}
export interface StatuteSummary {
    /**
     * Whether this statute requires judicial discretion
     */
    'has_discretion': boolean;
    /**
     * Unique statute identifier
     */
    'id': string;
    /**
     * Number of preconditions
     */
    'precondition_count': number;
    /**
     * Human-readable statute title
     */
    'title': string;
}
export interface VerifyRequest {
    /**
     * List of statute IDs to verify (empty array = verify all)
     */
    'statute_ids': Array<string>;
}
export interface VerifyResponse {
    /**
     * List of errors found
     */
    'errors': Array<string>;
    /**
     * Whether verification passed
     */
    'passed': boolean;
    /**
     * List of warnings
     */
    'warnings': Array<string>;
}
export interface VerifyStatutes200Response {
    'data'?: VerifyResponse;
}
export interface VisualizationResponse {
    /**
     * Generated visualization content
     */
    'content': string;
    /**
     * Number of discretionary nodes
     */
    'discretionary_count': number;
    /**
     * Output format used
     */
    'format': string;
    /**
     * Number of nodes in the decision tree
     */
    'node_count': number;
    /**
     * ID of the visualized statute
     */
    'statute_id': string;
}

/**
 * HealthApi - axios parameter creator
 */
export const HealthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Returns the service health status
         * @summary Health check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthCheck: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/health`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * HealthApi - functional programming interface
 */
export const HealthApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = HealthApiAxiosParamCreator(configuration)
    return {
        /**
         * Returns the service health status
         * @summary Health check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async healthCheck(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<HealthCheck200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.healthCheck(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HealthApi.healthCheck']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * HealthApi - factory interface
 */
export const HealthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = HealthApiFp(configuration)
    return {
        /**
         * Returns the service health status
         * @summary Health check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthCheck(options?: RawAxiosRequestConfig): AxiosPromise<HealthCheck200Response> {
            return localVarFp.healthCheck(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * HealthApi - object-oriented interface
 */
export class HealthApi extends BaseAPI {
    /**
     * Returns the service health status
     * @summary Health check
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public healthCheck(options?: RawAxiosRequestConfig) {
        return HealthApiFp(this.configuration).healthCheck(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * MetricsApi - axios parameter creator
 */
export const MetricsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Returns metrics in Prometheus format for monitoring
         * @summary Prometheus metrics
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        metrics: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/metrics`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'text/plain';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MetricsApi - functional programming interface
 */
export const MetricsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MetricsApiAxiosParamCreator(configuration)
    return {
        /**
         * Returns metrics in Prometheus format for monitoring
         * @summary Prometheus metrics
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async metrics(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.metrics(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MetricsApi.metrics']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * MetricsApi - factory interface
 */
export const MetricsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MetricsApiFp(configuration)
    return {
        /**
         * Returns metrics in Prometheus format for monitoring
         * @summary Prometheus metrics
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        metrics(options?: RawAxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.metrics(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MetricsApi - object-oriented interface
 */
export class MetricsApi extends BaseAPI {
    /**
     * Returns metrics in Prometheus format for monitoring
     * @summary Prometheus metrics
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public metrics(options?: RawAxiosRequestConfig) {
        return MetricsApiFp(this.configuration).metrics(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * SimulationApi - axios parameter creator
 */
export const SimulationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Retrieve a list of saved simulation results
         * @summary List saved simulations
         * @param {number} [limit] 
         * @param {number} [offset] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listSavedSimulations: async (limit?: number, offset?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/simulate/saved`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyHeader required
            await setApiKeyToObject(localVarHeaderParameter, "X-API-Key", configuration)

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Simulates the application of statutes to a generated population
         * @summary Run a simulation
         * @param {SimulationRequest} simulationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        runSimulation: async (simulationRequest: SimulationRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'simulationRequest' is not null or undefined
            assertParamExists('runSimulation', 'simulationRequest', simulationRequest)
            const localVarPath = `/api/v1/simulate`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyHeader required
            await setApiKeyToObject(localVarHeaderParameter, "X-API-Key", configuration)

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(simulationRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Save simulation results for later retrieval
         * @summary Save a simulation
         * @param {SaveSimulationRequest} saveSimulationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        saveSimulation: async (saveSimulationRequest: SaveSimulationRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'saveSimulationRequest' is not null or undefined
            assertParamExists('saveSimulation', 'saveSimulationRequest', saveSimulationRequest)
            const localVarPath = `/api/v1/simulate/saved`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyHeader required
            await setApiKeyToObject(localVarHeaderParameter, "X-API-Key", configuration)

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(saveSimulationRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Run simulation with real-time progress updates via Server-Sent Events (SSE)
         * @summary Stream simulation results
         * @param {SimulationRequest} simulationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        streamSimulation: async (simulationRequest: SimulationRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'simulationRequest' is not null or undefined
            assertParamExists('streamSimulation', 'simulationRequest', simulationRequest)
            const localVarPath = `/api/v1/simulate/stream`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyHeader required
            await setApiKeyToObject(localVarHeaderParameter, "X-API-Key", configuration)

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'text/event-stream';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(simulationRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SimulationApi - functional programming interface
 */
export const SimulationApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SimulationApiAxiosParamCreator(configuration)
    return {
        /**
         * Retrieve a list of saved simulation results
         * @summary List saved simulations
         * @param {number} [limit] 
         * @param {number} [offset] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listSavedSimulations(limit?: number, offset?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<SavedSimulation>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listSavedSimulations(limit, offset, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SimulationApi.listSavedSimulations']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Simulates the application of statutes to a generated population
         * @summary Run a simulation
         * @param {SimulationRequest} simulationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async runSimulation(simulationRequest: SimulationRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SimulationResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.runSimulation(simulationRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SimulationApi.runSimulation']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Save simulation results for later retrieval
         * @summary Save a simulation
         * @param {SaveSimulationRequest} saveSimulationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async saveSimulation(saveSimulationRequest: SaveSimulationRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SavedSimulation>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.saveSimulation(saveSimulationRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SimulationApi.saveSimulation']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Run simulation with real-time progress updates via Server-Sent Events (SSE)
         * @summary Stream simulation results
         * @param {SimulationRequest} simulationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async streamSimulation(simulationRequest: SimulationRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.streamSimulation(simulationRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SimulationApi.streamSimulation']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SimulationApi - factory interface
 */
export const SimulationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SimulationApiFp(configuration)
    return {
        /**
         * Retrieve a list of saved simulation results
         * @summary List saved simulations
         * @param {number} [limit] 
         * @param {number} [offset] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listSavedSimulations(limit?: number, offset?: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<SavedSimulation>> {
            return localVarFp.listSavedSimulations(limit, offset, options).then((request) => request(axios, basePath));
        },
        /**
         * Simulates the application of statutes to a generated population
         * @summary Run a simulation
         * @param {SimulationRequest} simulationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        runSimulation(simulationRequest: SimulationRequest, options?: RawAxiosRequestConfig): AxiosPromise<SimulationResponse> {
            return localVarFp.runSimulation(simulationRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Save simulation results for later retrieval
         * @summary Save a simulation
         * @param {SaveSimulationRequest} saveSimulationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        saveSimulation(saveSimulationRequest: SaveSimulationRequest, options?: RawAxiosRequestConfig): AxiosPromise<SavedSimulation> {
            return localVarFp.saveSimulation(saveSimulationRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Run simulation with real-time progress updates via Server-Sent Events (SSE)
         * @summary Stream simulation results
         * @param {SimulationRequest} simulationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        streamSimulation(simulationRequest: SimulationRequest, options?: RawAxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.streamSimulation(simulationRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SimulationApi - object-oriented interface
 */
export class SimulationApi extends BaseAPI {
    /**
     * Retrieve a list of saved simulation results
     * @summary List saved simulations
     * @param {number} [limit] 
     * @param {number} [offset] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listSavedSimulations(limit?: number, offset?: number, options?: RawAxiosRequestConfig) {
        return SimulationApiFp(this.configuration).listSavedSimulations(limit, offset, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Simulates the application of statutes to a generated population
     * @summary Run a simulation
     * @param {SimulationRequest} simulationRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public runSimulation(simulationRequest: SimulationRequest, options?: RawAxiosRequestConfig) {
        return SimulationApiFp(this.configuration).runSimulation(simulationRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Save simulation results for later retrieval
     * @summary Save a simulation
     * @param {SaveSimulationRequest} saveSimulationRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public saveSimulation(saveSimulationRequest: SaveSimulationRequest, options?: RawAxiosRequestConfig) {
        return SimulationApiFp(this.configuration).saveSimulation(saveSimulationRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Run simulation with real-time progress updates via Server-Sent Events (SSE)
     * @summary Stream simulation results
     * @param {SimulationRequest} simulationRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public streamSimulation(simulationRequest: SimulationRequest, options?: RawAxiosRequestConfig) {
        return SimulationApiFp(this.configuration).streamSimulation(simulationRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * StatutesApi - axios parameter creator
 */
export const StatutesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Creates a new statute in the system
         * @summary Create a new statute
         * @param {CreateStatuteRequest} createStatuteRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createStatute: async (createStatuteRequest: CreateStatuteRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createStatuteRequest' is not null or undefined
            assertParamExists('createStatute', 'createStatuteRequest', createStatuteRequest)
            const localVarPath = `/api/v1/statutes`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyHeader required
            await setApiKeyToObject(localVarHeaderParameter, "X-API-Key", configuration)

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createStatuteRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Deletes a statute from the system
         * @summary Delete a statute
         * @param {string} id Statute ID to delete
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteStatute: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteStatute', 'id', id)
            const localVarPath = `/api/v1/statutes/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyHeader required
            await setApiKeyToObject(localVarHeaderParameter, "X-API-Key", configuration)

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns detailed information about a specific statute
         * @summary Get a statute by ID
         * @param {string} id Statute ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStatute: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getStatute', 'id', id)
            const localVarPath = `/api/v1/statutes/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyHeader required
            await setApiKeyToObject(localVarHeaderParameter, "X-API-Key", configuration)

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns a list of all statutes with summary information
         * @summary List all statutes
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listStatutes: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/statutes`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyHeader required
            await setApiKeyToObject(localVarHeaderParameter, "X-API-Key", configuration)

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * StatutesApi - functional programming interface
 */
export const StatutesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = StatutesApiAxiosParamCreator(configuration)
    return {
        /**
         * Creates a new statute in the system
         * @summary Create a new statute
         * @param {CreateStatuteRequest} createStatuteRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createStatute(createStatuteRequest: CreateStatuteRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateStatute201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createStatute(createStatuteRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['StatutesApi.createStatute']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Deletes a statute from the system
         * @summary Delete a statute
         * @param {string} id Statute ID to delete
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteStatute(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteStatute(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['StatutesApi.deleteStatute']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns detailed information about a specific statute
         * @summary Get a statute by ID
         * @param {string} id Statute ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getStatute(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateStatute201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getStatute(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['StatutesApi.getStatute']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns a list of all statutes with summary information
         * @summary List all statutes
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listStatutes(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<StatuteListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listStatutes(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['StatutesApi.listStatutes']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * StatutesApi - factory interface
 */
export const StatutesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = StatutesApiFp(configuration)
    return {
        /**
         * Creates a new statute in the system
         * @summary Create a new statute
         * @param {CreateStatuteRequest} createStatuteRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createStatute(createStatuteRequest: CreateStatuteRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateStatute201Response> {
            return localVarFp.createStatute(createStatuteRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Deletes a statute from the system
         * @summary Delete a statute
         * @param {string} id Statute ID to delete
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteStatute(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteStatute(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns detailed information about a specific statute
         * @summary Get a statute by ID
         * @param {string} id Statute ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStatute(id: string, options?: RawAxiosRequestConfig): AxiosPromise<CreateStatute201Response> {
            return localVarFp.getStatute(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns a list of all statutes with summary information
         * @summary List all statutes
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listStatutes(options?: RawAxiosRequestConfig): AxiosPromise<StatuteListResponse> {
            return localVarFp.listStatutes(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * StatutesApi - object-oriented interface
 */
export class StatutesApi extends BaseAPI {
    /**
     * Creates a new statute in the system
     * @summary Create a new statute
     * @param {CreateStatuteRequest} createStatuteRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createStatute(createStatuteRequest: CreateStatuteRequest, options?: RawAxiosRequestConfig) {
        return StatutesApiFp(this.configuration).createStatute(createStatuteRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Deletes a statute from the system
     * @summary Delete a statute
     * @param {string} id Statute ID to delete
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteStatute(id: string, options?: RawAxiosRequestConfig) {
        return StatutesApiFp(this.configuration).deleteStatute(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns detailed information about a specific statute
     * @summary Get a statute by ID
     * @param {string} id Statute ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getStatute(id: string, options?: RawAxiosRequestConfig) {
        return StatutesApiFp(this.configuration).getStatute(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns a list of all statutes with summary information
     * @summary List all statutes
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listStatutes(options?: RawAxiosRequestConfig) {
        return StatutesApiFp(this.configuration).listStatutes(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * VerificationApi - axios parameter creator
 */
export const VerificationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Verifies one or more statutes for logical consistency and validity
         * @summary Verify statutes
         * @param {VerifyRequest} verifyRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        verifyStatutes: async (verifyRequest: VerifyRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'verifyRequest' is not null or undefined
            assertParamExists('verifyStatutes', 'verifyRequest', verifyRequest)
            const localVarPath = `/api/v1/verify`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyHeader required
            await setApiKeyToObject(localVarHeaderParameter, "X-API-Key", configuration)

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(verifyRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * VerificationApi - functional programming interface
 */
export const VerificationApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = VerificationApiAxiosParamCreator(configuration)
    return {
        /**
         * Verifies one or more statutes for logical consistency and validity
         * @summary Verify statutes
         * @param {VerifyRequest} verifyRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async verifyStatutes(verifyRequest: VerifyRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<VerifyStatutes200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.verifyStatutes(verifyRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VerificationApi.verifyStatutes']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * VerificationApi - factory interface
 */
export const VerificationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = VerificationApiFp(configuration)
    return {
        /**
         * Verifies one or more statutes for logical consistency and validity
         * @summary Verify statutes
         * @param {VerifyRequest} verifyRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        verifyStatutes(verifyRequest: VerifyRequest, options?: RawAxiosRequestConfig): AxiosPromise<VerifyStatutes200Response> {
            return localVarFp.verifyStatutes(verifyRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * VerificationApi - object-oriented interface
 */
export class VerificationApi extends BaseAPI {
    /**
     * Verifies one or more statutes for logical consistency and validity
     * @summary Verify statutes
     * @param {VerifyRequest} verifyRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public verifyStatutes(verifyRequest: VerifyRequest, options?: RawAxiosRequestConfig) {
        return VerificationApiFp(this.configuration).verifyStatutes(verifyRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * VisualizationApi - axios parameter creator
 */
export const VisualizationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Generate a visual representation of a statute in various formats (SVG, Mermaid, PlantUML, DOT, ASCII, HTML)
         * @summary Visualize a statute
         * @param {string} id Statute ID to visualize
         * @param {VisualizeStatuteFormatEnum} [format] Output format
         * @param {VisualizeStatuteThemeEnum} [theme] Color theme
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        visualizeStatute: async (id: string, format?: VisualizeStatuteFormatEnum, theme?: VisualizeStatuteThemeEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('visualizeStatute', 'id', id)
            const localVarPath = `/api/v1/visualize/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyHeader required
            await setApiKeyToObject(localVarHeaderParameter, "X-API-Key", configuration)

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }

            if (theme !== undefined) {
                localVarQueryParameter['theme'] = theme;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * VisualizationApi - functional programming interface
 */
export const VisualizationApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = VisualizationApiAxiosParamCreator(configuration)
    return {
        /**
         * Generate a visual representation of a statute in various formats (SVG, Mermaid, PlantUML, DOT, ASCII, HTML)
         * @summary Visualize a statute
         * @param {string} id Statute ID to visualize
         * @param {VisualizeStatuteFormatEnum} [format] Output format
         * @param {VisualizeStatuteThemeEnum} [theme] Color theme
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async visualizeStatute(id: string, format?: VisualizeStatuteFormatEnum, theme?: VisualizeStatuteThemeEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<VisualizationResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.visualizeStatute(id, format, theme, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VisualizationApi.visualizeStatute']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * VisualizationApi - factory interface
 */
export const VisualizationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = VisualizationApiFp(configuration)
    return {
        /**
         * Generate a visual representation of a statute in various formats (SVG, Mermaid, PlantUML, DOT, ASCII, HTML)
         * @summary Visualize a statute
         * @param {string} id Statute ID to visualize
         * @param {VisualizeStatuteFormatEnum} [format] Output format
         * @param {VisualizeStatuteThemeEnum} [theme] Color theme
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        visualizeStatute(id: string, format?: VisualizeStatuteFormatEnum, theme?: VisualizeStatuteThemeEnum, options?: RawAxiosRequestConfig): AxiosPromise<VisualizationResponse> {
            return localVarFp.visualizeStatute(id, format, theme, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * VisualizationApi - object-oriented interface
 */
export class VisualizationApi extends BaseAPI {
    /**
     * Generate a visual representation of a statute in various formats (SVG, Mermaid, PlantUML, DOT, ASCII, HTML)
     * @summary Visualize a statute
     * @param {string} id Statute ID to visualize
     * @param {VisualizeStatuteFormatEnum} [format] Output format
     * @param {VisualizeStatuteThemeEnum} [theme] Color theme
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public visualizeStatute(id: string, format?: VisualizeStatuteFormatEnum, theme?: VisualizeStatuteThemeEnum, options?: RawAxiosRequestConfig) {
        return VisualizationApiFp(this.configuration).visualizeStatute(id, format, theme, options).then((request) => request(this.axios, this.basePath));
    }
}

export const VisualizeStatuteFormatEnum = {
    Svg: 'svg',
    Mermaid: 'mermaid',
    Plantuml: 'plantuml',
    Dot: 'dot',
    Ascii: 'ascii',
    Html: 'html'
} as const;
export type VisualizeStatuteFormatEnum = typeof VisualizeStatuteFormatEnum[keyof typeof VisualizeStatuteFormatEnum];
export const VisualizeStatuteThemeEnum = {
    Light: 'light',
    Dark: 'dark',
    HighContrast: 'high_contrast',
    ColorblindFriendly: 'colorblind_friendly'
} as const;
export type VisualizeStatuteThemeEnum = typeof VisualizeStatuteThemeEnum[keyof typeof VisualizeStatuteThemeEnum];


