/* tslint:disable */
/* eslint-disable */
/**
 * Legalis API
 * REST API for the Legalis-RS legal framework. Provides CRUD operations for statutes, verification, and simulation endpoints.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

