# coding: utf-8

"""
    Legalis API

    REST API for the Legalis-RS legal framework. Provides CRUD operations for statutes, verification, and simulation endpoints.

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from legalis_client.models.create_statute201_response import CreateStatute201Response

class TestCreateStatute201Response(unittest.TestCase):
    """CreateStatute201Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateStatute201Response:
        """Test CreateStatute201Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateStatute201Response`
        """
        model = CreateStatute201Response()
        if include_optional:
            return CreateStatute201Response(
                data = legalis_client.models.statute.Statute(
                    amendments = [
                        None
                        ], 
                    discretion_logic = '', 
                    effect = legalis_client.models.statute_effect.Statute_effect(
                        description = '', 
                        effect_type = 'Grant', 
                        parameters = {
                            'key' : ''
                            }, ), 
                    id = 'civil-code-article-1', 
                    jurisdiction = '', 
                    preconditions = [
                        None
                        ], 
                    relations = [
                        None
                        ], 
                    temporal_validity = legalis_client.models.temporal_validity.temporal_validity(), 
                    title = '', 
                    version = 1, )
            )
        else:
            return CreateStatute201Response(
        )
        """

    def testCreateStatute201Response(self):
        """Test CreateStatute201Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
