# coding: utf-8

"""
    Legalis API

    REST API for the Legalis-RS legal framework. Provides CRUD operations for statutes, verification, and simulation endpoints.

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from legalis_client.models.simulation_response import SimulationResponse

class TestSimulationResponse(unittest.TestCase):
    """SimulationResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SimulationResponse:
        """Test SimulationResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SimulationResponse`
        """
        model = SimulationResponse()
        if include_optional:
            return SimulationResponse(
                completed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                deterministic_outcomes = 56,
                deterministic_rate = 1.337,
                discretionary_outcomes = 56,
                discretionary_rate = 1.337,
                simulation_id = '',
                total_entities = 56,
                void_outcomes = 56,
                void_rate = 1.337
            )
        else:
            return SimulationResponse(
                completed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                deterministic_outcomes = 56,
                deterministic_rate = 1.337,
                discretionary_outcomes = 56,
                discretionary_rate = 1.337,
                simulation_id = '',
                total_entities = 56,
                void_outcomes = 56,
                void_rate = 1.337,
        )
        """

    def testSimulationResponse(self):
        """Test SimulationResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
