# coding: utf-8

"""
    Legalis API

    REST API for the Legalis-RS legal framework. Provides CRUD operations for statutes, verification, and simulation endpoints.

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from legalis_client.models.visualization_response import VisualizationResponse

class TestVisualizationResponse(unittest.TestCase):
    """VisualizationResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VisualizationResponse:
        """Test VisualizationResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VisualizationResponse`
        """
        model = VisualizationResponse()
        if include_optional:
            return VisualizationResponse(
                content = '',
                discretionary_count = 56,
                format = '',
                node_count = 56,
                statute_id = ''
            )
        else:
            return VisualizationResponse(
                content = '',
                discretionary_count = 56,
                format = '',
                node_count = 56,
                statute_id = '',
        )
        """

    def testVisualizationResponse(self):
        """Test VisualizationResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
