# coding: utf-8

"""
    Legalis API

    REST API for the Legalis-RS legal framework. Provides CRUD operations for statutes, verification, and simulation endpoints.

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from legalis_client.api.simulation_api import SimulationApi


class TestSimulationApi(unittest.TestCase):
    """SimulationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SimulationApi()

    def tearDown(self) -> None:
        pass

    def test_list_saved_simulations(self) -> None:
        """Test case for list_saved_simulations

        List saved simulations
        """
        pass

    def test_run_simulation(self) -> None:
        """Test case for run_simulation

        Run a simulation
        """
        pass

    def test_save_simulation(self) -> None:
        """Test case for save_simulation

        Save a simulation
        """
        pass

    def test_stream_simulation(self) -> None:
        """Test case for stream_simulation

        Stream simulation results
        """
        pass


if __name__ == '__main__':
    unittest.main()
