# coding: utf-8

"""
    Legalis API

    REST API for the Legalis-RS legal framework. Provides CRUD operations for statutes, verification, and simulation endpoints.

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from legalis_client.models.save_simulation_request import SaveSimulationRequest

class TestSaveSimulationRequest(unittest.TestCase):
    """SaveSimulationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SaveSimulationRequest:
        """Test SaveSimulationRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SaveSimulationRequest`
        """
        model = SaveSimulationRequest()
        if include_optional:
            return SaveSimulationRequest(
                description = '',
                name = '',
                simulation_result = legalis_client.models.simulation_response.SimulationResponse(
                    completed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    deterministic_outcomes = 56, 
                    deterministic_rate = 1.337, 
                    discretionary_outcomes = 56, 
                    discretionary_rate = 1.337, 
                    simulation_id = '', 
                    total_entities = 56, 
                    void_outcomes = 56, 
                    void_rate = 1.337, )
            )
        else:
            return SaveSimulationRequest(
                name = '',
                simulation_result = legalis_client.models.simulation_response.SimulationResponse(
                    completed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    deterministic_outcomes = 56, 
                    deterministic_rate = 1.337, 
                    discretionary_outcomes = 56, 
                    discretionary_rate = 1.337, 
                    simulation_id = '', 
                    total_entities = 56, 
                    void_outcomes = 56, 
                    void_rate = 1.337, ),
        )
        """

    def testSaveSimulationRequest(self):
        """Test SaveSimulationRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
