# coding: utf-8

"""
    Legalis API

    REST API for the Legalis-RS legal framework. Provides CRUD operations for statutes, verification, and simulation endpoints.

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from legalis_client.models.statute_list_response import StatuteListResponse

class TestStatuteListResponse(unittest.TestCase):
    """StatuteListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StatuteListResponse:
        """Test StatuteListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StatuteListResponse`
        """
        model = StatuteListResponse()
        if include_optional:
            return StatuteListResponse(
                data = legalis_client.models.statute_list_response_data.StatuteListResponse_data(
                    statutes = [
                        legalis_client.models.statute_summary.StatuteSummary(
                            has_discretion = True, 
                            id = 'civil-code-art-1', 
                            precondition_count = 0, 
                            title = 'Adult Rights', )
                        ], )
            )
        else:
            return StatuteListResponse(
                data = legalis_client.models.statute_list_response_data.StatuteListResponse_data(
                    statutes = [
                        legalis_client.models.statute_summary.StatuteSummary(
                            has_discretion = True, 
                            id = 'civil-code-art-1', 
                            precondition_count = 0, 
                            title = 'Adult Rights', )
                        ], ),
        )
        """

    def testStatuteListResponse(self):
        """Test StatuteListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
