# coding: utf-8

"""
    Legalis API

    REST API for the Legalis-RS legal framework. Provides CRUD operations for statutes, verification, and simulation endpoints.

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from legalis_client.models.saved_simulation import SavedSimulation

class TestSavedSimulation(unittest.TestCase):
    """SavedSimulation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SavedSimulation:
        """Test SavedSimulation
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SavedSimulation`
        """
        model = SavedSimulation()
        if include_optional:
            return SavedSimulation(
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                created_by = '',
                description = '',
                deterministic_outcomes = 56,
                deterministic_rate = 1.337,
                discretionary_outcomes = 56,
                discretionary_rate = 1.337,
                id = '',
                name = '',
                population_size = 56,
                statute_ids = [
                    ''
                    ],
                void_outcomes = 56,
                void_rate = 1.337
            )
        else:
            return SavedSimulation(
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                created_by = '',
                deterministic_rate = 1.337,
                discretionary_rate = 1.337,
                id = '',
                name = '',
                population_size = 56,
                void_rate = 1.337,
        )
        """

    def testSavedSimulation(self):
        """Test SavedSimulation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
