# coding: utf-8

"""
    Legalis API

    REST API for the Legalis-RS legal framework. Provides CRUD operations for statutes, verification, and simulation endpoints.

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from legalis_client.models.verify_response import VerifyResponse

class TestVerifyResponse(unittest.TestCase):
    """VerifyResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VerifyResponse:
        """Test VerifyResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VerifyResponse`
        """
        model = VerifyResponse()
        if include_optional:
            return VerifyResponse(
                errors = [
                    ''
                    ],
                passed = True,
                warnings = [
                    ''
                    ]
            )
        else:
            return VerifyResponse(
                errors = [
                    ''
                    ],
                passed = True,
                warnings = [
                    ''
                    ],
        )
        """

    def testVerifyResponse(self):
        """Test VerifyResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
