# coding: utf-8

"""
    Legalis API

    REST API for the Legalis-RS legal framework. Provides CRUD operations for statutes, verification, and simulation endpoints.

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from legalis_client.api.verification_api import VerificationApi


class TestVerificationApi(unittest.TestCase):
    """VerificationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = VerificationApi()

    def tearDown(self) -> None:
        pass

    def test_verify_statutes(self) -> None:
        """Test case for verify_statutes

        Verify statutes
        """
        pass


if __name__ == '__main__':
    unittest.main()
