# coding: utf-8

"""
    Legalis API

    REST API for the Legalis-RS legal framework. Provides CRUD operations for statutes, verification, and simulation endpoints.

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from legalis_client.api.visualization_api import VisualizationApi


class TestVisualizationApi(unittest.TestCase):
    """VisualizationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = VisualizationApi()

    def tearDown(self) -> None:
        pass

    def test_visualize_statute(self) -> None:
        """Test case for visualize_statute

        Visualize a statute
        """
        pass


if __name__ == '__main__':
    unittest.main()
