//! Commodity tokenization generator (Solidity / EVM).
//!
//! 🤖 Part of the `tokenization` module.

use super::{CommodityToken, jurisdiction_compliance_tag};
use crate::{ChainError, ChainResult, ContractGenerator, GeneratedContract};

impl ContractGenerator {
    /// Emits the Solidity source for an asset-backed commodity token.
    ///
    /// The generated contract is an ERC-20 backed by a custodied physical reserve.
    /// Minting can be gated by a Chainlink proof-of-reserves feed, and holders can
    /// redeem according to the configured [`RedemptionPolicy`](super::RedemptionPolicy)
    /// (physical delivery requests and/or cash settlement).
    pub(crate) fn generate_solidity_commodity_token(
        &self,
        config: &CommodityToken,
    ) -> ChainResult<GeneratedContract> {
        if config.backing_units_per_token == 0 {
            return Err(ChainError::GenerationError(
                "CommodityToken.backing_units_per_token must be greater than zero".to_string(),
            ));
        }
        let compliance_tag = jurisdiction_compliance_tag(config.jurisdiction);
        let commodity_label = config.commodity_type.label();
        let allows_physical = config.redemption.allows_physical();
        let allows_cash = config.redemption.allows_cash();

        let mut source = String::from("// SPDX-License-Identifier: MIT\n");
        source.push_str("pragma solidity ^0.8.20;\n\n");
        source.push_str("import \"@openzeppelin/contracts/token/ERC20/ERC20.sol\";\n");
        source.push_str(
            "import \"@openzeppelin/contracts/token/ERC20/extensions/ERC20Burnable.sol\";\n",
        );
        source.push_str("import \"@openzeppelin/contracts/access/Ownable2Step.sol\";\n");
        source.push_str("import \"@openzeppelin/contracts/utils/Pausable.sol\";\n");
        source.push_str("import \"@openzeppelin/contracts/utils/ReentrancyGuard.sol\";\n");
        if config.proof_of_reserves {
            source.push_str(
                "import \"@chainlink/contracts/src/v0.8/interfaces/AggregatorV3Interface.sol\";\n",
            );
        }
        source.push('\n');

        // -- NatSpec header ----------------------------------------------------
        source.push_str(&format!("/// @title {}\n", config.name));
        source.push_str(&format!(
            "/// @notice Asset-backed token redeemable against custodied {}.\n",
            commodity_label
        ));
        source.push_str(&format!(
            "/// @notice Each whole token is backed by {} nano-{} held by {}.\n",
            config.backing_units_per_token, config.unit_label, config.custodian
        ));
        source.push_str(&format!(
            "/// @notice Redemption policy: {}.\n",
            config.redemption.label()
        ));
        source.push_str(&format!(
            "/// @dev Compliance framework: {}. Generated by Legalis-Chain.\n",
            compliance_tag
        ));
        source.push_str("/// @dev Security Considerations:\n");
        source.push_str("/// @dev  - Ownable2Step for safe custodian/issuer handover.\n");
        if config.proof_of_reserves {
            source.push_str(
                "/// @dev  - Minting is gated by a Chainlink proof-of-reserves oracle (no over-issuance).\n",
            );
        }
        source.push_str(
            "/// @dev  - Cash redemption uses ReentrancyGuard and the CEI pattern (burn before pay).\n",
        );
        source.push_str("/// @dev Gas Notes:\n");
        source.push_str(
            "/// @dev  - Reserve checks read a single oracle round; redemption avoids storage loops.\n\n",
        );

        // -- Contract declaration ---------------------------------------------
        source.push_str(&format!(
            "contract {} is ERC20, ERC20Burnable, Ownable2Step, Pausable, ReentrancyGuard {{\n",
            config.name
        ));

        // -- Constants & storage ----------------------------------------------
        source.push_str(&format!(
            "    /// @notice Custodian operating the physical reserve.\n    string public constant CUSTODIAN = \"{}\";\n",
            config.custodian
        ));
        source.push_str(&format!(
            "    /// @notice Label of the physical backing unit.\n    string public constant UNIT_LABEL = \"{}\";\n",
            config.unit_label
        ));
        source.push_str(&format!(
            "    /// @notice Backing nano-units represented by one whole token.\n    uint256 public constant BACKING_UNITS_PER_TOKEN = {};\n",
            config.backing_units_per_token
        ));
        if config.proof_of_reserves {
            source.push_str(
                "    /// @notice Whether minting is gated by proof-of-reserves.\n    bool public constant PROOF_OF_RESERVES = true;\n",
            );
            source.push_str(
                "    /// @notice Chainlink proof-of-reserves feed (reports backing nano-units).\n",
            );
            source.push_str("    AggregatorV3Interface public immutable reserveFeed;\n");
        }
        if allows_cash {
            source.push_str(
                "    /// @notice Cash-settlement price per token in wei (set by the issuer).\n    uint256 public settlementPricePerToken;\n",
            );
        }
        if allows_physical {
            source.push_str("    /// @notice Outstanding physical redemption requests.\n");
            source.push_str("    struct Redemption {\n");
            source.push_str("        address holder;\n");
            source.push_str("        uint256 amount;\n");
            source.push_str("        uint256 backingNanoUnits;\n");
            source.push_str("        bool fulfilled;\n");
            source.push_str("    }\n");
            source.push_str("    Redemption[] public redemptions;\n");
        }
        source.push('\n');

        // -- Events ------------------------------------------------------------
        source.push_str("    event Minted(address indexed to, uint256 amount);\n");
        if allows_physical {
            source.push_str(
                "    event PhysicalRedemptionRequested(uint256 indexed id, address indexed holder, uint256 amount);\n",
            );
            source.push_str("    event PhysicalRedemptionFulfilled(uint256 indexed id);\n");
        }
        if allows_cash {
            source.push_str(
                "    event CashRedeemed(address indexed holder, uint256 amount, uint256 payout);\n",
            );
            source.push_str("    event SettlementPriceUpdated(uint256 pricePerToken);\n");
        }
        source.push('\n');

        // -- Constructor -------------------------------------------------------
        if config.proof_of_reserves {
            source.push_str(&format!(
                "    constructor(address reserveFeed_) ERC20(\"{}\", \"{}\") Ownable(msg.sender) {{\n",
                config.name, config.symbol
            ));
            source.push_str(
                "        require(reserveFeed_ != address(0), \"Commodity: zero feed\");\n",
            );
            source.push_str("        reserveFeed = AggregatorV3Interface(reserveFeed_);\n");
            source.push_str("    }\n\n");
        } else {
            source.push_str(&format!(
                "    constructor() ERC20(\"{}\", \"{}\") Ownable(msg.sender) {{}}\n\n",
                config.name, config.symbol
            ));
        }

        // -- Reserve view ------------------------------------------------------
        source.push_str(
            "    /// @notice Total backing (nano-units) implied by the circulating supply.\n",
        );
        source.push_str("    function requiredReserveBacking() public view returns (uint256) {\n");
        source.push_str("        return totalSupply() * BACKING_UNITS_PER_TOKEN;\n");
        source.push_str("    }\n\n");
        if config.proof_of_reserves {
            source.push_str(
                "    /// @notice Latest attested reserves (nano-units) from the oracle.\n",
            );
            source.push_str("    function attestedReserves() public view returns (uint256) {\n");
            source.push_str("        (, int256 reserves, , , ) = reserveFeed.latestRoundData();\n");
            source.push_str("        require(reserves >= 0, \"Commodity: negative reserves\");\n");
            source.push_str("        return uint256(reserves);\n");
            source.push_str("    }\n\n");
        }

        // -- Mint --------------------------------------------------------------
        source.push_str("    /// @notice Issue new tokens against newly custodied reserves.\n");
        source.push_str(
            "    function mint(address to, uint256 amount) external onlyOwner whenNotPaused {\n",
        );
        source.push_str("        require(amount > 0, \"Commodity: zero amount\");\n");
        if config.proof_of_reserves {
            source.push_str(
                "        require((totalSupply() + amount) * BACKING_UNITS_PER_TOKEN <= attestedReserves(), \"Commodity: insufficient reserves\");\n",
            );
        }
        source.push_str("        _mint(to, amount);\n");
        source.push_str("        emit Minted(to, amount);\n");
        source.push_str("    }\n\n");

        // -- Pause control -----------------------------------------------------
        source.push_str("    /// @notice Pause transfers, minting and redemptions.\n");
        source.push_str("    function pause() external onlyOwner {\n");
        source.push_str("        _pause();\n");
        source.push_str("    }\n\n");
        source.push_str("    /// @notice Resume operations.\n");
        source.push_str("    function unpause() external onlyOwner {\n");
        source.push_str("        _unpause();\n");
        source.push_str("    }\n\n");

        // -- Redemption flows --------------------------------------------------
        self.push_commodity_redemptions(&mut source, config);

        // -- Pause-aware transfer hook ----------------------------------------
        source.push_str(
            "    function _update(address from, address to, uint256 value) internal override whenNotPaused {\n",
        );
        source.push_str("        super._update(from, to, value);\n");
        source.push_str("    }\n");
        source.push_str("}\n");

        Ok(GeneratedContract {
            name: config.name.clone(),
            source,
            platform: self.platform,
            abi: None,
            deployment_script: None,
        })
    }

    /// Appends the redemption functions selected by the configured policy.
    fn push_commodity_redemptions(&self, source: &mut String, config: &CommodityToken) {
        if config.redemption.allows_physical() {
            source.push_str("    /// @notice Burn tokens and request physical delivery of the backing commodity.\n");
            source.push_str(
                "    function requestPhysicalRedemption(uint256 amount) external whenNotPaused returns (uint256) {\n",
            );
            source.push_str("        require(amount > 0, \"Commodity: zero amount\");\n");
            source.push_str("        _burn(msg.sender, amount); // effects before bookkeeping\n");
            source.push_str("        uint256 id = redemptions.length;\n");
            source.push_str("        redemptions.push(Redemption({\n");
            source.push_str("            holder: msg.sender,\n");
            source.push_str("            amount: amount,\n");
            source.push_str("            backingNanoUnits: amount * BACKING_UNITS_PER_TOKEN,\n");
            source.push_str("            fulfilled: false\n");
            source.push_str("        }));\n");
            source.push_str("        emit PhysicalRedemptionRequested(id, msg.sender, amount);\n");
            source.push_str("        return id;\n");
            source.push_str("    }\n\n");
            source
                .push_str("    /// @notice Custodian confirms off-chain delivery for a request.\n");
            source.push_str("    function fulfillRedemption(uint256 id) external onlyOwner {\n");
            source.push_str("        require(id < redemptions.length, \"Commodity: bad id\");\n");
            source.push_str(
                "        require(!redemptions[id].fulfilled, \"Commodity: already fulfilled\");\n",
            );
            source.push_str("        redemptions[id].fulfilled = true;\n");
            source.push_str("        emit PhysicalRedemptionFulfilled(id);\n");
            source.push_str("    }\n\n");
        }
        if config.redemption.allows_cash() {
            source.push_str(
                "    /// @notice Issuer sets the per-token cash settlement price (wei).\n",
            );
            source.push_str(
                "    function setSettlementPrice(uint256 pricePerToken) external onlyOwner {\n",
            );
            source.push_str("        settlementPricePerToken = pricePerToken;\n");
            source.push_str("        emit SettlementPriceUpdated(pricePerToken);\n");
            source.push_str("    }\n\n");
            source.push_str("    /// @notice Fund the contract with cash for settlements.\n");
            source.push_str(
                "    function depositSettlementFunds() external payable onlyOwner {}\n\n",
            );
            source.push_str(
                "    /// @notice Burn tokens and receive cash settlement (pull payment).\n",
            );
            source.push_str(
                "    function redeemForCash(uint256 amount) external nonReentrant whenNotPaused {\n",
            );
            source.push_str("        require(amount > 0, \"Commodity: zero amount\");\n");
            source.push_str(
                "        require(settlementPricePerToken > 0, \"Commodity: price unset\");\n",
            );
            source.push_str("        uint256 payout = amount * settlementPricePerToken;\n");
            source.push_str(
                "        require(address(this).balance >= payout, \"Commodity: insufficient funds\");\n",
            );
            source.push_str(
                "        _burn(msg.sender, amount); // CEI: effects before interaction\n",
            );
            source.push_str("        emit CashRedeemed(msg.sender, amount, payout);\n");
            source.push_str(
                "        (bool success, ) = payable(msg.sender).call{value: payout}(\"\");\n",
            );
            source.push_str("        require(success, \"Commodity: payout failed\");\n");
            source.push_str("    }\n\n");
        }
    }
}
