//! Fractionalized-ownership (NFT vault) generator (Solidity / EVM).
//!
//! 🤖 Part of the `tokenization` module.

use super::{
    BASIS_POINTS_DENOMINATOR, FractionalOwnership, jurisdiction_compliance_tag, price_per_share,
};
use crate::{ChainError, ChainResult, ContractGenerator, GeneratedContract};

impl ContractGenerator {
    /// Emits the Solidity source for an NFT fractionalization vault.
    ///
    /// The generated contract escrows a single ERC-721, mints fungible fractions to
    /// the curator, and supports two unlock paths: a 100%-holder `redeemAll`, and
    /// (optionally) a reserve-price `buyout` whose proceeds are claimed pro-rata by
    /// fraction holders via pull payments.
    pub(crate) fn generate_solidity_fractional_ownership(
        &self,
        config: &FractionalOwnership,
    ) -> ChainResult<GeneratedContract> {
        if config.total_fractions == 0 {
            return Err(ChainError::GenerationError(
                "FractionalOwnership.total_fractions must be greater than zero".to_string(),
            ));
        }
        if u32::from(config.curator_fee_basis_points) > BASIS_POINTS_DENOMINATOR {
            return Err(ChainError::GenerationError(format!(
                "FractionalOwnership.curator_fee_basis_points must not exceed {BASIS_POINTS_DENOMINATOR}"
            )));
        }
        let implied_fraction_price = price_per_share(config.reserve_price, config.total_fractions)?;
        let compliance_tag = jurisdiction_compliance_tag(config.jurisdiction);

        let mut source = String::from("// SPDX-License-Identifier: MIT\n");
        source.push_str("pragma solidity ^0.8.20;\n\n");
        source.push_str("import \"@openzeppelin/contracts/token/ERC20/ERC20.sol\";\n");
        source.push_str("import \"@openzeppelin/contracts/token/ERC721/IERC721.sol\";\n");
        source
            .push_str("import \"@openzeppelin/contracts/token/ERC721/utils/ERC721Holder.sol\";\n");
        source.push_str("import \"@openzeppelin/contracts/access/Ownable2Step.sol\";\n");
        source.push_str("import \"@openzeppelin/contracts/utils/ReentrancyGuard.sol\";\n\n");

        // -- NatSpec header ----------------------------------------------------
        source.push_str(&format!("/// @title {}\n", config.name));
        source.push_str(&format!(
            "/// @notice Fractionalizes ERC-721 {} token #{} into {} fungible fractions.\n",
            config.underlying_nft, config.underlying_token_id, config.total_fractions
        ));
        source.push_str(&format!(
            "/// @notice Reserve price: {}; implied value per fraction: {}.\n",
            config.reserve_price, implied_fraction_price
        ));
        source.push_str(&format!(
            "/// @dev Compliance framework: {}. Generated by Legalis-Chain.\n",
            compliance_tag
        ));
        source.push_str("/// @dev Security Considerations:\n");
        source.push_str(
            "/// @dev  - ERC721Holder lets the vault custody the NFT; Ownable2Step for the curator.\n",
        );
        source.push_str(
            "/// @dev  - All asset moves use ReentrancyGuard and the CEI pattern (burn before send).\n",
        );
        source.push_str("/// @dev Gas Notes:\n");
        source.push_str(
            "/// @dev  - Buyout proceeds use a snapshot supply, so redemption stays O(1) per holder.\n\n",
        );

        // -- Contract declaration ---------------------------------------------
        source.push_str(&format!(
            "contract {} is ERC20, ERC721Holder, Ownable2Step, ReentrancyGuard {{\n",
            config.name
        ));

        // -- Constants & storage ----------------------------------------------
        source.push_str(&format!(
            "    /// @notice ERC-721 collection held by this vault.\n    IERC721 public immutable nft = IERC721({});\n",
            config.underlying_nft
        ));
        source.push_str(&format!(
            "    /// @notice Token id escrowed by this vault.\n    uint256 public constant TOKEN_ID = {};\n",
            config.underlying_token_id
        ));
        source.push_str(&format!(
            "    /// @notice Curator fee on buyout proceeds (basis points).\n    uint256 public constant CURATOR_FEE_BPS = {};\n",
            config.curator_fee_basis_points
        ));
        source.push_str(&format!(
            "    /// @notice Implied value of a single fraction at the reserve price.\n    uint256 public constant IMPLIED_FRACTION_PRICE = {};\n",
            implied_fraction_price
        ));
        source.push_str("    /// @notice Curator who deposited the NFT.\n");
        source.push_str("    address public curator;\n");
        source.push_str("    /// @notice Reserve (buyout) price in wei.\n");
        source.push_str("    uint256 public reservePrice;\n");
        source.push_str("    /// @notice Whether the NFT has been deposited into the vault.\n");
        source.push_str("    bool public active;\n");
        if config.buyout_enabled {
            source.push_str("    /// @notice Whether the vault has been bought out.\n");
            source.push_str("    bool public boughtOut;\n");
            source
                .push_str("    /// @notice Proceeds available to fraction holders post-buyout.\n");
            source.push_str("    uint256 public buyoutProceeds;\n");
            source.push_str("    /// @notice Fraction supply snapshotted at buyout.\n");
            source.push_str("    uint256 public fractionsAtBuyout;\n");
        }
        source.push('\n');

        // -- Events ------------------------------------------------------------
        source.push_str("    event VaultActivated(address indexed curator);\n");
        source.push_str("    event Redeemed(address indexed redeemer);\n");
        if config.buyout_enabled {
            source.push_str("    event BoughtOut(address indexed buyer, uint256 price);\n");
            source.push_str(
                "    event ProceedsRedeemed(address indexed holder, uint256 fractions, uint256 amount);\n",
            );
            source.push_str("    event ReservePriceUpdated(uint256 reservePrice);\n");
        }
        source.push('\n');

        // -- Constructor -------------------------------------------------------
        source.push_str(&format!(
            "    constructor() ERC20(\"{}\", \"{}\") Ownable(msg.sender) {{\n",
            config.name, config.symbol
        ));
        source.push_str("        curator = msg.sender;\n");
        source.push_str(&format!(
            "        reservePrice = {};\n",
            config.reserve_price
        ));
        source.push_str(&format!(
            "        _mint(msg.sender, {});\n",
            config.total_fractions
        ));
        source.push_str("    }\n\n");

        // -- Activation --------------------------------------------------------
        source.push_str(
            "    /// @notice Deposit the NFT into the vault (curator must approve first).\n",
        );
        source.push_str("    function activate() external onlyOwner {\n");
        source.push_str("        require(!active, \"Vault: already active\");\n");
        source.push_str("        active = true; // effects before interaction\n");
        source.push_str("        emit VaultActivated(msg.sender);\n");
        source.push_str("        nft.safeTransferFrom(msg.sender, address(this), TOKEN_ID);\n");
        source.push_str("    }\n\n");

        // -- 100% redemption ---------------------------------------------------
        source.push_str("    /// @notice A holder of all fractions reclaims the NFT.\n");
        source.push_str("    function redeemAll() external nonReentrant {\n");
        source.push_str("        require(active, \"Vault: inactive\");\n");
        if config.buyout_enabled {
            source.push_str("        require(!boughtOut, \"Vault: bought out\");\n");
        }
        source.push_str(
            "        require(balanceOf(msg.sender) == totalSupply(), \"Vault: need 100%\");\n",
        );
        source.push_str("        active = false;\n");
        source.push_str("        _burn(msg.sender, totalSupply());\n");
        source.push_str("        emit Redeemed(msg.sender);\n");
        source.push_str("        nft.safeTransferFrom(address(this), msg.sender, TOKEN_ID);\n");
        source.push_str("    }\n\n");

        // -- Buyout flow -------------------------------------------------------
        if config.buyout_enabled {
            self.push_fractional_buyout(&mut source);
        }

        source.push_str("}\n");

        Ok(GeneratedContract {
            name: config.name.clone(),
            source,
            platform: self.platform,
            abi: None,
            deployment_script: None,
        })
    }

    /// Appends the reserve-price buyout and proceeds-redemption functions.
    fn push_fractional_buyout(&self, source: &mut String) {
        source.push_str("    /// @notice Curator adjusts the reserve price before any buyout.\n");
        source.push_str("    function setReservePrice(uint256 newReserve) external onlyOwner {\n");
        source.push_str("        require(!boughtOut, \"Vault: bought out\");\n");
        source.push_str("        reservePrice = newReserve;\n");
        source.push_str("        emit ReservePriceUpdated(newReserve);\n");
        source.push_str("    }\n\n");
        source.push_str("    /// @notice Buy out the vault at or above the reserve price.\n");
        source.push_str("    function buyout() external payable nonReentrant {\n");
        source.push_str("        require(active, \"Vault: inactive\");\n");
        source.push_str("        require(!boughtOut, \"Vault: already bought out\");\n");
        source.push_str("        require(msg.value >= reservePrice, \"Vault: below reserve\");\n");
        source.push_str("        boughtOut = true; // effects before interactions\n");
        source.push_str("        fractionsAtBuyout = totalSupply();\n");
        source.push_str("        uint256 fee = (msg.value * CURATOR_FEE_BPS) / 10000;\n");
        source.push_str("        buyoutProceeds = msg.value - fee;\n");
        source.push_str("        emit BoughtOut(msg.sender, msg.value);\n");
        source.push_str("        nft.safeTransferFrom(address(this), msg.sender, TOKEN_ID);\n");
        source.push_str("        if (fee > 0) {\n");
        source
            .push_str("            (bool feePaid, ) = payable(curator).call{value: fee}(\"\");\n");
        source.push_str("            require(feePaid, \"Vault: fee transfer failed\");\n");
        source.push_str("        }\n");
        source.push_str("    }\n\n");
        source.push_str(
            "    /// @notice Redeem fractions for a pro-rata share of buyout proceeds.\n",
        );
        source.push_str("    function redeemProceeds() external nonReentrant {\n");
        source.push_str("        require(boughtOut, \"Vault: not bought out\");\n");
        source.push_str("        uint256 fractions = balanceOf(msg.sender);\n");
        source.push_str("        require(fractions > 0, \"Vault: no fractions\");\n");
        source.push_str(
            "        uint256 amount = (buyoutProceeds * fractions) / fractionsAtBuyout;\n",
        );
        source.push_str("        require(amount > 0, \"Vault: nothing to redeem\");\n");
        source.push_str("        _burn(msg.sender, fractions); // CEI: effects first\n");
        source.push_str("        emit ProceedsRedeemed(msg.sender, fractions, amount);\n");
        source.push_str(
            "        (bool success, ) = payable(msg.sender).call{value: amount}(\"\");\n",
        );
        source.push_str("        require(success, \"Vault: redeem failed\");\n");
        source.push_str("    }\n");
    }
}
