//! Intellectual-property NFT generator (Solidity / EVM).
//!
//! 🤖 Part of the `tokenization` module.

use super::{BASIS_POINTS_DENOMINATOR, IpNft, jurisdiction_compliance_tag};
use crate::{ChainError, ChainResult, ContractGenerator, GeneratedContract};

impl ContractGenerator {
    /// Emits the Solidity source for an intellectual-property NFT collection.
    ///
    /// The generated contract is an ERC-721 with ERC-721URIStorage metadata and
    /// EIP-2981 royalties. On-chain licensing, IP-term expiry and
    /// non-transferability (for non-assignable rights) are optional features.
    pub(crate) fn generate_solidity_ip_nft(
        &self,
        config: &IpNft,
    ) -> ChainResult<GeneratedContract> {
        if u32::from(config.royalty_basis_points) > BASIS_POINTS_DENOMINATOR {
            return Err(ChainError::GenerationError(format!(
                "IpNft.royalty_basis_points must not exceed {BASIS_POINTS_DENOMINATOR}"
            )));
        }
        let compliance_tag = jurisdiction_compliance_tag(config.jurisdiction);
        let asset_label = config.asset_type.label();
        let has_expiry = config.expiry_timestamp.is_some();

        let mut source = String::from("// SPDX-License-Identifier: MIT\n");
        source.push_str("pragma solidity ^0.8.20;\n\n");
        source.push_str("import \"@openzeppelin/contracts/token/ERC721/ERC721.sol\";\n");
        source.push_str(
            "import \"@openzeppelin/contracts/token/ERC721/extensions/ERC721URIStorage.sol\";\n",
        );
        source.push_str("import \"@openzeppelin/contracts/token/common/ERC2981.sol\";\n");
        source.push_str("import \"@openzeppelin/contracts/access/Ownable2Step.sol\";\n\n");

        // -- NatSpec header ----------------------------------------------------
        source.push_str(&format!("/// @title {}\n", config.name));
        source.push_str(&format!(
            "/// @notice Tokenized {} rights (registration {}).\n",
            asset_label, config.registration_number
        ));
        source.push_str(&format!(
            "/// @notice Secondary-sale royalty: {} bps (EIP-2981) to {}.\n",
            config.royalty_basis_points, config.royalty_receiver
        ));
        source.push_str(&format!(
            "/// @dev Compliance framework: {}. Generated by Legalis-Chain.\n",
            compliance_tag
        ));
        source.push_str("/// @dev Security Considerations:\n");
        source.push_str("/// @dev  - Ownable2Step guards minting and royalty configuration.\n");
        source.push_str("/// @dev  - Licensing checks ownerOf to prevent unauthorized grants.\n");
        if !config.transferable {
            source.push_str(
                "/// @dev  - Non-transferable: _update only permits minting and burning.\n",
            );
        }
        source.push_str("/// @dev Gas Notes:\n");
        source.push_str(
            "/// @dev  - License records are keyed mappings; no enumeration over licensees.\n\n",
        );

        // -- Contract declaration ---------------------------------------------
        source.push_str(&format!(
            "contract {} is ERC721, ERC721URIStorage, ERC2981, Ownable2Step {{\n",
            config.name
        ));
        source.push_str("    uint256 private _nextTokenId;\n\n");
        source.push_str(&format!(
            "    /// @notice Filing/registration number with the issuing authority.\n    string public constant REGISTRATION_NUMBER = \"{}\";\n",
            config.registration_number
        ));
        if let Some(expiry) = config.expiry_timestamp {
            source.push_str(&format!(
                "    /// @notice Unix timestamp at which the IP right expires.\n    uint256 public constant RIGHT_EXPIRY = {};\n",
                expiry
            ));
        }
        source.push('\n');

        // -- Licensing storage -------------------------------------------------
        if config.licensing_enabled {
            source.push_str("    /// @notice On-chain license record.\n");
            source.push_str("    struct License {\n");
            source.push_str("        uint256 validUntil;\n");
            source.push_str("        uint256 fee;\n");
            source.push_str("        bool active;\n");
            source.push_str("    }\n");
            source.push_str(
                "    /// @notice tokenId => licensee => license terms.\n    mapping(uint256 => mapping(address => License)) public licenses;\n\n",
            );
            source.push_str(
                "    event LicenseGranted(uint256 indexed tokenId, address indexed licensee, uint256 validUntil, uint256 fee);\n",
            );
            source.push_str(
                "    event LicenseRevoked(uint256 indexed tokenId, address indexed licensee);\n\n",
            );
        }
        source.push_str("    event IpMinted(uint256 indexed tokenId, address indexed to);\n\n");

        // -- Constructor -------------------------------------------------------
        source.push_str(&format!(
            "    constructor() ERC721(\"{}\", \"{}\") Ownable(msg.sender) {{\n",
            config.name, config.symbol
        ));
        source.push_str(&format!(
            "        _setDefaultRoyalty({}, {});\n",
            config.royalty_receiver, config.royalty_basis_points
        ));
        source.push_str("    }\n\n");

        // -- Mint --------------------------------------------------------------
        source.push_str("    /// @notice Mint a new IP token with metadata URI.\n");
        source.push_str(
            "    function mint(address to, string memory uri) external onlyOwner returns (uint256) {\n",
        );
        if has_expiry {
            source.push_str(
                "        require(block.timestamp < RIGHT_EXPIRY, \"IP: right expired\");\n",
            );
        }
        source.push_str("        uint256 tokenId = _nextTokenId++;\n");
        source.push_str("        _safeMint(to, tokenId);\n");
        source.push_str("        _setTokenURI(tokenId, uri);\n");
        source.push_str("        emit IpMinted(tokenId, to);\n");
        source.push_str("        return tokenId;\n");
        source.push_str("    }\n\n");

        // -- Royalty admin -----------------------------------------------------
        source.push_str("    /// @notice Update the default EIP-2981 royalty.\n");
        source.push_str(
            "    function setDefaultRoyalty(address receiver, uint96 feeNumerator) external onlyOwner {\n",
        );
        source.push_str("        _setDefaultRoyalty(receiver, feeNumerator);\n");
        source.push_str("    }\n\n");

        // -- Licensing ---------------------------------------------------------
        if config.licensing_enabled {
            self.push_ip_licensing(&mut source, has_expiry);
        }

        // -- Transfer restriction ---------------------------------------------
        if !config.transferable {
            source.push_str(
                "    /// @dev Non-assignable right: only minting and burning are permitted.\n",
            );
            source.push_str(
                "    function _update(address to, uint256 tokenId, address auth)\n        internal\n        override\n        returns (address)\n    {\n",
            );
            source.push_str("        address from = _ownerOf(tokenId);\n");
            source.push_str(
                "        require(from == address(0) || to == address(0), \"IP: non-transferable\");\n",
            );
            source.push_str("        return super._update(to, tokenId, auth);\n");
            source.push_str("    }\n\n");
        }

        // -- Required overrides ------------------------------------------------
        source.push_str("    function tokenURI(uint256 tokenId)\n        public\n        view\n        override(ERC721, ERC721URIStorage)\n        returns (string memory)\n    {\n");
        source.push_str("        return super.tokenURI(tokenId);\n");
        source.push_str("    }\n\n");
        source.push_str("    function supportsInterface(bytes4 interfaceId)\n        public\n        view\n        override(ERC721, ERC721URIStorage, ERC2981)\n        returns (bool)\n    {\n");
        source.push_str("        return super.supportsInterface(interfaceId);\n");
        source.push_str("    }\n");
        source.push_str("}\n");

        Ok(GeneratedContract {
            name: config.name.clone(),
            source,
            platform: self.platform,
            abi: None,
            deployment_script: None,
        })
    }

    /// Appends the licensing functions for an IP NFT.
    fn push_ip_licensing(&self, source: &mut String, has_expiry: bool) {
        source.push_str("    /// @notice Grant a time-bounded license over a token.\n");
        source.push_str(
            "    function grantLicense(uint256 tokenId, address licensee, uint256 validUntil, uint256 fee) external {\n",
        );
        source.push_str(
            "        require(ownerOf(tokenId) == msg.sender, \"IP: not token owner\");\n",
        );
        source.push_str("        require(licensee != address(0), \"IP: zero licensee\");\n");
        source.push_str(
            "        require(validUntil > block.timestamp, \"IP: validUntil in past\");\n",
        );
        if has_expiry {
            source.push_str(
                "        require(validUntil <= RIGHT_EXPIRY, \"IP: license outlives right\");\n",
            );
        }
        source.push_str(
            "        licenses[tokenId][licensee] = License({validUntil: validUntil, fee: fee, active: true});\n",
        );
        source.push_str("        emit LicenseGranted(tokenId, licensee, validUntil, fee);\n");
        source.push_str("    }\n\n");
        source.push_str("    /// @notice Revoke an active license.\n");
        source
            .push_str("    function revokeLicense(uint256 tokenId, address licensee) external {\n");
        source.push_str(
            "        require(ownerOf(tokenId) == msg.sender, \"IP: not token owner\");\n",
        );
        source.push_str("        licenses[tokenId][licensee].active = false;\n");
        source.push_str("        emit LicenseRevoked(tokenId, licensee);\n");
        source.push_str("    }\n\n");
        source.push_str("    /// @notice Whether an address currently holds a valid license.\n");
        source.push_str(
            "    function isLicensed(uint256 tokenId, address who) external view returns (bool) {\n",
        );
        source.push_str("        License memory lic = licenses[tokenId][who];\n");
        source.push_str("        return lic.active && block.timestamp <= lic.validUntil;\n");
        source.push_str("    }\n\n");
    }
}
