//! Real-estate tokenization generator (Solidity / EVM).
//!
//! 🤖 Part of the `tokenization` module.

use super::{RealEstateToken, jurisdiction_compliance_tag, price_per_share};
use crate::{ChainError, ChainResult, ContractGenerator, GeneratedContract};

impl ContractGenerator {
    /// Emits the Solidity source for a fractional real-estate security token.
    ///
    /// The generated contract is an ERC-20 share token with two-step ownership,
    /// pause control, KYC gating, regulatory transfer lock-ups and a pull-based
    /// rental-income distributor implemented with the magnified-dividend-per-share
    /// accounting pattern (no unbounded loops, dust-free pro-rata accrual).
    pub(crate) fn generate_solidity_real_estate_token(
        &self,
        config: &RealEstateToken,
    ) -> ChainResult<GeneratedContract> {
        if config.total_shares == 0 {
            return Err(ChainError::GenerationError(
                "RealEstateToken.total_shares must be greater than zero".to_string(),
            ));
        }
        let unit_price = price_per_share(config.appraised_value, config.total_shares)?;
        let compliance_tag = jurisdiction_compliance_tag(config.jurisdiction);
        let uses_erc20_dividend = config.dividend_token.is_some();
        let lockup_seconds = u64::from(config.transfer_lockup_days) * 86_400;

        let mut source = String::from("// SPDX-License-Identifier: MIT\n");
        source.push_str("pragma solidity ^0.8.20;\n\n");
        source.push_str("import \"@openzeppelin/contracts/token/ERC20/ERC20.sol\";\n");
        source.push_str("import \"@openzeppelin/contracts/access/Ownable2Step.sol\";\n");
        source.push_str("import \"@openzeppelin/contracts/utils/Pausable.sol\";\n");
        source.push_str("import \"@openzeppelin/contracts/utils/ReentrancyGuard.sol\";\n");
        source.push_str("import \"@openzeppelin/contracts/utils/math/SafeCast.sol\";\n");
        if uses_erc20_dividend {
            source.push_str("import \"@openzeppelin/contracts/token/ERC20/IERC20.sol\";\n");
            source
                .push_str("import \"@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol\";\n");
        }
        source.push('\n');

        // -- NatSpec header ----------------------------------------------------
        source.push_str(&format!("/// @title {}\n", config.name));
        source.push_str(&format!(
            "/// @notice Fractional ownership security token for a {} property ({}).\n",
            config.property_type.label(),
            config.property_identifier
        ));
        source.push_str(&format!(
            "/// @notice Appraised value: {} (reference units); {} total shares; {} per share.\n",
            config.appraised_value, config.total_shares, unit_price
        ));
        source.push_str(&format!(
            "/// @dev Compliance framework: {}. Generated by Legalis-Chain.\n",
            compliance_tag
        ));
        source.push_str("/// @dev Security Considerations:\n");
        source.push_str("/// @dev  - Ownable2Step prevents accidental ownership loss.\n");
        source.push_str(
            "/// @dev  - Pull-payment dividends + ReentrancyGuard follow the CEI pattern.\n",
        );
        source.push_str(
            "/// @dev  - Transfers are gated by KYC and lock-up checks in _update (one hook).\n",
        );
        source.push_str("/// @dev Gas Notes:\n");
        source.push_str(
            "/// @dev  - Dividend accrual is O(1): magnifiedDividendPerShare avoids per-holder loops.\n",
        );
        source.push_str(
            "/// @dev  - SafeCast guards int<->uint conversions without unchecked arithmetic.\n\n",
        );

        // -- Contract declaration ---------------------------------------------
        source.push_str(&format!(
            "contract {} is ERC20, Ownable2Step, Pausable, ReentrancyGuard {{\n",
            config.name
        ));
        source.push_str("    using SafeCast for uint256;\n");
        source.push_str("    using SafeCast for int256;\n");
        if uses_erc20_dividend {
            source.push_str("    using SafeERC20 for IERC20;\n");
        }
        source.push('\n');

        // -- Constants & storage ----------------------------------------------
        source.push_str("    /// @notice Magnitude used to retain dividend precision.\n");
        source.push_str("    uint256 internal constant MAGNITUDE = 2**128;\n\n");
        source.push_str(&format!(
            "    /// @notice Legal identifier of the underlying property.\n    string public constant PROPERTY_IDENTIFIER = \"{}\";\n",
            config.property_identifier
        ));
        source.push_str(&format!(
            "    /// @notice Appraised property value in reference units.\n    uint256 public constant APPRAISED_VALUE = {};\n",
            config.appraised_value
        ));
        source.push_str(&format!(
            "    /// @notice Indivisible price of a single share.\n    uint256 public constant PRICE_PER_SHARE = {};\n",
            unit_price
        ));
        if lockup_seconds > 0 {
            source.push_str(&format!(
                "    /// @notice Regulatory transfer lock-up applied on each acquisition.\n    uint256 public constant TRANSFER_LOCKUP = {} seconds;\n",
                lockup_seconds
            ));
        }
        source.push('\n');
        if let Some(token) = &config.dividend_token {
            source.push_str(&format!(
                "    /// @notice ERC-20 token used to pay rental dividends.\n    IERC20 public immutable dividendToken = IERC20({});\n\n",
                token
            ));
        }
        source.push_str("    uint256 internal magnifiedDividendPerShare;\n");
        source.push_str("    mapping(address => int256) internal magnifiedDividendCorrections;\n");
        source.push_str("    mapping(address => uint256) internal withdrawnDividends;\n");
        source.push_str("    /// @notice Cumulative rental income ever distributed.\n");
        source.push_str("    uint256 public totalDividendsDistributed;\n");
        if config.kyc_required {
            source.push_str("    /// @notice KYC approval registry.\n");
            source.push_str("    mapping(address => bool) public kycApproved;\n");
        }
        if lockup_seconds > 0 {
            source.push_str("    /// @notice Timestamp until which an address may not transfer.\n");
            source.push_str("    mapping(address => uint256) public lockupExpiry;\n");
        }
        source.push('\n');

        // -- Events ------------------------------------------------------------
        source.push_str("    event RentalIncomeDistributed(uint256 amount);\n");
        source.push_str("    event DividendWithdrawn(address indexed holder, uint256 amount);\n");
        if config.kyc_required {
            source
                .push_str("    event KycStatusChanged(address indexed account, bool approved);\n");
        }
        source.push('\n');

        // -- Constructor -------------------------------------------------------
        source.push_str(&format!(
            "    constructor() ERC20(\"{}\", \"{}\") Ownable(msg.sender) {{\n",
            config.name, config.symbol
        ));
        if config.kyc_required {
            source.push_str("        kycApproved[msg.sender] = true;\n");
        }
        source.push_str(&format!(
            "        _mint(msg.sender, {});\n",
            config.total_shares
        ));
        source.push_str("    }\n\n");
        source.push_str("    /// @dev Shares are indivisible (1 share == 1 token unit).\n");
        source.push_str("    function decimals() public pure override returns (uint8) {\n");
        source.push_str("        return 0;\n");
        source.push_str("    }\n\n");

        // -- Compliance admin --------------------------------------------------
        if config.kyc_required {
            source.push_str("    /// @notice Approve or revoke KYC status for an account.\n");
            source.push_str(
                "    function setKycStatus(address account, bool approved) external onlyOwner {\n",
            );
            source.push_str("        kycApproved[account] = approved;\n");
            source.push_str("        emit KycStatusChanged(account, approved);\n");
            source.push_str("    }\n\n");
        }
        source.push_str("    /// @notice Pause all transfers (regulatory circuit breaker).\n");
        source.push_str("    function pause() external onlyOwner {\n");
        source.push_str("        _pause();\n");
        source.push_str("    }\n\n");
        source.push_str("    /// @notice Resume transfers.\n");
        source.push_str("    function unpause() external onlyOwner {\n");
        source.push_str("        _unpause();\n");
        source.push_str("    }\n\n");

        // -- Rental income distribution (pull payments) ------------------------
        self.push_real_estate_dividends(&mut source, config);

        // -- Transfer hook (compliance + dividend bookkeeping) -----------------
        source.push_str(
            "    /// @dev Single ERC-20 hook: enforces compliance then keeps dividend math exact.\n",
        );
        source.push_str(
            "    function _update(address from, address to, uint256 value) internal override whenNotPaused {\n",
        );
        source.push_str("        if (from != address(0) && to != address(0)) {\n");
        if lockup_seconds > 0 {
            source.push_str(
                "            require(block.timestamp >= lockupExpiry[from], \"RealEstate: sender in lock-up\");\n",
            );
        }
        if config.kyc_required {
            source.push_str(
                "            require(kycApproved[to], \"RealEstate: recipient not KYC-approved\");\n",
            );
        }
        source.push_str("        }\n");
        source.push_str("        super._update(from, to, value);\n");
        source.push_str(
            "        // CEI pattern: dividend corrections use the transferred value, not balances.\n",
        );
        source.push_str(
            "        int256 magCorrection = (magnifiedDividendPerShare * value).toInt256();\n",
        );
        source.push_str("        if (from != address(0)) {\n");
        source.push_str("            magnifiedDividendCorrections[from] += magCorrection;\n");
        source.push_str("        }\n");
        source.push_str("        if (to != address(0)) {\n");
        source.push_str("            magnifiedDividendCorrections[to] -= magCorrection;\n");
        if lockup_seconds > 0 {
            source.push_str("            lockupExpiry[to] = block.timestamp + TRANSFER_LOCKUP;\n");
        }
        source.push_str("        }\n");
        source.push_str("    }\n");
        source.push_str("}\n");

        Ok(GeneratedContract {
            name: config.name.clone(),
            source,
            platform: self.platform,
            abi: None,
            deployment_script: None,
        })
    }

    /// Appends the rental-income distribution and dividend-view functions.
    fn push_real_estate_dividends(&self, source: &mut String, config: &RealEstateToken) {
        if !config.rental_income_enabled {
            return;
        }
        let uses_erc20_dividend = config.dividend_token.is_some();
        source.push_str("    /// @notice Distribute rental income pro-rata to all shareholders.\n");
        if uses_erc20_dividend {
            source.push_str(
                "    function distributeRentalIncome(uint256 amount) external onlyOwner {\n",
            );
            source.push_str("        require(totalSupply() > 0, \"RealEstate: no shares\");\n");
            source.push_str("        require(amount > 0, \"RealEstate: zero amount\");\n");
            source.push_str(
                "        dividendToken.safeTransferFrom(msg.sender, address(this), amount);\n",
            );
            source.push_str(
                "        magnifiedDividendPerShare += (amount * MAGNITUDE) / totalSupply();\n",
            );
            source.push_str("        totalDividendsDistributed += amount;\n");
            source.push_str("        emit RentalIncomeDistributed(amount);\n");
            source.push_str("    }\n\n");
        } else {
            source.push_str("    function distributeRentalIncome() external payable onlyOwner {\n");
            source.push_str("        require(totalSupply() > 0, \"RealEstate: no shares\");\n");
            source.push_str("        require(msg.value > 0, \"RealEstate: zero amount\");\n");
            source.push_str(
                "        magnifiedDividendPerShare += (msg.value * MAGNITUDE) / totalSupply();\n",
            );
            source.push_str("        totalDividendsDistributed += msg.value;\n");
            source.push_str("        emit RentalIncomeDistributed(msg.value);\n");
            source.push_str("    }\n\n");
        }

        source.push_str("    /// @notice Lifetime dividends accrued to an account.\n");
        source.push_str(
            "    function accumulativeDividendOf(address account) public view returns (uint256) {\n",
        );
        source.push_str(
            "        int256 cumulative = (magnifiedDividendPerShare * balanceOf(account)).toInt256()\n",
        );
        source.push_str("            + magnifiedDividendCorrections[account];\n");
        source.push_str("        return cumulative.toUint256() / MAGNITUDE;\n");
        source.push_str("    }\n\n");
        source.push_str("    /// @notice Dividends an account can withdraw right now.\n");
        source.push_str(
            "    function withdrawableDividendOf(address account) public view returns (uint256) {\n",
        );
        source.push_str(
            "        return accumulativeDividendOf(account) - withdrawnDividends[account];\n",
        );
        source.push_str("    }\n\n");
        source.push_str("    /// @notice Withdraw accrued rental income (pull payment).\n");
        source.push_str("    function withdrawDividend() external nonReentrant {\n");
        source.push_str("        uint256 amount = withdrawableDividendOf(msg.sender);\n");
        source.push_str("        require(amount > 0, \"RealEstate: nothing to withdraw\");\n");
        source.push_str(
            "        withdrawnDividends[msg.sender] += amount; // effects before interaction\n",
        );
        source.push_str("        emit DividendWithdrawn(msg.sender, amount);\n");
        if uses_erc20_dividend {
            source.push_str("        dividendToken.safeTransfer(msg.sender, amount);\n");
        } else {
            source.push_str(
                "        (bool success, ) = payable(msg.sender).call{value: amount}(\"\");\n",
            );
            source.push_str("        require(success, \"RealEstate: transfer failed\");\n");
        }
        source.push_str("    }\n\n");
    }
}
