//! Revenue-sharing generator (Solidity / EVM).
//!
//! 🤖 Part of the `tokenization` module.

use super::{
    RevenueShareContract, distribute_revenue, jurisdiction_compliance_tag,
    validate_ownership_allocations,
};
use crate::{ChainResult, ContractGenerator, GeneratedContract};

/// Sample total used to embed a worked distribution example in generated source.
const EXAMPLE_REVENUE_UNITS: u128 = 1_000_000;

impl ContractGenerator {
    /// Emits the Solidity source for a pull-payment revenue-sharing splitter.
    ///
    /// Allocations are validated to sum to 100% before any source is produced, and
    /// the on-chain accounting recomputes each payee's entitlement from the
    /// cumulative received amount (the PaymentSplitter pattern), which is dust-free
    /// across an unbounded number of deposits.
    pub(crate) fn generate_solidity_revenue_share(
        &self,
        config: &RevenueShareContract,
    ) -> ChainResult<GeneratedContract> {
        validate_ownership_allocations(&config.allocations)?;
        let compliance_tag = jurisdiction_compliance_tag(config.jurisdiction);
        let uses_erc20 = config.payment_token.is_some();
        // Exercise the apportionment math up-front so the generated documentation
        // reflects exactly what the contract will pay out.
        let example = distribute_revenue(EXAMPLE_REVENUE_UNITS, &config.allocations)?;

        let mut source = String::from("// SPDX-License-Identifier: MIT\n");
        source.push_str("pragma solidity ^0.8.20;\n\n");
        source.push_str("import \"@openzeppelin/contracts/utils/ReentrancyGuard.sol\";\n");
        if uses_erc20 {
            source.push_str("import \"@openzeppelin/contracts/token/ERC20/IERC20.sol\";\n");
            source
                .push_str("import \"@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol\";\n");
        }
        source.push('\n');

        // -- NatSpec header ----------------------------------------------------
        source.push_str(&format!("/// @title {}\n", config.name));
        source.push_str(&format!(
            "/// @notice Revenue-sharing splitter across {} payees (distribution {}).\n",
            config.allocations.len(),
            config.distribution_frequency.label()
        ));
        source.push_str(&format!(
            "/// @dev Compliance framework: {}. Generated by Legalis-Chain.\n",
            compliance_tag
        ));
        source.push_str(&format!(
            "/// @dev Worked example: distributing {EXAMPLE_REVENUE_UNITS} units yields:\n"
        ));
        for entry in &example {
            source.push_str(&format!(
                "/// @dev   - {}: {}\n",
                entry.holder, entry.amount
            ));
        }
        source.push_str("/// @dev Security Considerations:\n");
        source.push_str(
            "/// @dev  - Pull payments + ReentrancyGuard + CEI prevent reentrancy on payout.\n",
        );
        source.push_str(
            "/// @dev  - Entitlements are derived from cumulative receipts, so no dust is stranded.\n",
        );
        source.push_str("/// @dev Gas Notes:\n");
        if config.pull_payments {
            source.push_str(
                "/// @dev  - release() touches only the caller's accounting (O(1) per payee).\n\n",
            );
        } else {
            source.push_str(
                "/// @dev  - distributeAll() iterates a fixed, construction-time payee set.\n\n",
            );
        }

        // -- Contract declaration ---------------------------------------------
        source.push_str(&format!("contract {} is ReentrancyGuard {{\n", config.name));
        if uses_erc20 {
            source.push_str("    using SafeERC20 for IERC20;\n\n");
        }

        // -- Constants & storage ----------------------------------------------
        source.push_str("    uint256 public constant TOTAL_BASIS_POINTS = 10000;\n");
        source.push_str(&format!(
            "    /// @notice Minimum seconds between distribution epochs ({}).\n    uint256 public constant DISTRIBUTION_PERIOD = {} seconds;\n",
            config.distribution_frequency.label(),
            config.distribution_frequency.period_seconds()
        ));
        if let Some(token) = &config.payment_token {
            source.push_str(&format!(
                "    /// @notice ERC-20 token distributed by this splitter.\n    IERC20 public immutable paymentToken = IERC20({});\n",
                token
            ));
        }
        source.push_str("    address[] public shareholders;\n");
        source.push_str("    mapping(address => uint256) public basisPoints;\n");
        source.push_str("    mapping(address => uint256) public released;\n");
        source.push_str("    uint256 public totalReleased;\n\n");

        // -- Events ------------------------------------------------------------
        source.push_str("    event PaymentReceived(address indexed from, uint256 amount);\n");
        source.push_str("    event PaymentReleased(address indexed to, uint256 amount);\n\n");

        // -- Constructor (bakes in the validated allocation) -------------------
        source.push_str("    constructor() {\n");
        source.push_str("        uint256 sum;\n");
        for allocation in &config.allocations {
            source.push_str(&format!(
                "        _addShareholder({}, {});\n",
                allocation.holder, allocation.basis_points
            ));
        }
        for allocation in &config.allocations {
            source.push_str(&format!("        sum += {};\n", allocation.basis_points));
        }
        source.push_str(
            "        require(sum == TOTAL_BASIS_POINTS, \"RevShare: invalid allocation\");\n",
        );
        source.push_str("    }\n\n");
        source.push_str("    function _addShareholder(address account, uint256 bps) private {\n");
        source.push_str("        require(account != address(0), \"RevShare: zero payee\");\n");
        source.push_str(
            "        require(basisPoints[account] == 0, \"RevShare: duplicate payee\");\n",
        );
        source.push_str("        shareholders.push(account);\n");
        source.push_str("        basisPoints[account] = bps;\n");
        source.push_str("    }\n\n");
        source.push_str("    /// @notice Number of payees.\n");
        source.push_str("    function shareholderCount() external view returns (uint256) {\n");
        source.push_str("        return shareholders.length;\n");
        source.push_str("    }\n\n");

        // -- Income reception --------------------------------------------------
        if !uses_erc20 {
            source.push_str("    receive() external payable {\n");
            source.push_str("        emit PaymentReceived(msg.sender, msg.value);\n");
            source.push_str("    }\n\n");
        }

        // -- Entitlement view --------------------------------------------------
        source.push_str("    /// @notice Amount currently releasable to an account.\n");
        source.push_str(
            "    function pendingPayment(address account) public view returns (uint256) {\n",
        );
        if uses_erc20 {
            source.push_str(
                "        uint256 totalReceived = paymentToken.balanceOf(address(this)) + totalReleased;\n",
            );
        } else {
            source.push_str(
                "        uint256 totalReceived = address(this).balance + totalReleased;\n",
            );
        }
        source.push_str(
            "        return (totalReceived * basisPoints[account]) / TOTAL_BASIS_POINTS - released[account];\n",
        );
        source.push_str("    }\n\n");

        // -- Distribution ------------------------------------------------------
        if config.pull_payments {
            self.push_revenue_pull(&mut source, uses_erc20);
        } else {
            self.push_revenue_push(&mut source, uses_erc20);
        }

        source.push_str("}\n");

        Ok(GeneratedContract {
            name: config.name.clone(),
            source,
            platform: self.platform,
            abi: None,
            deployment_script: None,
        })
    }

    /// Appends the pull-payment `release` function.
    fn push_revenue_pull(&self, source: &mut String, uses_erc20: bool) {
        source
            .push_str("    /// @notice Release the caller-specified payee's entitlement (pull).\n");
        source.push_str("    function release(address account) external nonReentrant {\n");
        source.push_str("        require(basisPoints[account] > 0, \"RevShare: not a payee\");\n");
        source.push_str("        uint256 payment = pendingPayment(account);\n");
        source.push_str("        require(payment > 0, \"RevShare: nothing due\");\n");
        source.push_str("        released[account] += payment; // CEI: effects first\n");
        source.push_str("        totalReleased += payment;\n");
        source.push_str("        emit PaymentReleased(account, payment);\n");
        if uses_erc20 {
            source.push_str("        paymentToken.safeTransfer(account, payment);\n");
        } else {
            source.push_str(
                "        (bool success, ) = payable(account).call{value: payment}(\"\");\n",
            );
            source.push_str("        require(success, \"RevShare: transfer failed\");\n");
        }
        source.push_str("    }\n");
    }

    /// Appends the push-payment `distributeAll` function over the fixed payee set.
    fn push_revenue_push(&self, source: &mut String, uses_erc20: bool) {
        source.push_str("    /// @notice Distribute to every payee in one call (push).\n");
        source.push_str("    function distributeAll() external nonReentrant {\n");
        source.push_str("        uint256 count = shareholders.length;\n");
        source.push_str("        for (uint256 i = 0; i < count; i++) {\n");
        source.push_str("            address account = shareholders[i];\n");
        source.push_str("            uint256 payment = pendingPayment(account);\n");
        source.push_str("            if (payment == 0) {\n");
        source.push_str("                continue;\n");
        source.push_str("            }\n");
        source.push_str("            released[account] += payment; // CEI: effects first\n");
        source.push_str("            totalReleased += payment;\n");
        source.push_str("            emit PaymentReleased(account, payment);\n");
        if uses_erc20 {
            source.push_str("            paymentToken.safeTransfer(account, payment);\n");
        } else {
            source.push_str(
                "            (bool success, ) = payable(account).call{value: payment}(\"\");\n",
            );
            source.push_str("            require(success, \"RevShare: transfer failed\");\n");
        }
        source.push_str("        }\n");
        source.push_str("    }\n");
    }
}
