# coding: utf-8

# flake8: noqa

"""
    Legalis API

    REST API for the Legalis-RS legal framework. Provides CRUD operations for statutes, verification, and simulation endpoints.

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "0.2.0"

# Define package exports
__all__ = [
    "HealthApi",
    "MetricsApi",
    "SimulationApi",
    "StatutesApi",
    "VerificationApi",
    "VisualizationApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "CreateStatute201Response",
    "CreateStatuteRequest",
    "ErrorResponse",
    "HealthCheck200Response",
    "SaveSimulationRequest",
    "SavedSimulation",
    "SimulationRequest",
    "SimulationResponse",
    "Statute",
    "StatuteEffect",
    "StatuteListResponse",
    "StatuteListResponseData",
    "StatuteSummary",
    "VerifyRequest",
    "VerifyResponse",
    "VerifyStatutes200Response",
    "VisualizationResponse",
]

# import apis into sdk package
from legalis_client.api.health_api import HealthApi as HealthApi
from legalis_client.api.metrics_api import MetricsApi as MetricsApi
from legalis_client.api.simulation_api import SimulationApi as SimulationApi
from legalis_client.api.statutes_api import StatutesApi as StatutesApi
from legalis_client.api.verification_api import VerificationApi as VerificationApi
from legalis_client.api.visualization_api import VisualizationApi as VisualizationApi

# import ApiClient
from legalis_client.api_response import ApiResponse as ApiResponse
from legalis_client.api_client import ApiClient as ApiClient
from legalis_client.configuration import Configuration as Configuration
from legalis_client.exceptions import OpenApiException as OpenApiException
from legalis_client.exceptions import ApiTypeError as ApiTypeError
from legalis_client.exceptions import ApiValueError as ApiValueError
from legalis_client.exceptions import ApiKeyError as ApiKeyError
from legalis_client.exceptions import ApiAttributeError as ApiAttributeError
from legalis_client.exceptions import ApiException as ApiException

# import models into sdk package
from legalis_client.models.create_statute201_response import CreateStatute201Response as CreateStatute201Response
from legalis_client.models.create_statute_request import CreateStatuteRequest as CreateStatuteRequest
from legalis_client.models.error_response import ErrorResponse as ErrorResponse
from legalis_client.models.health_check200_response import HealthCheck200Response as HealthCheck200Response
from legalis_client.models.save_simulation_request import SaveSimulationRequest as SaveSimulationRequest
from legalis_client.models.saved_simulation import SavedSimulation as SavedSimulation
from legalis_client.models.simulation_request import SimulationRequest as SimulationRequest
from legalis_client.models.simulation_response import SimulationResponse as SimulationResponse
from legalis_client.models.statute import Statute as Statute
from legalis_client.models.statute_effect import StatuteEffect as StatuteEffect
from legalis_client.models.statute_list_response import StatuteListResponse as StatuteListResponse
from legalis_client.models.statute_list_response_data import StatuteListResponseData as StatuteListResponseData
from legalis_client.models.statute_summary import StatuteSummary as StatuteSummary
from legalis_client.models.verify_request import VerifyRequest as VerifyRequest
from legalis_client.models.verify_response import VerifyResponse as VerifyResponse
from legalis_client.models.verify_statutes200_response import VerifyStatutes200Response as VerifyStatutes200Response
from legalis_client.models.visualization_response import VisualizationResponse as VisualizationResponse

