# coding: utf-8

# flake8: noqa
"""
    Legalis API

    REST API for the Legalis-RS legal framework. Provides CRUD operations for statutes, verification, and simulation endpoints.

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from legalis_client.models.create_statute201_response import CreateStatute201Response
from legalis_client.models.create_statute_request import CreateStatuteRequest
from legalis_client.models.error_response import ErrorResponse
from legalis_client.models.health_check200_response import HealthCheck200Response
from legalis_client.models.save_simulation_request import SaveSimulationRequest
from legalis_client.models.saved_simulation import SavedSimulation
from legalis_client.models.simulation_request import SimulationRequest
from legalis_client.models.simulation_response import SimulationResponse
from legalis_client.models.statute import Statute
from legalis_client.models.statute_effect import StatuteEffect
from legalis_client.models.statute_list_response import StatuteListResponse
from legalis_client.models.statute_list_response_data import StatuteListResponseData
from legalis_client.models.statute_summary import StatuteSummary
from legalis_client.models.verify_request import VerifyRequest
from legalis_client.models.verify_response import VerifyResponse
from legalis_client.models.verify_statutes200_response import VerifyStatutes200Response
from legalis_client.models.visualization_response import VisualizationResponse

