# coding: utf-8

"""
    Legalis API

    REST API for the Legalis-RS legal framework. Provides CRUD operations for statutes, verification, and simulation endpoints.

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class SavedSimulation(BaseModel):
    """
    SavedSimulation
    """ # noqa: E501
    created_at: datetime
    created_by: StrictStr = Field(description="Username of creator")
    description: Optional[StrictStr] = Field(default=None, description="Optional description")
    deterministic_outcomes: Optional[StrictInt] = Field(default=None, description="Number of deterministic outcomes")
    deterministic_rate: Union[StrictFloat, StrictInt]
    discretionary_outcomes: Optional[StrictInt] = Field(default=None, description="Number of discretionary outcomes")
    discretionary_rate: Union[StrictFloat, StrictInt]
    id: StrictStr = Field(description="Unique saved simulation identifier")
    name: StrictStr = Field(description="User-provided name for the simulation")
    population_size: StrictInt = Field(description="Population size")
    statute_ids: Optional[List[StrictStr]] = Field(default=None, description="Statute IDs used in simulation")
    void_outcomes: Optional[StrictInt] = Field(default=None, description="Number of void outcomes")
    void_rate: Union[StrictFloat, StrictInt]
    __properties: ClassVar[List[str]] = ["created_at", "created_by", "description", "deterministic_outcomes", "deterministic_rate", "discretionary_outcomes", "discretionary_rate", "id", "name", "population_size", "statute_ids", "void_outcomes", "void_rate"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SavedSimulation from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SavedSimulation from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "created_at": obj.get("created_at"),
            "created_by": obj.get("created_by"),
            "description": obj.get("description"),
            "deterministic_outcomes": obj.get("deterministic_outcomes"),
            "deterministic_rate": obj.get("deterministic_rate"),
            "discretionary_outcomes": obj.get("discretionary_outcomes"),
            "discretionary_rate": obj.get("discretionary_rate"),
            "id": obj.get("id"),
            "name": obj.get("name"),
            "population_size": obj.get("population_size"),
            "statute_ids": obj.get("statute_ids"),
            "void_outcomes": obj.get("void_outcomes"),
            "void_rate": obj.get("void_rate")
        })
        return _obj


