# coding: utf-8

"""
    Legalis API

    REST API for the Legalis-RS legal framework. Provides CRUD operations for statutes, verification, and simulation endpoints.

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from legalis_client.models.statute_effect import StatuteEffect
from typing import Optional, Set
from typing_extensions import Self

class Statute(BaseModel):
    """
    Statute
    """ # noqa: E501
    amendments: Optional[List[Dict[str, Any]]] = Field(default=None, description="Amendment history")
    discretion_logic: Optional[StrictStr] = Field(default=None, description="Description of discretionary logic")
    effect: StatuteEffect
    id: StrictStr = Field(description="Unique identifier")
    jurisdiction: Optional[StrictStr] = Field(default=None, description="Jurisdiction identifier")
    preconditions: List[Dict[str, Any]] = Field(description="List of preconditions (If clauses)")
    relations: Optional[List[Dict[str, Any]]] = Field(default=None, description="Hierarchical relationships to other statutes")
    temporal_validity: Optional[Dict[str, Any]] = Field(default=None, description="Temporal validity constraints")
    title: StrictStr = Field(description="Title of the statute")
    version: Annotated[int, Field(strict=True, ge=1)] = Field(description="Version number")
    __properties: ClassVar[List[str]] = ["amendments", "discretion_logic", "effect", "id", "jurisdiction", "preconditions", "relations", "temporal_validity", "title", "version"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Statute from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of effect
        if self.effect:
            _dict['effect'] = self.effect.to_dict()
        # set to None if discretion_logic (nullable) is None
        # and model_fields_set contains the field
        if self.discretion_logic is None and "discretion_logic" in self.model_fields_set:
            _dict['discretion_logic'] = None

        # set to None if jurisdiction (nullable) is None
        # and model_fields_set contains the field
        if self.jurisdiction is None and "jurisdiction" in self.model_fields_set:
            _dict['jurisdiction'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Statute from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "amendments": obj.get("amendments"),
            "discretion_logic": obj.get("discretion_logic"),
            "effect": StatuteEffect.from_dict(obj["effect"]) if obj.get("effect") is not None else None,
            "id": obj.get("id"),
            "jurisdiction": obj.get("jurisdiction"),
            "preconditions": obj.get("preconditions"),
            "relations": obj.get("relations"),
            "temporal_validity": obj.get("temporal_validity"),
            "title": obj.get("title"),
            "version": obj.get("version")
        })
        return _obj


