//! Vietnamese Cybersecurity Law 2018 (Luật An ninh mạng 2018) - Law No. 24/2018/QH14
//!
//! Vietnam's law on cybersecurity and data protection, effective from January 1, 2019.
//!
//! ## Key Requirements
//!
//! - **Data localization** (Article 26): Domestic companies and foreign entities must
//!   store user data on servers located in Vietnam
//! - **Content removal** (Article 16): Remove prohibited content within 24 hours
//! - **Government access** (Article 26.4): Provide data to authorities when requested
//! - **Local presence** (Article 26.7): Foreign entities must establish presence in Vietnam
//!
//! ## Prohibited Content (Article 8)
//!
//! - Opposition to the Socialist Republic of Vietnam
//! - National security threats
//! - Fake news and misinformation
//! - Obscene or violent content

use serde::{Deserialize, Serialize};
use thiserror::Error;

/// Types of entities subject to cybersecurity law (Chủ thể chịu sự điều chỉnh)
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum CybersecurityEntity {
    /// Domestic enterprise (Doanh nghiệp trong nước)
    DomesticEnterprise,
    /// Foreign enterprise operating in Vietnam (Doanh nghiệp nước ngoài hoạt động tại VN)
    ForeignEnterprise,
    /// Telecommunications provider (Doanh nghiệp viễn thông)
    TelecomProvider,
    /// Internet service provider (Doanh nghiệp dịch vụ Internet)
    InternetServiceProvider,
    /// Social media platform (Mạng xã hội)
    SocialMediaPlatform,
    /// E-commerce platform (Thương mại điện tử)
    EcommercePlatform,
    /// Online game provider (Trò chơi trực tuyến)
    OnlineGameProvider,
    /// Other digital services
    Other(String),
}

impl CybersecurityEntity {
    /// Get Vietnamese name
    pub fn name_vi(&self) -> String {
        match self {
            Self::DomesticEnterprise => "Doanh nghiệp trong nước".to_string(),
            Self::ForeignEnterprise => "Doanh nghiệp nước ngoài".to_string(),
            Self::TelecomProvider => "Doanh nghiệp viễn thông".to_string(),
            Self::InternetServiceProvider => "Nhà cung cấp dịch vụ Internet".to_string(),
            Self::SocialMediaPlatform => "Mạng xã hội".to_string(),
            Self::EcommercePlatform => "Sàn thương mại điện tử".to_string(),
            Self::OnlineGameProvider => "Nhà cung cấp trò chơi trực tuyến".to_string(),
            Self::Other(name) => name.clone(),
        }
    }

    /// Check if requires data localization (Article 26)
    pub fn requires_data_localization(&self) -> bool {
        matches!(
            self,
            Self::TelecomProvider
                | Self::InternetServiceProvider
                | Self::SocialMediaPlatform
                | Self::EcommercePlatform
        )
    }

    /// Check if requires local presence in Vietnam
    pub fn requires_local_presence(&self) -> bool {
        matches!(
            self,
            Self::ForeignEnterprise
                | Self::SocialMediaPlatform
                | Self::EcommercePlatform
                | Self::OnlineGameProvider
        )
    }
}

/// Types of data subject to localization (Dữ liệu phải lưu trữ tại VN) - Article 26
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum LocalizedDataType {
    /// User personal data (Dữ liệu cá nhân người dùng)
    PersonalData,
    /// Data generated by users in Vietnam (Dữ liệu do người dùng VN tạo ra)
    UserGeneratedContent,
    /// Account information (Thông tin tài khoản)
    AccountInformation,
    /// Transaction data (Dữ liệu giao dịch)
    TransactionData,
    /// Other service-related data (Dữ liệu liên quan đến dịch vụ)
    ServiceData,
}

impl LocalizedDataType {
    /// Get Vietnamese description
    pub fn description_vi(&self) -> &'static str {
        match self {
            Self::PersonalData => "Dữ liệu cá nhân của người dùng Việt Nam",
            Self::UserGeneratedContent => "Dữ liệu do người dùng Việt Nam tạo ra",
            Self::AccountInformation => "Thông tin tài khoản người dùng",
            Self::TransactionData => "Dữ liệu về giao dịch, thanh toán",
            Self::ServiceData => "Dữ liệu khác liên quan đến dịch vụ",
        }
    }

    /// Minimum retention period in months (if applicable)
    pub fn minimum_retention_months(&self) -> Option<u8> {
        match self {
            Self::TransactionData => Some(36), // 3 years for transaction data
            Self::AccountInformation => Some(24), // 2 years for account info
            _ => None,
        }
    }
}

/// Prohibited content categories (Nội dung bị cấm) - Article 8
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ProhibitedContent {
    /// Opposition to Socialist Republic (Chống phá Nhà nước)
    AntiState,
    /// National security threats (Đe dọa an ninh quốc gia)
    NationalSecurityThreat,
    /// Fake news and misinformation (Tin giả, thông tin sai sự thật)
    FakeNews,
    /// Inciting violence (Kích động bạo lực)
    IncitingViolence,
    /// Obscene content (Nội dung khiêu dâm)
    ObsceneContent,
    /// Child exploitation (Xâm hại trẻ em)
    ChildExploitation,
    /// Hate speech (Kích động thù hận)
    HateSpeech,
    /// Gambling promotion (Quảng cáo cờ bạc)
    GamblingPromotion,
    /// Other prohibited content
    Other(String),
}

impl ProhibitedContent {
    /// Get Vietnamese description
    pub fn description_vi(&self) -> String {
        match self {
            Self::AntiState => "Chống phá Nhà nước Cộng hòa xã hội chủ nghĩa Việt Nam".to_string(),
            Self::NationalSecurityThreat => {
                "Đe dọa an ninh quốc gia, trật tự an toàn xã hội".to_string()
            }
            Self::FakeNews => "Thông tin giả mạo, sai sự thật".to_string(),
            Self::IncitingViolence => "Kích động bạo lực, gây rối trật tự công cộng".to_string(),
            Self::ObsceneContent => "Nội dung khiêu dâm, đồi trụy".to_string(),
            Self::ChildExploitation => "Xâm hại trẻ em".to_string(),
            Self::HateSpeech => "Kích động thù hận, phân biệt đối xử".to_string(),
            Self::GamblingPromotion => "Quảng cáo cờ bạc, ma túy".to_string(),
            Self::Other(desc) => desc.clone(),
        }
    }

    /// Get required removal time in hours (Article 16)
    pub fn removal_deadline_hours(&self) -> u8 {
        match self {
            Self::AntiState | Self::NationalSecurityThreat | Self::ChildExploitation => 12,
            _ => 24,
        }
    }
}

/// Data localization compliance
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DataLocalizationCompliance {
    /// Entity type
    pub entity: CybersecurityEntity,
    /// Has data stored in Vietnam
    pub has_vietnam_servers: bool,
    /// Has local representative office
    pub has_local_office: bool,
    /// Types of data being stored
    pub data_types: Vec<LocalizedDataType>,
    /// Can provide data to authorities within required time
    pub can_provide_data_to_authorities: bool,
}

impl DataLocalizationCompliance {
    /// Check if compliant with Article 26
    pub fn is_compliant(&self) -> bool {
        // Must have Vietnam servers if required
        if self.entity.requires_data_localization() && !self.has_vietnam_servers {
            return false;
        }

        // Must have local office if required
        if self.entity.requires_local_presence() && !self.has_local_office {
            return false;
        }

        // Must be able to provide data to authorities
        if !self.can_provide_data_to_authorities {
            return false;
        }

        true
    }

    /// Get list of compliance violations
    pub fn get_violations(&self) -> Vec<String> {
        let mut violations = Vec::new();

        if self.entity.requires_data_localization() && !self.has_vietnam_servers {
            violations.push("Chưa lưu trữ dữ liệu tại Việt Nam (Điều 26.3)".to_string());
        }

        if self.entity.requires_local_presence() && !self.has_local_office {
            violations.push("Chưa có văn phòng đại diện tại Việt Nam (Điều 26.7)".to_string());
        }

        if !self.can_provide_data_to_authorities {
            violations
                .push("Không thể cung cấp dữ liệu cho cơ quan chức năng (Điều 26.4)".to_string());
        }

        violations
    }
}

/// Content moderation requirement
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ContentModerationRequirement {
    /// Platform type
    pub platform: CybersecurityEntity,
    /// Has automated content filtering
    pub has_automated_filtering: bool,
    /// Has human moderation team
    pub has_human_moderators: bool,
    /// Can remove content within deadline
    pub can_meet_removal_deadline: bool,
    /// Has user reporting mechanism
    pub has_user_reporting: bool,
}

impl ContentModerationRequirement {
    /// Check if compliant with content moderation requirements
    pub fn is_compliant(&self) -> bool {
        self.has_automated_filtering
            && self.has_human_moderators
            && self.can_meet_removal_deadline
            && self.has_user_reporting
    }
}

/// Result type for cybersecurity law operations
pub type CybersecurityResult<T> = Result<T, CybersecurityError>;

/// Errors related to Cybersecurity Law
#[derive(Debug, Error)]
pub enum CybersecurityError {
    /// Data localization violation
    #[error("Vi phạm quy định lưu trữ dữ liệu (Điều 26): {reason}")]
    DataLocalizationViolation { reason: String },

    /// Prohibited content not removed
    #[error("Nội dung vi phạm chưa được gỡ bỏ (Điều 16): {content_type}")]
    ProhibitedContentNotRemoved { content_type: String },

    /// Missing local presence
    #[error("Chưa có đại diện tại Việt Nam (Điều 26.7): {entity}")]
    MissingLocalPresence { entity: String },

    /// Data not provided to authorities
    #[error("Không cung cấp dữ liệu cho cơ quan chức năng (Điều 26.4)")]
    DataNotProvided,

    /// Other compliance violation
    #[error("Vi phạm Luật An ninh mạng: {reason}")]
    ComplianceViolation { reason: String },
}

/// Validate data localization compliance
pub fn validate_data_localization(
    compliance: &DataLocalizationCompliance,
) -> CybersecurityResult<()> {
    if !compliance.is_compliant() {
        let violations = compliance.get_violations();
        return Err(CybersecurityError::DataLocalizationViolation {
            reason: violations.join("; "),
        });
    }
    Ok(())
}

/// Validate content removal deadline compliance
pub fn validate_content_removal_deadline(
    content_type: &ProhibitedContent,
    hours_since_notification: u8,
) -> CybersecurityResult<()> {
    let deadline = content_type.removal_deadline_hours();

    if hours_since_notification > deadline {
        Err(CybersecurityError::ProhibitedContentNotRemoved {
            content_type: content_type.description_vi(),
        })
    } else {
        Ok(())
    }
}

/// Get Cybersecurity Law checklist
pub fn get_cybersecurity_checklist() -> Vec<(&'static str, &'static str, &'static str)> {
    vec![
        (
            "Lưu trữ dữ liệu tại Việt Nam",
            "Data localization in Vietnam",
            "Điều 26.3",
        ),
        (
            "Văn phòng đại diện tại VN",
            "Representative office in Vietnam",
            "Điều 26.7",
        ),
        (
            "Cung cấp dữ liệu cho cơ quan chức năng",
            "Provide data to authorities",
            "Điều 26.4",
        ),
        (
            "Gỡ bỏ nội dung vi phạm trong 24h",
            "Remove prohibited content within 24h",
            "Điều 16",
        ),
        (
            "Bảo vệ thông tin cá nhân",
            "Personal data protection",
            "Điều 21",
        ),
        ("Chống tấn công mạng", "Cyber attack prevention", "Điều 19"),
        ("Xác thực người dùng", "User authentication", "Điều 15"),
        (
            "Báo cáo sự cố an ninh mạng",
            "Report cybersecurity incidents",
            "Điều 25",
        ),
    ]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_entity_requirements() {
        assert!(CybersecurityEntity::SocialMediaPlatform.requires_data_localization());
        assert!(CybersecurityEntity::SocialMediaPlatform.requires_local_presence());

        assert!(CybersecurityEntity::TelecomProvider.requires_data_localization());

        assert!(!CybersecurityEntity::DomesticEnterprise.requires_local_presence());
    }

    #[test]
    fn test_data_localization_compliance() {
        let compliant = DataLocalizationCompliance {
            entity: CybersecurityEntity::SocialMediaPlatform,
            has_vietnam_servers: true,
            has_local_office: true,
            data_types: vec![
                LocalizedDataType::PersonalData,
                LocalizedDataType::UserGeneratedContent,
            ],
            can_provide_data_to_authorities: true,
        };

        assert!(compliant.is_compliant());
        assert!(compliant.get_violations().is_empty());

        let non_compliant = DataLocalizationCompliance {
            entity: CybersecurityEntity::SocialMediaPlatform,
            has_vietnam_servers: false,
            has_local_office: false,
            data_types: vec![LocalizedDataType::PersonalData],
            can_provide_data_to_authorities: false,
        };

        assert!(!non_compliant.is_compliant());
        assert_eq!(non_compliant.get_violations().len(), 3);
    }

    #[test]
    fn test_prohibited_content_deadlines() {
        assert_eq!(ProhibitedContent::AntiState.removal_deadline_hours(), 12);
        assert_eq!(
            ProhibitedContent::ChildExploitation.removal_deadline_hours(),
            12
        );
        assert_eq!(ProhibitedContent::FakeNews.removal_deadline_hours(), 24);
        assert_eq!(
            ProhibitedContent::ObsceneContent.removal_deadline_hours(),
            24
        );
    }

    #[test]
    fn test_content_removal_validation() {
        let anti_state = ProhibitedContent::AntiState;

        // Within deadline
        assert!(validate_content_removal_deadline(&anti_state, 10).is_ok());

        // Exceeded deadline
        assert!(validate_content_removal_deadline(&anti_state, 15).is_err());
    }

    #[test]
    fn test_data_types() {
        assert_eq!(
            LocalizedDataType::TransactionData.minimum_retention_months(),
            Some(36)
        );
        assert_eq!(
            LocalizedDataType::AccountInformation.minimum_retention_months(),
            Some(24)
        );
        assert_eq!(
            LocalizedDataType::PersonalData.minimum_retention_months(),
            None
        );
    }

    #[test]
    fn test_content_moderation() {
        let compliant = ContentModerationRequirement {
            platform: CybersecurityEntity::SocialMediaPlatform,
            has_automated_filtering: true,
            has_human_moderators: true,
            can_meet_removal_deadline: true,
            has_user_reporting: true,
        };

        assert!(compliant.is_compliant());

        let non_compliant = ContentModerationRequirement {
            platform: CybersecurityEntity::SocialMediaPlatform,
            has_automated_filtering: false,
            has_human_moderators: true,
            can_meet_removal_deadline: true,
            has_user_reporting: false,
        };

        assert!(!non_compliant.is_compliant());
    }

    #[test]
    fn test_validation() {
        let compliant = DataLocalizationCompliance {
            entity: CybersecurityEntity::EcommercePlatform,
            has_vietnam_servers: true,
            has_local_office: true,
            data_types: vec![LocalizedDataType::TransactionData],
            can_provide_data_to_authorities: true,
        };

        assert!(validate_data_localization(&compliant).is_ok());

        let non_compliant = DataLocalizationCompliance {
            entity: CybersecurityEntity::EcommercePlatform,
            has_vietnam_servers: false,
            has_local_office: true,
            data_types: vec![LocalizedDataType::TransactionData],
            can_provide_data_to_authorities: true,
        };

        assert!(validate_data_localization(&non_compliant).is_err());
    }

    #[test]
    fn test_cybersecurity_checklist() {
        let checklist = get_cybersecurity_checklist();
        assert!(!checklist.is_empty());
        assert_eq!(checklist.len(), 8);
    }
}
