[package]
name = "legalis-sim"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Simulation engine for Legalis-RS"
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/legalis-sim"

[dependencies]
legalis-core.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
uuid.workspace = true
thiserror.workspace = true
chrono.workspace = true
indexmap.workspace = true
num_cpus.workspace = true
wide = "1.3"
rand.workspace = true

[dev-dependencies]
criterion = { workspace = true, features = ["async_tokio"] }

[[bench]]
name = "simulation"
harness = false
